package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

/**
 * AResourceJudgeDetailId generated by hbm2java
 */
public class AResourceJudgeDetailId implements java.io.Serializable {

	private String judgeId;
	private int judgeSeq;

	public AResourceJudgeDetailId() {
	}

	public AResourceJudgeDetailId(String judgeId, int judgeSeq) {
		this.judgeId = judgeId;
		this.judgeSeq = judgeSeq;
	}

	public String getJudgeId() {
		return this.judgeId;
	}

	public void setJudgeId(String judgeId) {
		this.judgeId = judgeId;
	}

	public int getJudgeSeq() {
		return this.judgeSeq;
	}

	public void setJudgeSeq(int judgeSeq) {
		this.judgeSeq = judgeSeq;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AResourceJudgeDetailId))
			return false;
		AResourceJudgeDetailId castOther = (AResourceJudgeDetailId) other;

		return ((this.getJudgeId() == castOther.getJudgeId()) || (this.getJudgeId() != null
				&& castOther.getJudgeId() != null && this.getJudgeId().equals(castOther.getJudgeId())))
				&& (this.getJudgeSeq() == castOther.getJudgeSeq());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getJudgeId() == null ? 0 : this.getJudgeId().hashCode());
		result = 37 * result + this.getJudgeSeq();
		return result;
	}

}
