package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AResourceDataHeader generated by hbm2java
 */
public class AResourceDataHeader implements java.io.Serializable {

	private String dataId;
	private String relationid;
	private String dataState;
	private String deptid;
	private String employeeid;
	private Date finalTime;
	private Date nextTime;
	private String creator;
	private Date createtime;
	private String binid;
	private Integer priority;
	private String isValid;
	private Set AResourceDataDetails = new HashSet(0);

	public AResourceDataHeader() {
	}

	public AResourceDataHeader(String dataId) {
		this.dataId = dataId;
	}

	public AResourceDataHeader(String dataId, String relationid, String dataState, String deptid, String employeeid,
			Date finalTime, Date nextTime, String creator, Date createtime, String binid, Integer priority,
			String isValid, Set AResourceDataDetails) {
		this.dataId = dataId;
		this.relationid = relationid;
		this.dataState = dataState;
		this.deptid = deptid;
		this.employeeid = employeeid;
		this.finalTime = finalTime;
		this.nextTime = nextTime;
		this.creator = creator;
		this.createtime = createtime;
		this.binid = binid;
		this.priority = priority;
		this.isValid = isValid;
		this.AResourceDataDetails = AResourceDataDetails;
	}

	public String getDataId() {
		return this.dataId;
	}

	public void setDataId(String dataId) {
		this.dataId = dataId;
	}

	public String getRelationid() {
		return this.relationid;
	}

	public void setRelationid(String relationid) {
		this.relationid = relationid;
	}

	public String getDataState() {
		return this.dataState;
	}

	public void setDataState(String dataState) {
		this.dataState = dataState;
	}

	public String getDeptid() {
		return this.deptid;
	}

	public void setDeptid(String deptid) {
		this.deptid = deptid;
	}

	public String getEmployeeid() {
		return this.employeeid;
	}

	public void setEmployeeid(String employeeid) {
		this.employeeid = employeeid;
	}

	public Date getFinalTime() {
		return this.finalTime;
	}

	public void setFinalTime(Date finalTime) {
		this.finalTime = finalTime;
	}

	public Date getNextTime() {
		return this.nextTime;
	}

	public void setNextTime(Date nextTime) {
		this.nextTime = nextTime;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getBinid() {
		return this.binid;
	}

	public void setBinid(String binid) {
		this.binid = binid;
	}

	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	public String getIsValid() {
		return this.isValid;
	}

	public void setIsValid(String isValid) {
		this.isValid = isValid;
	}

	public Set getAResourceDataDetails() {
		return this.AResourceDataDetails;
	}

	public void setAResourceDataDetails(Set AResourceDataDetails) {
		this.AResourceDataDetails = AResourceDataDetails;
	}

}
