package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * AResourceCalendar generated by hbm2java
 */
public class AResourceCalendar implements java.io.Serializable {

	private AResourceCalendarId id;
	private String uniqueid;
	private String dataType;
	private String resourceUid;
	private String dataEmp;
	private String isValid;
	private Date startTime;
	private Date finishTime;
	private Integer duringTime;
	private String dataState;
	private Integer dataNum;

	public AResourceCalendar() {
	}

	public AResourceCalendar(AResourceCalendarId id) {
		this.id = id;
	}

	public AResourceCalendar(AResourceCalendarId id, String uniqueid, String dataType, String resourceUid,
			String dataEmp, String isValid, Date startTime, Date finishTime, Integer duringTime, String dataState,
			Integer dataNum) {
		this.id = id;
		this.uniqueid = uniqueid;
		this.dataType = dataType;
		this.resourceUid = resourceUid;
		this.dataEmp = dataEmp;
		this.isValid = isValid;
		this.startTime = startTime;
		this.finishTime = finishTime;
		this.duringTime = duringTime;
		this.dataState = dataState;
		this.dataNum = dataNum;
	}

	public AResourceCalendarId getId() {
		return this.id;
	}

	public void setId(AResourceCalendarId id) {
		this.id = id;
	}

	public String getUniqueid() {
		return this.uniqueid;
	}

	public void setUniqueid(String uniqueid) {
		this.uniqueid = uniqueid;
	}

	public String getDataType() {
		return this.dataType;
	}

	public void setDataType(String dataType) {
		this.dataType = dataType;
	}

	public String getResourceUid() {
		return this.resourceUid;
	}

	public void setResourceUid(String resourceUid) {
		this.resourceUid = resourceUid;
	}

	public String getDataEmp() {
		return this.dataEmp;
	}

	public void setDataEmp(String dataEmp) {
		this.dataEmp = dataEmp;
	}

	public String getIsValid() {
		return this.isValid;
	}

	public void setIsValid(String isValid) {
		this.isValid = isValid;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getFinishTime() {
		return this.finishTime;
	}

	public void setFinishTime(Date finishTime) {
		this.finishTime = finishTime;
	}

	public Integer getDuringTime() {
		return this.duringTime;
	}

	public void setDuringTime(Integer duringTime) {
		this.duringTime = duringTime;
	}

	public String getDataState() {
		return this.dataState;
	}

	public void setDataState(String dataState) {
		this.dataState = dataState;
	}

	public Integer getDataNum() {
		return this.dataNum;
	}

	public void setDataNum(Integer dataNum) {
		this.dataNum = dataNum;
	}

}
