package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

/**
 * BClassAttributeRelation generated by hbm2java
 */
public class BClassAttributeRelation implements java.io.Serializable {

	private String uuid;
	private BAttribute BAttribute;
	private BClassinfo BClassinfo;
	private String notes;
	private Byte effective;
	private String relationType;
	private Short attributeIndex;
	private String attributeGroupName;

	public BClassAttributeRelation() {
	}

	public BClassAttributeRelation(String uuid, BAttribute BAttribute) {
		this.uuid = uuid;
		this.BAttribute = BAttribute;
	}

	public BClassAttributeRelation(String uuid, BAttribute BAttribute, BClassinfo BClassinfo, String notes,
			Byte effective, String relationType, Short attributeIndex, String attributeGroupName) {
		this.uuid = uuid;
		this.BAttribute = BAttribute;
		this.BClassinfo = BClassinfo;
		this.notes = notes;
		this.effective = effective;
		this.relationType = relationType;
		this.attributeIndex = attributeIndex;
		this.attributeGroupName = attributeGroupName;
	}

	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public BAttribute getBAttribute() {
		return this.BAttribute;
	}

	public void setBAttribute(BAttribute BAttribute) {
		this.BAttribute = BAttribute;
	}

	public BClassinfo getBClassinfo() {
		return this.BClassinfo;
	}

	public void setBClassinfo(BClassinfo BClassinfo) {
		this.BClassinfo = BClassinfo;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public Byte getEffective() {
		return this.effective;
	}

	public void setEffective(Byte effective) {
		this.effective = effective;
	}

	public String getRelationType() {
		return this.relationType;
	}

	public void setRelationType(String relationType) {
		this.relationType = relationType;
	}

	public Short getAttributeIndex() {
		return this.attributeIndex;
	}

	public void setAttributeIndex(Short attributeIndex) {
		this.attributeIndex = attributeIndex;
	}

	public String getAttributeGroupName() {
		return this.attributeGroupName;
	}

	public void setAttributeGroupName(String attributeGroupName) {
		this.attributeGroupName = attributeGroupName;
	}

}
