package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

/**
 * BCostStructure generated by hbm2java
 */
public class BCostStructure implements java.io.Serializable {

	private BCostStructureId id;

	public BCostStructure() {
	}

	public BCostStructure(BCostStructureId id) {
		this.id = id;
	}

	public BCostStructureId getId() {
		return this.id;
	}

	public void setId(BCostStructureId id) {
		this.id = id;
	}

}
