package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * BDeptOptype generated by hbm2java
 */
public class BDeptOptype implements java.io.Serializable {

	private BDeptOptypeId id;
	private BOptype BOptype;
	private BigDecimal estiduration;
	private BigDecimal wagerate;
	private String creator;
	private Date createtime;

	public BDeptOptype() {
	}

	public BDeptOptype(BDeptOptypeId id, BOptype BOptype) {
		this.id = id;
		this.BOptype = BOptype;
	}

	public BDeptOptype(BDeptOptypeId id, BOptype BOptype, BigDecimal estiduration, BigDecimal wagerate, String creator,
			Date createtime) {
		this.id = id;
		this.BOptype = BOptype;
		this.estiduration = estiduration;
		this.wagerate = wagerate;
		this.creator = creator;
		this.createtime = createtime;
	}

	public BDeptOptypeId getId() {
		return this.id;
	}

	public void setId(BDeptOptypeId id) {
		this.id = id;
	}

	public BOptype getBOptype() {
		return this.BOptype;
	}

	public void setBOptype(BOptype BOptype) {
		this.BOptype = BOptype;
	}

	public BigDecimal getEstiduration() {
		return this.estiduration;
	}

	public void setEstiduration(BigDecimal estiduration) {
		this.estiduration = estiduration;
	}

	public BigDecimal getWagerate() {
		return this.wagerate;
	}

	public void setWagerate(BigDecimal wagerate) {
		this.wagerate = wagerate;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

}
