package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;

/**
 * BOperatestepId generated by hbm2java
 */
public class BOperatestepId implements java.io.Serializable {

	private long stepid;
	private BigDecimal opuid;

	public BOperatestepId() {
	}

	public BOperatestepId(long stepid, BigDecimal opuid) {
		this.stepid = stepid;
		this.opuid = opuid;
	}

	public long getStepid() {
		return this.stepid;
	}

	public void setStepid(long stepid) {
		this.stepid = stepid;
	}

	public BigDecimal getOpuid() {
		return this.opuid;
	}

	public void setOpuid(BigDecimal opuid) {
		this.opuid = opuid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BOperatestepId))
			return false;
		BOperatestepId castOther = (BOperatestepId) other;

		return (this.getStepid() == castOther.getStepid())
				&& ((this.getOpuid() == castOther.getOpuid()) || (this.getOpuid() != null
						&& castOther.getOpuid() != null && this.getOpuid().equals(castOther.getOpuid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getStepid();
		result = 37 * result + (getOpuid() == null ? 0 : this.getOpuid().hashCode());
		return result;
	}

}
