package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

/**
 * BOperationLinkId generated by hbm2java
 */
public class BOperationLinkId implements java.io.Serializable {

	private String opuid1;
	private String opuid2;
	private String operlinktype;

	public BOperationLinkId() {
	}

	public BOperationLinkId(String opuid1, String opuid2, String operlinktype) {
		this.opuid1 = opuid1;
		this.opuid2 = opuid2;
		this.operlinktype = operlinktype;
	}

	public String getOpuid1() {
		return this.opuid1;
	}

	public void setOpuid1(String opuid1) {
		this.opuid1 = opuid1;
	}

	public String getOpuid2() {
		return this.opuid2;
	}

	public void setOpuid2(String opuid2) {
		this.opuid2 = opuid2;
	}

	public String getOperlinktype() {
		return this.operlinktype;
	}

	public void setOperlinktype(String operlinktype) {
		this.operlinktype = operlinktype;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BOperationLinkId))
			return false;
		BOperationLinkId castOther = (BOperationLinkId) other;

		return ((this.getOpuid1() == castOther.getOpuid1()) || (this.getOpuid1() != null
				&& castOther.getOpuid1() != null && this.getOpuid1().equals(castOther.getOpuid1())))
				&& ((this.getOpuid2() == castOther.getOpuid2()) || (this.getOpuid2() != null
						&& castOther.getOpuid2() != null && this.getOpuid2().equals(castOther.getOpuid2())))
				&& ((this.getOperlinktype() == castOther.getOperlinktype())
						|| (this.getOperlinktype() != null && castOther.getOperlinktype() != null
								&& this.getOperlinktype().equals(castOther.getOperlinktype())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOpuid1() == null ? 0 : this.getOpuid1().hashCode());
		result = 37 * result + (getOpuid2() == null ? 0 : this.getOpuid2().hashCode());
		result = 37 * result + (getOperlinktype() == null ? 0 : this.getOperlinktype().hashCode());
		return result;
	}

}
