package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

/**
 * BvEffectBomMrp generated by hbm2java
 */
public class BvEffectBomMrp implements java.io.Serializable {

	private BvEffectBomMrpId id;

	public BvEffectBomMrp() {
	}

	public BvEffectBomMrp(BvEffectBomMrpId id) {
		this.id = id;
	}

	public BvEffectBomMrpId getId() {
		return this.id;
	}

	public void setId(BvEffectBomMrpId id) {
		this.id = id;
	}

}
