package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;

/**
 * BvOperId generated by hbm2java
 */
public class BvOperId implements java.io.Serializable {

	private String routing;
	private BigDecimal operationId;
	private BigDecimal opuid;
	private String operationName;
	private String operationGroup;
	private BigDecimal preopTime;
	private BigDecimal unitRuntime;
	private BigDecimal postopTime;
	private String baseMachineResource;
	private String machineNumber;
	private Long numOperators;
	private Long parallel;
	private String parallelThreshold;
	private String minimumParallelSubtask;
	private Long useMprsIfNotLate;
	private Long minOperationTime;
	private BigDecimal opEstimatedQueneTime;
	private BigDecimal opMininumQueneTime;
	private BigDecimal baseYield;
	private Long interruptible;
	private Long operationType;
	private Long priority;
	private String queueCalendarName;
	private String rampupCalendarName;
	private Long transferBatchQuantity;
	private Long isCrossOperation;
	private Long needCheck;
	private Long isCriticalOperation;
	private String operationSpecification;
	private Long materialCheckIn;
	private Long materialCheckOut;
	private Long operationCostSum;
	private Long laborCost;
	private Long machineCost;
	private Long linkDownstreamP;
	private Long linkDownstreamMinWip;
	private Long linkDownstreamMaxWip;
	private String unitRuntimeCostPer;
	private Long unitRuntimeCostPerTime;
	private String unitWipCarryCostPer;
	private Long unitWipCarryCostPerTime;
	private String sequenceDependentSetupType;
	private String sequenceDependentSetupType2;
	private String sequenceDependentSetupType3;
	private String note;
	private String routingType;
	private String operationNote;
	private BigDecimal workcoefficient;
	private Date changetime;
	private String changer;
	private String changereason;
	private BigDecimal changestate;
	private Byte effective;
	private String creator;
	private Date createtime;
	private BigDecimal uniqueid;
	private Long dispatchgrade;
	private Integer sampleqty;
	private BigDecimal samplepercent;
	private String operationIddesc;
	private String estipretime;
	private String estiruntime;
	private String sampleOpid;
	private Byte needSample;
	private Boolean checkstate;
	private String groupuid;
	private String opid;
	private Long optype;
	private String versionid;
	private String routingNote;
	private BigDecimal sampleRuntime;
	private Boolean needFirstcheck;
	private BigDecimal checkpercent;
	private String refrouting;
	private String BRoutineOutUid;
	private String deptid;
	private String deviceuid;
	private String operationContentTt;
	private BigDecimal parentopuid;
	private String ncNumber;
	private String ncVersionid;
	private String isSpecialOperation;
	private Byte preparegrade;
	private Boolean needPhoto;
	private Clob operationSimpleContent;
	private Clob operationContent;
	private Long isStatisticCheck;
	private Boolean keycount;
	private String routingName;
	private String RVersionid;
	private String partNumber;
	private String partName;
	private String PVersionid;
	private String drawingid;
	private String partSort2;
	private String partNumberType;
	private String classname;
	private String bigmodelName;

	public BvOperId() {
	}

	public BvOperId(String routing, BigDecimal operationId, BigDecimal opuid, BigDecimal uniqueid, String partNumber) {
		this.routing = routing;
		this.operationId = operationId;
		this.opuid = opuid;
		this.uniqueid = uniqueid;
		this.partNumber = partNumber;
	}

	public BvOperId(String routing, BigDecimal operationId, BigDecimal opuid, String operationName,
			String operationGroup, BigDecimal preopTime, BigDecimal unitRuntime, BigDecimal postopTime,
			String baseMachineResource, String machineNumber, Long numOperators, Long parallel,
			String parallelThreshold, String minimumParallelSubtask, Long useMprsIfNotLate, Long minOperationTime,
			BigDecimal opEstimatedQueneTime, BigDecimal opMininumQueneTime, BigDecimal baseYield, Long interruptible,
			Long operationType, Long priority, String queueCalendarName, String rampupCalendarName,
			Long transferBatchQuantity, Long isCrossOperation, Long needCheck, Long isCriticalOperation,
			String operationSpecification, Long materialCheckIn, Long materialCheckOut, Long operationCostSum,
			Long laborCost, Long machineCost, Long linkDownstreamP, Long linkDownstreamMinWip,
			Long linkDownstreamMaxWip, String unitRuntimeCostPer, Long unitRuntimeCostPerTime,
			String unitWipCarryCostPer, Long unitWipCarryCostPerTime, String sequenceDependentSetupType,
			String sequenceDependentSetupType2, String sequenceDependentSetupType3, String note, String routingType,
			String operationNote, BigDecimal workcoefficient, Date changetime, String changer, String changereason,
			BigDecimal changestate, Byte effective, String creator, Date createtime, BigDecimal uniqueid,
			Long dispatchgrade, Integer sampleqty, BigDecimal samplepercent, String operationIddesc, String estipretime,
			String estiruntime, String sampleOpid, Byte needSample, Boolean checkstate, String groupuid, String opid,
			Long optype, String versionid, String routingNote, BigDecimal sampleRuntime, Boolean needFirstcheck,
			BigDecimal checkpercent, String refrouting, String BRoutineOutUid, String deptid, String deviceuid,
			String operationContentTt, BigDecimal parentopuid, String ncNumber, String ncVersionid,
			String isSpecialOperation, Byte preparegrade, Boolean needPhoto, Clob operationSimpleContent,
			Clob operationContent, Long isStatisticCheck, Boolean keycount, String routingName, String RVersionid,
			String partNumber, String partName, String PVersionid, String drawingid, String partSort2,
			String partNumberType, String classname, String bigmodelName) {
		this.routing = routing;
		this.operationId = operationId;
		this.opuid = opuid;
		this.operationName = operationName;
		this.operationGroup = operationGroup;
		this.preopTime = preopTime;
		this.unitRuntime = unitRuntime;
		this.postopTime = postopTime;
		this.baseMachineResource = baseMachineResource;
		this.machineNumber = machineNumber;
		this.numOperators = numOperators;
		this.parallel = parallel;
		this.parallelThreshold = parallelThreshold;
		this.minimumParallelSubtask = minimumParallelSubtask;
		this.useMprsIfNotLate = useMprsIfNotLate;
		this.minOperationTime = minOperationTime;
		this.opEstimatedQueneTime = opEstimatedQueneTime;
		this.opMininumQueneTime = opMininumQueneTime;
		this.baseYield = baseYield;
		this.interruptible = interruptible;
		this.operationType = operationType;
		this.priority = priority;
		this.queueCalendarName = queueCalendarName;
		this.rampupCalendarName = rampupCalendarName;
		this.transferBatchQuantity = transferBatchQuantity;
		this.isCrossOperation = isCrossOperation;
		this.needCheck = needCheck;
		this.isCriticalOperation = isCriticalOperation;
		this.operationSpecification = operationSpecification;
		this.materialCheckIn = materialCheckIn;
		this.materialCheckOut = materialCheckOut;
		this.operationCostSum = operationCostSum;
		this.laborCost = laborCost;
		this.machineCost = machineCost;
		this.linkDownstreamP = linkDownstreamP;
		this.linkDownstreamMinWip = linkDownstreamMinWip;
		this.linkDownstreamMaxWip = linkDownstreamMaxWip;
		this.unitRuntimeCostPer = unitRuntimeCostPer;
		this.unitRuntimeCostPerTime = unitRuntimeCostPerTime;
		this.unitWipCarryCostPer = unitWipCarryCostPer;
		this.unitWipCarryCostPerTime = unitWipCarryCostPerTime;
		this.sequenceDependentSetupType = sequenceDependentSetupType;
		this.sequenceDependentSetupType2 = sequenceDependentSetupType2;
		this.sequenceDependentSetupType3 = sequenceDependentSetupType3;
		this.note = note;
		this.routingType = routingType;
		this.operationNote = operationNote;
		this.workcoefficient = workcoefficient;
		this.changetime = changetime;
		this.changer = changer;
		this.changereason = changereason;
		this.changestate = changestate;
		this.effective = effective;
		this.creator = creator;
		this.createtime = createtime;
		this.uniqueid = uniqueid;
		this.dispatchgrade = dispatchgrade;
		this.sampleqty = sampleqty;
		this.samplepercent = samplepercent;
		this.operationIddesc = operationIddesc;
		this.estipretime = estipretime;
		this.estiruntime = estiruntime;
		this.sampleOpid = sampleOpid;
		this.needSample = needSample;
		this.checkstate = checkstate;
		this.groupuid = groupuid;
		this.opid = opid;
		this.optype = optype;
		this.versionid = versionid;
		this.routingNote = routingNote;
		this.sampleRuntime = sampleRuntime;
		this.needFirstcheck = needFirstcheck;
		this.checkpercent = checkpercent;
		this.refrouting = refrouting;
		this.BRoutineOutUid = BRoutineOutUid;
		this.deptid = deptid;
		this.deviceuid = deviceuid;
		this.operationContentTt = operationContentTt;
		this.parentopuid = parentopuid;
		this.ncNumber = ncNumber;
		this.ncVersionid = ncVersionid;
		this.isSpecialOperation = isSpecialOperation;
		this.preparegrade = preparegrade;
		this.needPhoto = needPhoto;
		this.operationSimpleContent = operationSimpleContent;
		this.operationContent = operationContent;
		this.isStatisticCheck = isStatisticCheck;
		this.keycount = keycount;
		this.routingName = routingName;
		this.RVersionid = RVersionid;
		this.partNumber = partNumber;
		this.partName = partName;
		this.PVersionid = PVersionid;
		this.drawingid = drawingid;
		this.partSort2 = partSort2;
		this.partNumberType = partNumberType;
		this.classname = classname;
		this.bigmodelName = bigmodelName;
	}

	public String getRouting() {
		return this.routing;
	}

	public void setRouting(String routing) {
		this.routing = routing;
	}

	public BigDecimal getOperationId() {
		return this.operationId;
	}

	public void setOperationId(BigDecimal operationId) {
		this.operationId = operationId;
	}

	public BigDecimal getOpuid() {
		return this.opuid;
	}

	public void setOpuid(BigDecimal opuid) {
		this.opuid = opuid;
	}

	public String getOperationName() {
		return this.operationName;
	}

	public void setOperationName(String operationName) {
		this.operationName = operationName;
	}

	public String getOperationGroup() {
		return this.operationGroup;
	}

	public void setOperationGroup(String operationGroup) {
		this.operationGroup = operationGroup;
	}

	public BigDecimal getPreopTime() {
		return this.preopTime;
	}

	public void setPreopTime(BigDecimal preopTime) {
		this.preopTime = preopTime;
	}

	public BigDecimal getUnitRuntime() {
		return this.unitRuntime;
	}

	public void setUnitRuntime(BigDecimal unitRuntime) {
		this.unitRuntime = unitRuntime;
	}

	public BigDecimal getPostopTime() {
		return this.postopTime;
	}

	public void setPostopTime(BigDecimal postopTime) {
		this.postopTime = postopTime;
	}

	public String getBaseMachineResource() {
		return this.baseMachineResource;
	}

	public void setBaseMachineResource(String baseMachineResource) {
		this.baseMachineResource = baseMachineResource;
	}

	public String getMachineNumber() {
		return this.machineNumber;
	}

	public void setMachineNumber(String machineNumber) {
		this.machineNumber = machineNumber;
	}

	public Long getNumOperators() {
		return this.numOperators;
	}

	public void setNumOperators(Long numOperators) {
		this.numOperators = numOperators;
	}

	public Long getParallel() {
		return this.parallel;
	}

	public void setParallel(Long parallel) {
		this.parallel = parallel;
	}

	public String getParallelThreshold() {
		return this.parallelThreshold;
	}

	public void setParallelThreshold(String parallelThreshold) {
		this.parallelThreshold = parallelThreshold;
	}

	public String getMinimumParallelSubtask() {
		return this.minimumParallelSubtask;
	}

	public void setMinimumParallelSubtask(String minimumParallelSubtask) {
		this.minimumParallelSubtask = minimumParallelSubtask;
	}

	public Long getUseMprsIfNotLate() {
		return this.useMprsIfNotLate;
	}

	public void setUseMprsIfNotLate(Long useMprsIfNotLate) {
		this.useMprsIfNotLate = useMprsIfNotLate;
	}

	public Long getMinOperationTime() {
		return this.minOperationTime;
	}

	public void setMinOperationTime(Long minOperationTime) {
		this.minOperationTime = minOperationTime;
	}

	public BigDecimal getOpEstimatedQueneTime() {
		return this.opEstimatedQueneTime;
	}

	public void setOpEstimatedQueneTime(BigDecimal opEstimatedQueneTime) {
		this.opEstimatedQueneTime = opEstimatedQueneTime;
	}

	public BigDecimal getOpMininumQueneTime() {
		return this.opMininumQueneTime;
	}

	public void setOpMininumQueneTime(BigDecimal opMininumQueneTime) {
		this.opMininumQueneTime = opMininumQueneTime;
	}

	public BigDecimal getBaseYield() {
		return this.baseYield;
	}

	public void setBaseYield(BigDecimal baseYield) {
		this.baseYield = baseYield;
	}

	public Long getInterruptible() {
		return this.interruptible;
	}

	public void setInterruptible(Long interruptible) {
		this.interruptible = interruptible;
	}

	public Long getOperationType() {
		return this.operationType;
	}

	public void setOperationType(Long operationType) {
		this.operationType = operationType;
	}

	public Long getPriority() {
		return this.priority;
	}

	public void setPriority(Long priority) {
		this.priority = priority;
	}

	public String getQueueCalendarName() {
		return this.queueCalendarName;
	}

	public void setQueueCalendarName(String queueCalendarName) {
		this.queueCalendarName = queueCalendarName;
	}

	public String getRampupCalendarName() {
		return this.rampupCalendarName;
	}

	public void setRampupCalendarName(String rampupCalendarName) {
		this.rampupCalendarName = rampupCalendarName;
	}

	public Long getTransferBatchQuantity() {
		return this.transferBatchQuantity;
	}

	public void setTransferBatchQuantity(Long transferBatchQuantity) {
		this.transferBatchQuantity = transferBatchQuantity;
	}

	public Long getIsCrossOperation() {
		return this.isCrossOperation;
	}

	public void setIsCrossOperation(Long isCrossOperation) {
		this.isCrossOperation = isCrossOperation;
	}

	public Long getNeedCheck() {
		return this.needCheck;
	}

	public void setNeedCheck(Long needCheck) {
		this.needCheck = needCheck;
	}

	public Long getIsCriticalOperation() {
		return this.isCriticalOperation;
	}

	public void setIsCriticalOperation(Long isCriticalOperation) {
		this.isCriticalOperation = isCriticalOperation;
	}

	public String getOperationSpecification() {
		return this.operationSpecification;
	}

	public void setOperationSpecification(String operationSpecification) {
		this.operationSpecification = operationSpecification;
	}

	public Long getMaterialCheckIn() {
		return this.materialCheckIn;
	}

	public void setMaterialCheckIn(Long materialCheckIn) {
		this.materialCheckIn = materialCheckIn;
	}

	public Long getMaterialCheckOut() {
		return this.materialCheckOut;
	}

	public void setMaterialCheckOut(Long materialCheckOut) {
		this.materialCheckOut = materialCheckOut;
	}

	public Long getOperationCostSum() {
		return this.operationCostSum;
	}

	public void setOperationCostSum(Long operationCostSum) {
		this.operationCostSum = operationCostSum;
	}

	public Long getLaborCost() {
		return this.laborCost;
	}

	public void setLaborCost(Long laborCost) {
		this.laborCost = laborCost;
	}

	public Long getMachineCost() {
		return this.machineCost;
	}

	public void setMachineCost(Long machineCost) {
		this.machineCost = machineCost;
	}

	public Long getLinkDownstreamP() {
		return this.linkDownstreamP;
	}

	public void setLinkDownstreamP(Long linkDownstreamP) {
		this.linkDownstreamP = linkDownstreamP;
	}

	public Long getLinkDownstreamMinWip() {
		return this.linkDownstreamMinWip;
	}

	public void setLinkDownstreamMinWip(Long linkDownstreamMinWip) {
		this.linkDownstreamMinWip = linkDownstreamMinWip;
	}

	public Long getLinkDownstreamMaxWip() {
		return this.linkDownstreamMaxWip;
	}

	public void setLinkDownstreamMaxWip(Long linkDownstreamMaxWip) {
		this.linkDownstreamMaxWip = linkDownstreamMaxWip;
	}

	public String getUnitRuntimeCostPer() {
		return this.unitRuntimeCostPer;
	}

	public void setUnitRuntimeCostPer(String unitRuntimeCostPer) {
		this.unitRuntimeCostPer = unitRuntimeCostPer;
	}

	public Long getUnitRuntimeCostPerTime() {
		return this.unitRuntimeCostPerTime;
	}

	public void setUnitRuntimeCostPerTime(Long unitRuntimeCostPerTime) {
		this.unitRuntimeCostPerTime = unitRuntimeCostPerTime;
	}

	public String getUnitWipCarryCostPer() {
		return this.unitWipCarryCostPer;
	}

	public void setUnitWipCarryCostPer(String unitWipCarryCostPer) {
		this.unitWipCarryCostPer = unitWipCarryCostPer;
	}

	public Long getUnitWipCarryCostPerTime() {
		return this.unitWipCarryCostPerTime;
	}

	public void setUnitWipCarryCostPerTime(Long unitWipCarryCostPerTime) {
		this.unitWipCarryCostPerTime = unitWipCarryCostPerTime;
	}

	public String getSequenceDependentSetupType() {
		return this.sequenceDependentSetupType;
	}

	public void setSequenceDependentSetupType(String sequenceDependentSetupType) {
		this.sequenceDependentSetupType = sequenceDependentSetupType;
	}

	public String getSequenceDependentSetupType2() {
		return this.sequenceDependentSetupType2;
	}

	public void setSequenceDependentSetupType2(String sequenceDependentSetupType2) {
		this.sequenceDependentSetupType2 = sequenceDependentSetupType2;
	}

	public String getSequenceDependentSetupType3() {
		return this.sequenceDependentSetupType3;
	}

	public void setSequenceDependentSetupType3(String sequenceDependentSetupType3) {
		this.sequenceDependentSetupType3 = sequenceDependentSetupType3;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getRoutingType() {
		return this.routingType;
	}

	public void setRoutingType(String routingType) {
		this.routingType = routingType;
	}

	public String getOperationNote() {
		return this.operationNote;
	}

	public void setOperationNote(String operationNote) {
		this.operationNote = operationNote;
	}

	public BigDecimal getWorkcoefficient() {
		return this.workcoefficient;
	}

	public void setWorkcoefficient(BigDecimal workcoefficient) {
		this.workcoefficient = workcoefficient;
	}

	public Date getChangetime() {
		return this.changetime;
	}

	public void setChangetime(Date changetime) {
		this.changetime = changetime;
	}

	public String getChanger() {
		return this.changer;
	}

	public void setChanger(String changer) {
		this.changer = changer;
	}

	public String getChangereason() {
		return this.changereason;
	}

	public void setChangereason(String changereason) {
		this.changereason = changereason;
	}

	public BigDecimal getChangestate() {
		return this.changestate;
	}

	public void setChangestate(BigDecimal changestate) {
		this.changestate = changestate;
	}

	public Byte getEffective() {
		return this.effective;
	}

	public void setEffective(Byte effective) {
		this.effective = effective;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public BigDecimal getUniqueid() {
		return this.uniqueid;
	}

	public void setUniqueid(BigDecimal uniqueid) {
		this.uniqueid = uniqueid;
	}

	public Long getDispatchgrade() {
		return this.dispatchgrade;
	}

	public void setDispatchgrade(Long dispatchgrade) {
		this.dispatchgrade = dispatchgrade;
	}

	public Integer getSampleqty() {
		return this.sampleqty;
	}

	public void setSampleqty(Integer sampleqty) {
		this.sampleqty = sampleqty;
	}

	public BigDecimal getSamplepercent() {
		return this.samplepercent;
	}

	public void setSamplepercent(BigDecimal samplepercent) {
		this.samplepercent = samplepercent;
	}

	public String getOperationIddesc() {
		return this.operationIddesc;
	}

	public void setOperationIddesc(String operationIddesc) {
		this.operationIddesc = operationIddesc;
	}

	public String getEstipretime() {
		return this.estipretime;
	}

	public void setEstipretime(String estipretime) {
		this.estipretime = estipretime;
	}

	public String getEstiruntime() {
		return this.estiruntime;
	}

	public void setEstiruntime(String estiruntime) {
		this.estiruntime = estiruntime;
	}

	public String getSampleOpid() {
		return this.sampleOpid;
	}

	public void setSampleOpid(String sampleOpid) {
		this.sampleOpid = sampleOpid;
	}

	public Byte getNeedSample() {
		return this.needSample;
	}

	public void setNeedSample(Byte needSample) {
		this.needSample = needSample;
	}

	public Boolean getCheckstate() {
		return this.checkstate;
	}

	public void setCheckstate(Boolean checkstate) {
		this.checkstate = checkstate;
	}

	public String getGroupuid() {
		return this.groupuid;
	}

	public void setGroupuid(String groupuid) {
		this.groupuid = groupuid;
	}

	public String getOpid() {
		return this.opid;
	}

	public void setOpid(String opid) {
		this.opid = opid;
	}

	public Long getOptype() {
		return this.optype;
	}

	public void setOptype(Long optype) {
		this.optype = optype;
	}

	public String getVersionid() {
		return this.versionid;
	}

	public void setVersionid(String versionid) {
		this.versionid = versionid;
	}

	public String getRoutingNote() {
		return this.routingNote;
	}

	public void setRoutingNote(String routingNote) {
		this.routingNote = routingNote;
	}

	public BigDecimal getSampleRuntime() {
		return this.sampleRuntime;
	}

	public void setSampleRuntime(BigDecimal sampleRuntime) {
		this.sampleRuntime = sampleRuntime;
	}

	public Boolean getNeedFirstcheck() {
		return this.needFirstcheck;
	}

	public void setNeedFirstcheck(Boolean needFirstcheck) {
		this.needFirstcheck = needFirstcheck;
	}

	public BigDecimal getCheckpercent() {
		return this.checkpercent;
	}

	public void setCheckpercent(BigDecimal checkpercent) {
		this.checkpercent = checkpercent;
	}

	public String getRefrouting() {
		return this.refrouting;
	}

	public void setRefrouting(String refrouting) {
		this.refrouting = refrouting;
	}

	public String getBRoutineOutUid() {
		return this.BRoutineOutUid;
	}

	public void setBRoutineOutUid(String BRoutineOutUid) {
		this.BRoutineOutUid = BRoutineOutUid;
	}

	public String getDeptid() {
		return this.deptid;
	}

	public void setDeptid(String deptid) {
		this.deptid = deptid;
	}

	public String getDeviceuid() {
		return this.deviceuid;
	}

	public void setDeviceuid(String deviceuid) {
		this.deviceuid = deviceuid;
	}

	public String getOperationContentTt() {
		return this.operationContentTt;
	}

	public void setOperationContentTt(String operationContentTt) {
		this.operationContentTt = operationContentTt;
	}

	public BigDecimal getParentopuid() {
		return this.parentopuid;
	}

	public void setParentopuid(BigDecimal parentopuid) {
		this.parentopuid = parentopuid;
	}

	public String getNcNumber() {
		return this.ncNumber;
	}

	public void setNcNumber(String ncNumber) {
		this.ncNumber = ncNumber;
	}

	public String getNcVersionid() {
		return this.ncVersionid;
	}

	public void setNcVersionid(String ncVersionid) {
		this.ncVersionid = ncVersionid;
	}

	public String getIsSpecialOperation() {
		return this.isSpecialOperation;
	}

	public void setIsSpecialOperation(String isSpecialOperation) {
		this.isSpecialOperation = isSpecialOperation;
	}

	public Byte getPreparegrade() {
		return this.preparegrade;
	}

	public void setPreparegrade(Byte preparegrade) {
		this.preparegrade = preparegrade;
	}

	public Boolean getNeedPhoto() {
		return this.needPhoto;
	}

	public void setNeedPhoto(Boolean needPhoto) {
		this.needPhoto = needPhoto;
	}

	public Clob getOperationSimpleContent() {
		return this.operationSimpleContent;
	}

	public void setOperationSimpleContent(Clob operationSimpleContent) {
		this.operationSimpleContent = operationSimpleContent;
	}

	public Clob getOperationContent() {
		return this.operationContent;
	}

	public void setOperationContent(Clob operationContent) {
		this.operationContent = operationContent;
	}

	public Long getIsStatisticCheck() {
		return this.isStatisticCheck;
	}

	public void setIsStatisticCheck(Long isStatisticCheck) {
		this.isStatisticCheck = isStatisticCheck;
	}

	public Boolean getKeycount() {
		return this.keycount;
	}

	public void setKeycount(Boolean keycount) {
		this.keycount = keycount;
	}

	public String getRoutingName() {
		return this.routingName;
	}

	public void setRoutingName(String routingName) {
		this.routingName = routingName;
	}

	public String getRVersionid() {
		return this.RVersionid;
	}

	public void setRVersionid(String RVersionid) {
		this.RVersionid = RVersionid;
	}

	public String getPartNumber() {
		return this.partNumber;
	}

	public void setPartNumber(String partNumber) {
		this.partNumber = partNumber;
	}

	public String getPartName() {
		return this.partName;
	}

	public void setPartName(String partName) {
		this.partName = partName;
	}

	public String getPVersionid() {
		return this.PVersionid;
	}

	public void setPVersionid(String PVersionid) {
		this.PVersionid = PVersionid;
	}

	public String getDrawingid() {
		return this.drawingid;
	}

	public void setDrawingid(String drawingid) {
		this.drawingid = drawingid;
	}

	public String getPartSort2() {
		return this.partSort2;
	}

	public void setPartSort2(String partSort2) {
		this.partSort2 = partSort2;
	}

	public String getPartNumberType() {
		return this.partNumberType;
	}

	public void setPartNumberType(String partNumberType) {
		this.partNumberType = partNumberType;
	}

	public String getClassname() {
		return this.classname;
	}

	public void setClassname(String classname) {
		this.classname = classname;
	}

	public String getBigmodelName() {
		return this.bigmodelName;
	}

	public void setBigmodelName(String bigmodelName) {
		this.bigmodelName = bigmodelName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BvOperId))
			return false;
		BvOperId castOther = (BvOperId) other;

		return ((this.getRouting() == castOther.getRouting()) || (this.getRouting() != null
				&& castOther.getRouting() != null && this.getRouting().equals(castOther.getRouting())))
				&& ((this.getOperationId() == castOther.getOperationId())
						|| (this.getOperationId() != null && castOther.getOperationId() != null
								&& this.getOperationId().equals(castOther.getOperationId())))
				&& ((this.getOpuid() == castOther.getOpuid()) || (this.getOpuid() != null
						&& castOther.getOpuid() != null && this.getOpuid().equals(castOther.getOpuid())))
				&& ((this.getOperationName() == castOther.getOperationName())
						|| (this.getOperationName() != null && castOther.getOperationName() != null
								&& this.getOperationName().equals(castOther.getOperationName())))
				&& ((this.getOperationGroup() == castOther.getOperationGroup())
						|| (this.getOperationGroup() != null && castOther.getOperationGroup() != null
								&& this.getOperationGroup().equals(castOther.getOperationGroup())))
				&& ((this.getPreopTime() == castOther.getPreopTime()) || (this.getPreopTime() != null
						&& castOther.getPreopTime() != null && this.getPreopTime().equals(castOther.getPreopTime())))
				&& ((this.getUnitRuntime() == castOther.getUnitRuntime())
						|| (this.getUnitRuntime() != null && castOther.getUnitRuntime() != null
								&& this.getUnitRuntime().equals(castOther.getUnitRuntime())))
				&& ((this.getPostopTime() == castOther.getPostopTime()) || (this.getPostopTime() != null
						&& castOther.getPostopTime() != null && this.getPostopTime().equals(castOther.getPostopTime())))
				&& ((this.getBaseMachineResource() == castOther.getBaseMachineResource())
						|| (this.getBaseMachineResource() != null && castOther.getBaseMachineResource() != null
								&& this.getBaseMachineResource().equals(castOther.getBaseMachineResource())))
				&& ((this.getMachineNumber() == castOther.getMachineNumber())
						|| (this.getMachineNumber() != null && castOther.getMachineNumber() != null
								&& this.getMachineNumber().equals(castOther.getMachineNumber())))
				&& ((this.getNumOperators() == castOther.getNumOperators())
						|| (this.getNumOperators() != null && castOther.getNumOperators() != null
								&& this.getNumOperators().equals(castOther.getNumOperators())))
				&& ((this.getParallel() == castOther.getParallel()) || (this.getParallel() != null
						&& castOther.getParallel() != null && this.getParallel().equals(castOther.getParallel())))
				&& ((this.getParallelThreshold() == castOther.getParallelThreshold())
						|| (this.getParallelThreshold() != null && castOther.getParallelThreshold() != null
								&& this.getParallelThreshold().equals(castOther.getParallelThreshold())))
				&& ((this.getMinimumParallelSubtask() == castOther.getMinimumParallelSubtask())
						|| (this.getMinimumParallelSubtask() != null && castOther.getMinimumParallelSubtask() != null
								&& this.getMinimumParallelSubtask().equals(castOther.getMinimumParallelSubtask())))
				&& ((this.getUseMprsIfNotLate() == castOther.getUseMprsIfNotLate())
						|| (this.getUseMprsIfNotLate() != null && castOther.getUseMprsIfNotLate() != null
								&& this.getUseMprsIfNotLate().equals(castOther.getUseMprsIfNotLate())))
				&& ((this.getMinOperationTime() == castOther.getMinOperationTime())
						|| (this.getMinOperationTime() != null && castOther.getMinOperationTime() != null
								&& this.getMinOperationTime().equals(castOther.getMinOperationTime())))
				&& ((this.getOpEstimatedQueneTime() == castOther.getOpEstimatedQueneTime())
						|| (this.getOpEstimatedQueneTime() != null && castOther.getOpEstimatedQueneTime() != null
								&& this.getOpEstimatedQueneTime().equals(castOther.getOpEstimatedQueneTime())))
				&& ((this.getOpMininumQueneTime() == castOther.getOpMininumQueneTime())
						|| (this.getOpMininumQueneTime() != null && castOther.getOpMininumQueneTime() != null
								&& this.getOpMininumQueneTime().equals(castOther.getOpMininumQueneTime())))
				&& ((this.getBaseYield() == castOther.getBaseYield()) || (this.getBaseYield() != null
						&& castOther.getBaseYield() != null && this.getBaseYield().equals(castOther.getBaseYield())))
				&& ((this.getInterruptible() == castOther.getInterruptible())
						|| (this.getInterruptible() != null && castOther.getInterruptible() != null
								&& this.getInterruptible().equals(castOther.getInterruptible())))
				&& ((this.getOperationType() == castOther.getOperationType())
						|| (this.getOperationType() != null && castOther.getOperationType() != null
								&& this.getOperationType().equals(castOther.getOperationType())))
				&& ((this.getPriority() == castOther.getPriority()) || (this.getPriority() != null
						&& castOther.getPriority() != null && this.getPriority().equals(castOther.getPriority())))
				&& ((this.getQueueCalendarName() == castOther.getQueueCalendarName())
						|| (this.getQueueCalendarName() != null && castOther.getQueueCalendarName() != null
								&& this.getQueueCalendarName().equals(castOther.getQueueCalendarName())))
				&& ((this.getRampupCalendarName() == castOther.getRampupCalendarName())
						|| (this.getRampupCalendarName() != null && castOther.getRampupCalendarName() != null
								&& this.getRampupCalendarName().equals(castOther.getRampupCalendarName())))
				&& ((this.getTransferBatchQuantity() == castOther.getTransferBatchQuantity())
						|| (this.getTransferBatchQuantity() != null && castOther.getTransferBatchQuantity() != null
								&& this.getTransferBatchQuantity().equals(castOther.getTransferBatchQuantity())))
				&& ((this.getIsCrossOperation() == castOther.getIsCrossOperation())
						|| (this.getIsCrossOperation() != null && castOther.getIsCrossOperation() != null
								&& this.getIsCrossOperation().equals(castOther.getIsCrossOperation())))
				&& ((this.getNeedCheck() == castOther.getNeedCheck()) || (this.getNeedCheck() != null
						&& castOther.getNeedCheck() != null && this.getNeedCheck().equals(castOther.getNeedCheck())))
				&& ((this.getIsCriticalOperation() == castOther.getIsCriticalOperation())
						|| (this.getIsCriticalOperation() != null && castOther.getIsCriticalOperation() != null
								&& this.getIsCriticalOperation().equals(castOther.getIsCriticalOperation())))
				&& ((this.getOperationSpecification() == castOther.getOperationSpecification())
						|| (this.getOperationSpecification() != null && castOther.getOperationSpecification() != null
								&& this.getOperationSpecification().equals(castOther.getOperationSpecification())))
				&& ((this.getMaterialCheckIn() == castOther.getMaterialCheckIn())
						|| (this.getMaterialCheckIn() != null && castOther.getMaterialCheckIn() != null
								&& this.getMaterialCheckIn().equals(castOther.getMaterialCheckIn())))
				&& ((this.getMaterialCheckOut() == castOther.getMaterialCheckOut())
						|| (this.getMaterialCheckOut() != null && castOther.getMaterialCheckOut() != null
								&& this.getMaterialCheckOut().equals(castOther.getMaterialCheckOut())))
				&& ((this.getOperationCostSum() == castOther.getOperationCostSum())
						|| (this.getOperationCostSum() != null && castOther.getOperationCostSum() != null
								&& this.getOperationCostSum().equals(castOther.getOperationCostSum())))
				&& ((this.getLaborCost() == castOther.getLaborCost()) || (this.getLaborCost() != null
						&& castOther.getLaborCost() != null && this.getLaborCost().equals(castOther.getLaborCost())))
				&& ((this.getMachineCost() == castOther.getMachineCost())
						|| (this.getMachineCost() != null && castOther.getMachineCost() != null
								&& this.getMachineCost().equals(castOther.getMachineCost())))
				&& ((this.getLinkDownstreamP() == castOther.getLinkDownstreamP())
						|| (this.getLinkDownstreamP() != null && castOther.getLinkDownstreamP() != null
								&& this.getLinkDownstreamP().equals(castOther.getLinkDownstreamP())))
				&& ((this.getLinkDownstreamMinWip() == castOther.getLinkDownstreamMinWip())
						|| (this.getLinkDownstreamMinWip() != null && castOther.getLinkDownstreamMinWip() != null
								&& this.getLinkDownstreamMinWip().equals(castOther.getLinkDownstreamMinWip())))
				&& ((this.getLinkDownstreamMaxWip() == castOther.getLinkDownstreamMaxWip())
						|| (this.getLinkDownstreamMaxWip() != null && castOther.getLinkDownstreamMaxWip() != null
								&& this.getLinkDownstreamMaxWip().equals(castOther.getLinkDownstreamMaxWip())))
				&& ((this.getUnitRuntimeCostPer() == castOther.getUnitRuntimeCostPer())
						|| (this.getUnitRuntimeCostPer() != null && castOther.getUnitRuntimeCostPer() != null
								&& this.getUnitRuntimeCostPer().equals(castOther.getUnitRuntimeCostPer())))
				&& ((this.getUnitRuntimeCostPerTime() == castOther.getUnitRuntimeCostPerTime())
						|| (this.getUnitRuntimeCostPerTime() != null && castOther.getUnitRuntimeCostPerTime() != null
								&& this.getUnitRuntimeCostPerTime().equals(castOther.getUnitRuntimeCostPerTime())))
				&& ((this.getUnitWipCarryCostPer() == castOther.getUnitWipCarryCostPer())
						|| (this.getUnitWipCarryCostPer() != null && castOther.getUnitWipCarryCostPer() != null
								&& this.getUnitWipCarryCostPer().equals(castOther.getUnitWipCarryCostPer())))
				&& ((this.getUnitWipCarryCostPerTime() == castOther.getUnitWipCarryCostPerTime())
						|| (this.getUnitWipCarryCostPerTime() != null && castOther.getUnitWipCarryCostPerTime() != null
								&& this.getUnitWipCarryCostPerTime().equals(castOther.getUnitWipCarryCostPerTime())))
				&& ((this.getSequenceDependentSetupType() == castOther.getSequenceDependentSetupType())
						|| (this.getSequenceDependentSetupType() != null
								&& castOther.getSequenceDependentSetupType() != null
								&& this.getSequenceDependentSetupType()
										.equals(castOther.getSequenceDependentSetupType())))
				&& ((this.getSequenceDependentSetupType2() == castOther.getSequenceDependentSetupType2())
						|| (this.getSequenceDependentSetupType2() != null
								&& castOther.getSequenceDependentSetupType2() != null
								&& this.getSequenceDependentSetupType2()
										.equals(castOther.getSequenceDependentSetupType2())))
				&& ((this.getSequenceDependentSetupType3() == castOther.getSequenceDependentSetupType3())
						|| (this.getSequenceDependentSetupType3() != null
								&& castOther.getSequenceDependentSetupType3() != null
								&& this.getSequenceDependentSetupType3()
										.equals(castOther.getSequenceDependentSetupType3())))
				&& ((this.getNote() == castOther.getNote()) || (this.getNote() != null && castOther.getNote() != null
						&& this.getNote().equals(castOther.getNote())))
				&& ((this.getRoutingType() == castOther.getRoutingType())
						|| (this.getRoutingType() != null && castOther.getRoutingType() != null
								&& this.getRoutingType().equals(castOther.getRoutingType())))
				&& ((this.getOperationNote() == castOther.getOperationNote())
						|| (this.getOperationNote() != null && castOther.getOperationNote() != null
								&& this.getOperationNote().equals(castOther.getOperationNote())))
				&& ((this.getWorkcoefficient() == castOther.getWorkcoefficient())
						|| (this.getWorkcoefficient() != null && castOther.getWorkcoefficient() != null
								&& this.getWorkcoefficient().equals(castOther.getWorkcoefficient())))
				&& ((this.getChangetime() == castOther.getChangetime()) || (this.getChangetime() != null
						&& castOther.getChangetime() != null && this.getChangetime().equals(castOther.getChangetime())))
				&& ((this.getChanger() == castOther.getChanger()) || (this.getChanger() != null
						&& castOther.getChanger() != null && this.getChanger().equals(castOther.getChanger())))
				&& ((this.getChangereason() == castOther.getChangereason())
						|| (this.getChangereason() != null && castOther.getChangereason() != null
								&& this.getChangereason().equals(castOther.getChangereason())))
				&& ((this.getChangestate() == castOther.getChangestate())
						|| (this.getChangestate() != null && castOther.getChangestate() != null
								&& this.getChangestate().equals(castOther.getChangestate())))
				&& ((this.getEffective() == castOther.getEffective()) || (this.getEffective() != null
						&& castOther.getEffective() != null && this.getEffective().equals(castOther.getEffective())))
				&& ((this.getCreator() == castOther.getCreator()) || (this.getCreator() != null
						&& castOther.getCreator() != null && this.getCreator().equals(castOther.getCreator())))
				&& ((this.getCreatetime() == castOther.getCreatetime()) || (this.getCreatetime() != null
						&& castOther.getCreatetime() != null && this.getCreatetime().equals(castOther.getCreatetime())))
				&& ((this.getUniqueid() == castOther.getUniqueid()) || (this.getUniqueid() != null
						&& castOther.getUniqueid() != null && this.getUniqueid().equals(castOther.getUniqueid())))
				&& ((this.getDispatchgrade() == castOther.getDispatchgrade())
						|| (this.getDispatchgrade() != null && castOther.getDispatchgrade() != null
								&& this.getDispatchgrade().equals(castOther.getDispatchgrade())))
				&& ((this.getSampleqty() == castOther.getSampleqty()) || (this.getSampleqty() != null
						&& castOther.getSampleqty() != null && this.getSampleqty().equals(castOther.getSampleqty())))
				&& ((this.getSamplepercent() == castOther.getSamplepercent())
						|| (this.getSamplepercent() != null && castOther.getSamplepercent() != null
								&& this.getSamplepercent().equals(castOther.getSamplepercent())))
				&& ((this.getOperationIddesc() == castOther.getOperationIddesc())
						|| (this.getOperationIddesc() != null && castOther.getOperationIddesc() != null
								&& this.getOperationIddesc().equals(castOther.getOperationIddesc())))
				&& ((this.getEstipretime() == castOther.getEstipretime())
						|| (this.getEstipretime() != null && castOther.getEstipretime() != null
								&& this.getEstipretime().equals(castOther.getEstipretime())))
				&& ((this.getEstiruntime() == castOther.getEstiruntime())
						|| (this.getEstiruntime() != null && castOther.getEstiruntime() != null
								&& this.getEstiruntime().equals(castOther.getEstiruntime())))
				&& ((this.getSampleOpid() == castOther.getSampleOpid()) || (this.getSampleOpid() != null
						&& castOther.getSampleOpid() != null && this.getSampleOpid().equals(castOther.getSampleOpid())))
				&& ((this.getNeedSample() == castOther.getNeedSample()) || (this.getNeedSample() != null
						&& castOther.getNeedSample() != null && this.getNeedSample().equals(castOther.getNeedSample())))
				&& ((this.getCheckstate() == castOther.getCheckstate()) || (this.getCheckstate() != null
						&& castOther.getCheckstate() != null && this.getCheckstate().equals(castOther.getCheckstate())))
				&& ((this.getGroupuid() == castOther.getGroupuid()) || (this.getGroupuid() != null
						&& castOther.getGroupuid() != null && this.getGroupuid().equals(castOther.getGroupuid())))
				&& ((this.getOpid() == castOther.getOpid()) || (this.getOpid() != null && castOther.getOpid() != null
						&& this.getOpid().equals(castOther.getOpid())))
				&& ((this.getOptype() == castOther.getOptype()) || (this.getOptype() != null
						&& castOther.getOptype() != null && this.getOptype().equals(castOther.getOptype())))
				&& ((this.getVersionid() == castOther.getVersionid()) || (this.getVersionid() != null
						&& castOther.getVersionid() != null && this.getVersionid().equals(castOther.getVersionid())))
				&& ((this.getRoutingNote() == castOther.getRoutingNote())
						|| (this.getRoutingNote() != null && castOther.getRoutingNote() != null
								&& this.getRoutingNote().equals(castOther.getRoutingNote())))
				&& ((this.getSampleRuntime() == castOther.getSampleRuntime())
						|| (this.getSampleRuntime() != null && castOther.getSampleRuntime() != null
								&& this.getSampleRuntime().equals(castOther.getSampleRuntime())))
				&& ((this.getNeedFirstcheck() == castOther.getNeedFirstcheck())
						|| (this.getNeedFirstcheck() != null && castOther.getNeedFirstcheck() != null
								&& this.getNeedFirstcheck().equals(castOther.getNeedFirstcheck())))
				&& ((this.getCheckpercent() == castOther.getCheckpercent())
						|| (this.getCheckpercent() != null && castOther.getCheckpercent() != null
								&& this.getCheckpercent().equals(castOther.getCheckpercent())))
				&& ((this.getRefrouting() == castOther.getRefrouting()) || (this.getRefrouting() != null
						&& castOther.getRefrouting() != null && this.getRefrouting().equals(castOther.getRefrouting())))
				&& ((this.getBRoutineOutUid() == castOther.getBRoutineOutUid())
						|| (this.getBRoutineOutUid() != null && castOther.getBRoutineOutUid() != null
								&& this.getBRoutineOutUid().equals(castOther.getBRoutineOutUid())))
				&& ((this.getDeptid() == castOther.getDeptid()) || (this.getDeptid() != null
						&& castOther.getDeptid() != null && this.getDeptid().equals(castOther.getDeptid())))
				&& ((this.getDeviceuid() == castOther.getDeviceuid()) || (this.getDeviceuid() != null
						&& castOther.getDeviceuid() != null && this.getDeviceuid().equals(castOther.getDeviceuid())))
				&& ((this.getOperationContentTt() == castOther.getOperationContentTt())
						|| (this.getOperationContentTt() != null && castOther.getOperationContentTt() != null
								&& this.getOperationContentTt().equals(castOther.getOperationContentTt())))
				&& ((this.getParentopuid() == castOther.getParentopuid())
						|| (this.getParentopuid() != null && castOther.getParentopuid() != null
								&& this.getParentopuid().equals(castOther.getParentopuid())))
				&& ((this.getNcNumber() == castOther.getNcNumber()) || (this.getNcNumber() != null
						&& castOther.getNcNumber() != null && this.getNcNumber().equals(castOther.getNcNumber())))
				&& ((this.getNcVersionid() == castOther.getNcVersionid())
						|| (this.getNcVersionid() != null && castOther.getNcVersionid() != null
								&& this.getNcVersionid().equals(castOther.getNcVersionid())))
				&& ((this.getIsSpecialOperation() == castOther.getIsSpecialOperation())
						|| (this.getIsSpecialOperation() != null && castOther.getIsSpecialOperation() != null
								&& this.getIsSpecialOperation().equals(castOther.getIsSpecialOperation())))
				&& ((this.getPreparegrade() == castOther.getPreparegrade())
						|| (this.getPreparegrade() != null && castOther.getPreparegrade() != null
								&& this.getPreparegrade().equals(castOther.getPreparegrade())))
				&& ((this.getNeedPhoto() == castOther.getNeedPhoto()) || (this.getNeedPhoto() != null
						&& castOther.getNeedPhoto() != null && this.getNeedPhoto().equals(castOther.getNeedPhoto())))
				&& ((this.getOperationSimpleContent() == castOther.getOperationSimpleContent())
						|| (this.getOperationSimpleContent() != null && castOther.getOperationSimpleContent() != null
								&& this.getOperationSimpleContent().equals(castOther.getOperationSimpleContent())))
				&& ((this.getOperationContent() == castOther.getOperationContent())
						|| (this.getOperationContent() != null && castOther.getOperationContent() != null
								&& this.getOperationContent().equals(castOther.getOperationContent())))
				&& ((this.getIsStatisticCheck() == castOther.getIsStatisticCheck())
						|| (this.getIsStatisticCheck() != null && castOther.getIsStatisticCheck() != null
								&& this.getIsStatisticCheck().equals(castOther.getIsStatisticCheck())))
				&& ((this.getKeycount() == castOther.getKeycount()) || (this.getKeycount() != null
						&& castOther.getKeycount() != null && this.getKeycount().equals(castOther.getKeycount())))
				&& ((this.getRoutingName() == castOther.getRoutingName())
						|| (this.getRoutingName() != null && castOther.getRoutingName() != null
								&& this.getRoutingName().equals(castOther.getRoutingName())))
				&& ((this.getRVersionid() == castOther.getRVersionid()) || (this.getRVersionid() != null
						&& castOther.getRVersionid() != null && this.getRVersionid().equals(castOther.getRVersionid())))
				&& ((this.getPartNumber() == castOther.getPartNumber()) || (this.getPartNumber() != null
						&& castOther.getPartNumber() != null && this.getPartNumber().equals(castOther.getPartNumber())))
				&& ((this.getPartName() == castOther.getPartName()) || (this.getPartName() != null
						&& castOther.getPartName() != null && this.getPartName().equals(castOther.getPartName())))
				&& ((this.getPVersionid() == castOther.getPVersionid()) || (this.getPVersionid() != null
						&& castOther.getPVersionid() != null && this.getPVersionid().equals(castOther.getPVersionid())))
				&& ((this.getDrawingid() == castOther.getDrawingid()) || (this.getDrawingid() != null
						&& castOther.getDrawingid() != null && this.getDrawingid().equals(castOther.getDrawingid())))
				&& ((this.getPartSort2() == castOther.getPartSort2()) || (this.getPartSort2() != null
						&& castOther.getPartSort2() != null && this.getPartSort2().equals(castOther.getPartSort2())))
				&& ((this.getPartNumberType() == castOther.getPartNumberType())
						|| (this.getPartNumberType() != null && castOther.getPartNumberType() != null
								&& this.getPartNumberType().equals(castOther.getPartNumberType())))
				&& ((this.getClassname() == castOther.getClassname()) || (this.getClassname() != null
						&& castOther.getClassname() != null && this.getClassname().equals(castOther.getClassname())))
				&& ((this.getBigmodelName() == castOther.getBigmodelName())
						|| (this.getBigmodelName() != null && castOther.getBigmodelName() != null
								&& this.getBigmodelName().equals(castOther.getBigmodelName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRouting() == null ? 0 : this.getRouting().hashCode());
		result = 37 * result + (getOperationId() == null ? 0 : this.getOperationId().hashCode());
		result = 37 * result + (getOpuid() == null ? 0 : this.getOpuid().hashCode());
		result = 37 * result + (getOperationName() == null ? 0 : this.getOperationName().hashCode());
		result = 37 * result + (getOperationGroup() == null ? 0 : this.getOperationGroup().hashCode());
		result = 37 * result + (getPreopTime() == null ? 0 : this.getPreopTime().hashCode());
		result = 37 * result + (getUnitRuntime() == null ? 0 : this.getUnitRuntime().hashCode());
		result = 37 * result + (getPostopTime() == null ? 0 : this.getPostopTime().hashCode());
		result = 37 * result + (getBaseMachineResource() == null ? 0 : this.getBaseMachineResource().hashCode());
		result = 37 * result + (getMachineNumber() == null ? 0 : this.getMachineNumber().hashCode());
		result = 37 * result + (getNumOperators() == null ? 0 : this.getNumOperators().hashCode());
		result = 37 * result + (getParallel() == null ? 0 : this.getParallel().hashCode());
		result = 37 * result + (getParallelThreshold() == null ? 0 : this.getParallelThreshold().hashCode());
		result = 37 * result + (getMinimumParallelSubtask() == null ? 0 : this.getMinimumParallelSubtask().hashCode());
		result = 37 * result + (getUseMprsIfNotLate() == null ? 0 : this.getUseMprsIfNotLate().hashCode());
		result = 37 * result + (getMinOperationTime() == null ? 0 : this.getMinOperationTime().hashCode());
		result = 37 * result + (getOpEstimatedQueneTime() == null ? 0 : this.getOpEstimatedQueneTime().hashCode());
		result = 37 * result + (getOpMininumQueneTime() == null ? 0 : this.getOpMininumQueneTime().hashCode());
		result = 37 * result + (getBaseYield() == null ? 0 : this.getBaseYield().hashCode());
		result = 37 * result + (getInterruptible() == null ? 0 : this.getInterruptible().hashCode());
		result = 37 * result + (getOperationType() == null ? 0 : this.getOperationType().hashCode());
		result = 37 * result + (getPriority() == null ? 0 : this.getPriority().hashCode());
		result = 37 * result + (getQueueCalendarName() == null ? 0 : this.getQueueCalendarName().hashCode());
		result = 37 * result + (getRampupCalendarName() == null ? 0 : this.getRampupCalendarName().hashCode());
		result = 37 * result + (getTransferBatchQuantity() == null ? 0 : this.getTransferBatchQuantity().hashCode());
		result = 37 * result + (getIsCrossOperation() == null ? 0 : this.getIsCrossOperation().hashCode());
		result = 37 * result + (getNeedCheck() == null ? 0 : this.getNeedCheck().hashCode());
		result = 37 * result + (getIsCriticalOperation() == null ? 0 : this.getIsCriticalOperation().hashCode());
		result = 37 * result + (getOperationSpecification() == null ? 0 : this.getOperationSpecification().hashCode());
		result = 37 * result + (getMaterialCheckIn() == null ? 0 : this.getMaterialCheckIn().hashCode());
		result = 37 * result + (getMaterialCheckOut() == null ? 0 : this.getMaterialCheckOut().hashCode());
		result = 37 * result + (getOperationCostSum() == null ? 0 : this.getOperationCostSum().hashCode());
		result = 37 * result + (getLaborCost() == null ? 0 : this.getLaborCost().hashCode());
		result = 37 * result + (getMachineCost() == null ? 0 : this.getMachineCost().hashCode());
		result = 37 * result + (getLinkDownstreamP() == null ? 0 : this.getLinkDownstreamP().hashCode());
		result = 37 * result + (getLinkDownstreamMinWip() == null ? 0 : this.getLinkDownstreamMinWip().hashCode());
		result = 37 * result + (getLinkDownstreamMaxWip() == null ? 0 : this.getLinkDownstreamMaxWip().hashCode());
		result = 37 * result + (getUnitRuntimeCostPer() == null ? 0 : this.getUnitRuntimeCostPer().hashCode());
		result = 37 * result + (getUnitRuntimeCostPerTime() == null ? 0 : this.getUnitRuntimeCostPerTime().hashCode());
		result = 37 * result + (getUnitWipCarryCostPer() == null ? 0 : this.getUnitWipCarryCostPer().hashCode());
		result = 37 * result
				+ (getUnitWipCarryCostPerTime() == null ? 0 : this.getUnitWipCarryCostPerTime().hashCode());
		result = 37 * result
				+ (getSequenceDependentSetupType() == null ? 0 : this.getSequenceDependentSetupType().hashCode());
		result = 37 * result
				+ (getSequenceDependentSetupType2() == null ? 0 : this.getSequenceDependentSetupType2().hashCode());
		result = 37 * result
				+ (getSequenceDependentSetupType3() == null ? 0 : this.getSequenceDependentSetupType3().hashCode());
		result = 37 * result + (getNote() == null ? 0 : this.getNote().hashCode());
		result = 37 * result + (getRoutingType() == null ? 0 : this.getRoutingType().hashCode());
		result = 37 * result + (getOperationNote() == null ? 0 : this.getOperationNote().hashCode());
		result = 37 * result + (getWorkcoefficient() == null ? 0 : this.getWorkcoefficient().hashCode());
		result = 37 * result + (getChangetime() == null ? 0 : this.getChangetime().hashCode());
		result = 37 * result + (getChanger() == null ? 0 : this.getChanger().hashCode());
		result = 37 * result + (getChangereason() == null ? 0 : this.getChangereason().hashCode());
		result = 37 * result + (getChangestate() == null ? 0 : this.getChangestate().hashCode());
		result = 37 * result + (getEffective() == null ? 0 : this.getEffective().hashCode());
		result = 37 * result + (getCreator() == null ? 0 : this.getCreator().hashCode());
		result = 37 * result + (getCreatetime() == null ? 0 : this.getCreatetime().hashCode());
		result = 37 * result + (getUniqueid() == null ? 0 : this.getUniqueid().hashCode());
		result = 37 * result + (getDispatchgrade() == null ? 0 : this.getDispatchgrade().hashCode());
		result = 37 * result + (getSampleqty() == null ? 0 : this.getSampleqty().hashCode());
		result = 37 * result + (getSamplepercent() == null ? 0 : this.getSamplepercent().hashCode());
		result = 37 * result + (getOperationIddesc() == null ? 0 : this.getOperationIddesc().hashCode());
		result = 37 * result + (getEstipretime() == null ? 0 : this.getEstipretime().hashCode());
		result = 37 * result + (getEstiruntime() == null ? 0 : this.getEstiruntime().hashCode());
		result = 37 * result + (getSampleOpid() == null ? 0 : this.getSampleOpid().hashCode());
		result = 37 * result + (getNeedSample() == null ? 0 : this.getNeedSample().hashCode());
		result = 37 * result + (getCheckstate() == null ? 0 : this.getCheckstate().hashCode());
		result = 37 * result + (getGroupuid() == null ? 0 : this.getGroupuid().hashCode());
		result = 37 * result + (getOpid() == null ? 0 : this.getOpid().hashCode());
		result = 37 * result + (getOptype() == null ? 0 : this.getOptype().hashCode());
		result = 37 * result + (getVersionid() == null ? 0 : this.getVersionid().hashCode());
		result = 37 * result + (getRoutingNote() == null ? 0 : this.getRoutingNote().hashCode());
		result = 37 * result + (getSampleRuntime() == null ? 0 : this.getSampleRuntime().hashCode());
		result = 37 * result + (getNeedFirstcheck() == null ? 0 : this.getNeedFirstcheck().hashCode());
		result = 37 * result + (getCheckpercent() == null ? 0 : this.getCheckpercent().hashCode());
		result = 37 * result + (getRefrouting() == null ? 0 : this.getRefrouting().hashCode());
		result = 37 * result + (getBRoutineOutUid() == null ? 0 : this.getBRoutineOutUid().hashCode());
		result = 37 * result + (getDeptid() == null ? 0 : this.getDeptid().hashCode());
		result = 37 * result + (getDeviceuid() == null ? 0 : this.getDeviceuid().hashCode());
		result = 37 * result + (getOperationContentTt() == null ? 0 : this.getOperationContentTt().hashCode());
		result = 37 * result + (getParentopuid() == null ? 0 : this.getParentopuid().hashCode());
		result = 37 * result + (getNcNumber() == null ? 0 : this.getNcNumber().hashCode());
		result = 37 * result + (getNcVersionid() == null ? 0 : this.getNcVersionid().hashCode());
		result = 37 * result + (getIsSpecialOperation() == null ? 0 : this.getIsSpecialOperation().hashCode());
		result = 37 * result + (getPreparegrade() == null ? 0 : this.getPreparegrade().hashCode());
		result = 37 * result + (getNeedPhoto() == null ? 0 : this.getNeedPhoto().hashCode());
		result = 37 * result + (getOperationSimpleContent() == null ? 0 : this.getOperationSimpleContent().hashCode());
		result = 37 * result + (getOperationContent() == null ? 0 : this.getOperationContent().hashCode());
		result = 37 * result + (getIsStatisticCheck() == null ? 0 : this.getIsStatisticCheck().hashCode());
		result = 37 * result + (getKeycount() == null ? 0 : this.getKeycount().hashCode());
		result = 37 * result + (getRoutingName() == null ? 0 : this.getRoutingName().hashCode());
		result = 37 * result + (getRVersionid() == null ? 0 : this.getRVersionid().hashCode());
		result = 37 * result + (getPartNumber() == null ? 0 : this.getPartNumber().hashCode());
		result = 37 * result + (getPartName() == null ? 0 : this.getPartName().hashCode());
		result = 37 * result + (getPVersionid() == null ? 0 : this.getPVersionid().hashCode());
		result = 37 * result + (getDrawingid() == null ? 0 : this.getDrawingid().hashCode());
		result = 37 * result + (getPartSort2() == null ? 0 : this.getPartSort2().hashCode());
		result = 37 * result + (getPartNumberType() == null ? 0 : this.getPartNumberType().hashCode());
		result = 37 * result + (getClassname() == null ? 0 : this.getClassname().hashCode());
		result = 37 * result + (getBigmodelName() == null ? 0 : this.getBigmodelName().hashCode());
		return result;
	}

}
