package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;

/**
 * BvPrepareRoutineId generated by hbm2java
 */
public class BvPrepareRoutineId implements java.io.Serializable {

	private String routing;
	private String routingName;
	private String routingType;
	private BigDecimal opuid;
	private BigDecimal operationId;
	private String requirePartNumber;
	private Byte requireNum;
	private String partName;
	private String drawingid;
	private String versionid;
	private String partNumberSort;
	private String partNumberSortIddesc;
	private String isNeedJudge;
	private Long judgeAdvanceTime;
	private String isNeedData;
	private Long dataAdvanceTime;
	private String isNeedSort;
	private Long sortAdvanceTime;

	public BvPrepareRoutineId() {
	}

	public BvPrepareRoutineId(String routing, BigDecimal opuid, BigDecimal operationId, String requirePartNumber,
			String partNumberSortIddesc) {
		this.routing = routing;
		this.opuid = opuid;
		this.operationId = operationId;
		this.requirePartNumber = requirePartNumber;
		this.partNumberSortIddesc = partNumberSortIddesc;
	}

	public BvPrepareRoutineId(String routing, String routingName, String routingType, BigDecimal opuid,
			BigDecimal operationId, String requirePartNumber, Byte requireNum, String partName, String drawingid,
			String versionid, String partNumberSort, String partNumberSortIddesc, String isNeedJudge,
			Long judgeAdvanceTime, String isNeedData, Long dataAdvanceTime, String isNeedSort, Long sortAdvanceTime) {
		this.routing = routing;
		this.routingName = routingName;
		this.routingType = routingType;
		this.opuid = opuid;
		this.operationId = operationId;
		this.requirePartNumber = requirePartNumber;
		this.requireNum = requireNum;
		this.partName = partName;
		this.drawingid = drawingid;
		this.versionid = versionid;
		this.partNumberSort = partNumberSort;
		this.partNumberSortIddesc = partNumberSortIddesc;
		this.isNeedJudge = isNeedJudge;
		this.judgeAdvanceTime = judgeAdvanceTime;
		this.isNeedData = isNeedData;
		this.dataAdvanceTime = dataAdvanceTime;
		this.isNeedSort = isNeedSort;
		this.sortAdvanceTime = sortAdvanceTime;
	}

	public String getRouting() {
		return this.routing;
	}

	public void setRouting(String routing) {
		this.routing = routing;
	}

	public String getRoutingName() {
		return this.routingName;
	}

	public void setRoutingName(String routingName) {
		this.routingName = routingName;
	}

	public String getRoutingType() {
		return this.routingType;
	}

	public void setRoutingType(String routingType) {
		this.routingType = routingType;
	}

	public BigDecimal getOpuid() {
		return this.opuid;
	}

	public void setOpuid(BigDecimal opuid) {
		this.opuid = opuid;
	}

	public BigDecimal getOperationId() {
		return this.operationId;
	}

	public void setOperationId(BigDecimal operationId) {
		this.operationId = operationId;
	}

	public String getRequirePartNumber() {
		return this.requirePartNumber;
	}

	public void setRequirePartNumber(String requirePartNumber) {
		this.requirePartNumber = requirePartNumber;
	}

	public Byte getRequireNum() {
		return this.requireNum;
	}

	public void setRequireNum(Byte requireNum) {
		this.requireNum = requireNum;
	}

	public String getPartName() {
		return this.partName;
	}

	public void setPartName(String partName) {
		this.partName = partName;
	}

	public String getDrawingid() {
		return this.drawingid;
	}

	public void setDrawingid(String drawingid) {
		this.drawingid = drawingid;
	}

	public String getVersionid() {
		return this.versionid;
	}

	public void setVersionid(String versionid) {
		this.versionid = versionid;
	}

	public String getPartNumberSort() {
		return this.partNumberSort;
	}

	public void setPartNumberSort(String partNumberSort) {
		this.partNumberSort = partNumberSort;
	}

	public String getPartNumberSortIddesc() {
		return this.partNumberSortIddesc;
	}

	public void setPartNumberSortIddesc(String partNumberSortIddesc) {
		this.partNumberSortIddesc = partNumberSortIddesc;
	}

	public String getIsNeedJudge() {
		return this.isNeedJudge;
	}

	public void setIsNeedJudge(String isNeedJudge) {
		this.isNeedJudge = isNeedJudge;
	}

	public Long getJudgeAdvanceTime() {
		return this.judgeAdvanceTime;
	}

	public void setJudgeAdvanceTime(Long judgeAdvanceTime) {
		this.judgeAdvanceTime = judgeAdvanceTime;
	}

	public String getIsNeedData() {
		return this.isNeedData;
	}

	public void setIsNeedData(String isNeedData) {
		this.isNeedData = isNeedData;
	}

	public Long getDataAdvanceTime() {
		return this.dataAdvanceTime;
	}

	public void setDataAdvanceTime(Long dataAdvanceTime) {
		this.dataAdvanceTime = dataAdvanceTime;
	}

	public String getIsNeedSort() {
		return this.isNeedSort;
	}

	public void setIsNeedSort(String isNeedSort) {
		this.isNeedSort = isNeedSort;
	}

	public Long getSortAdvanceTime() {
		return this.sortAdvanceTime;
	}

	public void setSortAdvanceTime(Long sortAdvanceTime) {
		this.sortAdvanceTime = sortAdvanceTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BvPrepareRoutineId))
			return false;
		BvPrepareRoutineId castOther = (BvPrepareRoutineId) other;

		return ((this.getRouting() == castOther.getRouting()) || (this.getRouting() != null
				&& castOther.getRouting() != null && this.getRouting().equals(castOther.getRouting())))
				&& ((this.getRoutingName() == castOther.getRoutingName())
						|| (this.getRoutingName() != null && castOther.getRoutingName() != null
								&& this.getRoutingName().equals(castOther.getRoutingName())))
				&& ((this.getRoutingType() == castOther.getRoutingType())
						|| (this.getRoutingType() != null && castOther.getRoutingType() != null
								&& this.getRoutingType().equals(castOther.getRoutingType())))
				&& ((this.getOpuid() == castOther.getOpuid()) || (this.getOpuid() != null
						&& castOther.getOpuid() != null && this.getOpuid().equals(castOther.getOpuid())))
				&& ((this.getOperationId() == castOther.getOperationId())
						|| (this.getOperationId() != null && castOther.getOperationId() != null
								&& this.getOperationId().equals(castOther.getOperationId())))
				&& ((this.getRequirePartNumber() == castOther.getRequirePartNumber())
						|| (this.getRequirePartNumber() != null && castOther.getRequirePartNumber() != null
								&& this.getRequirePartNumber().equals(castOther.getRequirePartNumber())))
				&& ((this.getRequireNum() == castOther.getRequireNum()) || (this.getRequireNum() != null
						&& castOther.getRequireNum() != null && this.getRequireNum().equals(castOther.getRequireNum())))
				&& ((this.getPartName() == castOther.getPartName()) || (this.getPartName() != null
						&& castOther.getPartName() != null && this.getPartName().equals(castOther.getPartName())))
				&& ((this.getDrawingid() == castOther.getDrawingid()) || (this.getDrawingid() != null
						&& castOther.getDrawingid() != null && this.getDrawingid().equals(castOther.getDrawingid())))
				&& ((this.getVersionid() == castOther.getVersionid()) || (this.getVersionid() != null
						&& castOther.getVersionid() != null && this.getVersionid().equals(castOther.getVersionid())))
				&& ((this.getPartNumberSort() == castOther.getPartNumberSort())
						|| (this.getPartNumberSort() != null && castOther.getPartNumberSort() != null
								&& this.getPartNumberSort().equals(castOther.getPartNumberSort())))
				&& ((this.getPartNumberSortIddesc() == castOther.getPartNumberSortIddesc())
						|| (this.getPartNumberSortIddesc() != null && castOther.getPartNumberSortIddesc() != null
								&& this.getPartNumberSortIddesc().equals(castOther.getPartNumberSortIddesc())))
				&& ((this.getIsNeedJudge() == castOther.getIsNeedJudge())
						|| (this.getIsNeedJudge() != null && castOther.getIsNeedJudge() != null
								&& this.getIsNeedJudge().equals(castOther.getIsNeedJudge())))
				&& ((this.getJudgeAdvanceTime() == castOther.getJudgeAdvanceTime())
						|| (this.getJudgeAdvanceTime() != null && castOther.getJudgeAdvanceTime() != null
								&& this.getJudgeAdvanceTime().equals(castOther.getJudgeAdvanceTime())))
				&& ((this.getIsNeedData() == castOther.getIsNeedData()) || (this.getIsNeedData() != null
						&& castOther.getIsNeedData() != null && this.getIsNeedData().equals(castOther.getIsNeedData())))
				&& ((this.getDataAdvanceTime() == castOther.getDataAdvanceTime())
						|| (this.getDataAdvanceTime() != null && castOther.getDataAdvanceTime() != null
								&& this.getDataAdvanceTime().equals(castOther.getDataAdvanceTime())))
				&& ((this.getIsNeedSort() == castOther.getIsNeedSort()) || (this.getIsNeedSort() != null
						&& castOther.getIsNeedSort() != null && this.getIsNeedSort().equals(castOther.getIsNeedSort())))
				&& ((this.getSortAdvanceTime() == castOther.getSortAdvanceTime())
						|| (this.getSortAdvanceTime() != null && castOther.getSortAdvanceTime() != null
								&& this.getSortAdvanceTime().equals(castOther.getSortAdvanceTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRouting() == null ? 0 : this.getRouting().hashCode());
		result = 37 * result + (getRoutingName() == null ? 0 : this.getRoutingName().hashCode());
		result = 37 * result + (getRoutingType() == null ? 0 : this.getRoutingType().hashCode());
		result = 37 * result + (getOpuid() == null ? 0 : this.getOpuid().hashCode());
		result = 37 * result + (getOperationId() == null ? 0 : this.getOperationId().hashCode());
		result = 37 * result + (getRequirePartNumber() == null ? 0 : this.getRequirePartNumber().hashCode());
		result = 37 * result + (getRequireNum() == null ? 0 : this.getRequireNum().hashCode());
		result = 37 * result + (getPartName() == null ? 0 : this.getPartName().hashCode());
		result = 37 * result + (getDrawingid() == null ? 0 : this.getDrawingid().hashCode());
		result = 37 * result + (getVersionid() == null ? 0 : this.getVersionid().hashCode());
		result = 37 * result + (getPartNumberSort() == null ? 0 : this.getPartNumberSort().hashCode());
		result = 37 * result + (getPartNumberSortIddesc() == null ? 0 : this.getPartNumberSortIddesc().hashCode());
		result = 37 * result + (getIsNeedJudge() == null ? 0 : this.getIsNeedJudge().hashCode());
		result = 37 * result + (getJudgeAdvanceTime() == null ? 0 : this.getJudgeAdvanceTime().hashCode());
		result = 37 * result + (getIsNeedData() == null ? 0 : this.getIsNeedData().hashCode());
		result = 37 * result + (getDataAdvanceTime() == null ? 0 : this.getDataAdvanceTime().hashCode());
		result = 37 * result + (getIsNeedSort() == null ? 0 : this.getIsNeedSort().hashCode());
		result = 37 * result + (getSortAdvanceTime() == null ? 0 : this.getSortAdvanceTime().hashCode());
		return result;
	}

}
