package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

/**
 * BvPrepareRoutine generated by hbm2java
 */
public class BvPrepareRoutine implements java.io.Serializable {

	private BvPrepareRoutineId id;

	public BvPrepareRoutine() {
	}

	public BvPrepareRoutine(BvPrepareRoutineId id) {
		this.id = id;
	}

	public BvPrepareRoutineId getId() {
		return this.id;
	}

	public void setId(BvPrepareRoutineId id) {
		this.id = id;
	}

}
