package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

/**
 * BXbomHeader generated by hbm2java
 */
public class BXbomHeader implements java.io.Serializable {

	private BXbomHeaderId id;

	public BXbomHeader() {
	}

	public BXbomHeader(BXbomHeaderId id) {
		this.id = id;
	}

	public BXbomHeaderId getId() {
		return this.id;
	}

	public void setId(BXbomHeaderId id) {
		this.id = id;
	}

}
