package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * CDtActivity generated by hbm2java
 */
public class CDtActivity implements java.io.Serializable {

	private String activityId;
	private CCostCenter CCostCenter;
	private CDtCostDriver CDtCostDriver;
	private String activityName;
	private Long isIncreaseActivity;
	private Long isKeyActivity;
	private String uom;
	private Long activityType;
	private String activityUnitCost;
	private String activityAccountId;
	private Date createTime;
	private String creator;
	private String deptid;

	public CDtActivity() {
	}

	public CDtActivity(String activityId) {
		this.activityId = activityId;
	}

	public CDtActivity(String activityId, CCostCenter CCostCenter, CDtCostDriver CDtCostDriver, String activityName,
			Long isIncreaseActivity, Long isKeyActivity, String uom, Long activityType, String activityUnitCost,
			String activityAccountId, Date createTime, String creator, String deptid) {
		this.activityId = activityId;
		this.CCostCenter = CCostCenter;
		this.CDtCostDriver = CDtCostDriver;
		this.activityName = activityName;
		this.isIncreaseActivity = isIncreaseActivity;
		this.isKeyActivity = isKeyActivity;
		this.uom = uom;
		this.activityType = activityType;
		this.activityUnitCost = activityUnitCost;
		this.activityAccountId = activityAccountId;
		this.createTime = createTime;
		this.creator = creator;
		this.deptid = deptid;
	}

	public String getActivityId() {
		return this.activityId;
	}

	public void setActivityId(String activityId) {
		this.activityId = activityId;
	}

	public CCostCenter getCCostCenter() {
		return this.CCostCenter;
	}

	public void setCCostCenter(CCostCenter CCostCenter) {
		this.CCostCenter = CCostCenter;
	}

	public CDtCostDriver getCDtCostDriver() {
		return this.CDtCostDriver;
	}

	public void setCDtCostDriver(CDtCostDriver CDtCostDriver) {
		this.CDtCostDriver = CDtCostDriver;
	}

	public String getActivityName() {
		return this.activityName;
	}

	public void setActivityName(String activityName) {
		this.activityName = activityName;
	}

	public Long getIsIncreaseActivity() {
		return this.isIncreaseActivity;
	}

	public void setIsIncreaseActivity(Long isIncreaseActivity) {
		this.isIncreaseActivity = isIncreaseActivity;
	}

	public Long getIsKeyActivity() {
		return this.isKeyActivity;
	}

	public void setIsKeyActivity(Long isKeyActivity) {
		this.isKeyActivity = isKeyActivity;
	}

	public String getUom() {
		return this.uom;
	}

	public void setUom(String uom) {
		this.uom = uom;
	}

	public Long getActivityType() {
		return this.activityType;
	}

	public void setActivityType(Long activityType) {
		this.activityType = activityType;
	}

	public String getActivityUnitCost() {
		return this.activityUnitCost;
	}

	public void setActivityUnitCost(String activityUnitCost) {
		this.activityUnitCost = activityUnitCost;
	}

	public String getActivityAccountId() {
		return this.activityAccountId;
	}

	public void setActivityAccountId(String activityAccountId) {
		this.activityAccountId = activityAccountId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public String getDeptid() {
		return this.deptid;
	}

	public void setDeptid(String deptid) {
		this.deptid = deptid;
	}

}
