package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * CSnresult generated by hbm2java
 */
public class CSnresult implements java.io.Serializable {

	private String sruid;
	private String cruid;
	private String sn;
	private String creator;
	private Date creattime;
	private String notes;
	private String features;
	private String featuresFormat;
	private String snuid;

	public CSnresult() {
	}

	public CSnresult(String sruid) {
		this.sruid = sruid;
	}

	public CSnresult(String sruid, String cruid, String sn, String creator, Date creattime, String notes,
			String features, String featuresFormat, String snuid) {
		this.sruid = sruid;
		this.cruid = cruid;
		this.sn = sn;
		this.creator = creator;
		this.creattime = creattime;
		this.notes = notes;
		this.features = features;
		this.featuresFormat = featuresFormat;
		this.snuid = snuid;
	}

	public String getSruid() {
		return this.sruid;
	}

	public void setSruid(String sruid) {
		this.sruid = sruid;
	}

	public String getCruid() {
		return this.cruid;
	}

	public void setCruid(String cruid) {
		this.cruid = cruid;
	}

	public String getSn() {
		return this.sn;
	}

	public void setSn(String sn) {
		this.sn = sn;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Date getCreattime() {
		return this.creattime;
	}

	public void setCreattime(Date creattime) {
		this.creattime = creattime;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getFeatures() {
		return this.features;
	}

	public void setFeatures(String features) {
		this.features = features;
	}

	public String getFeaturesFormat() {
		return this.featuresFormat;
	}

	public void setFeaturesFormat(String featuresFormat) {
		this.featuresFormat = featuresFormat;
	}

	public String getSnuid() {
		return this.snuid;
	}

	public void setSnuid(String snuid) {
		this.snuid = snuid;
	}

}
