package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

/**
 * CvCostDriver generated by hbm2java
 */
public class CvCostDriver implements java.io.Serializable {

	private CvCostDriverId id;

	public CvCostDriver() {
	}

	public CvCostDriver(CvCostDriverId id) {
		this.id = id;
	}

	public CvCostDriverId getId() {
		return this.id;
	}

	public void setId(CvCostDriverId id) {
		this.id = id;
	}

}
