package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

/**
 * DxjDevice generated by hbm2java
 */
public class DxjDevice implements java.io.Serializable {

	private DxjDeviceId id;

	public DxjDevice() {
	}

	public DxjDevice(DxjDeviceId id) {
		this.id = id;
	}

	public DxjDeviceId getId() {
		return this.id;
	}

	public void setId(DxjDeviceId id) {
		this.id = id;
	}

}
