package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

/**
 * HisREmployee generated by hbm2java
 */
public class HisREmployee implements java.io.Serializable {

	private HisREmployeeId id;

	public HisREmployee() {
	}

	public HisREmployee(HisREmployeeId id) {
		this.id = id;
	}

	public HisREmployeeId getId() {
		return this.id;
	}

	public void setId(HisREmployeeId id) {
		this.id = id;
	}

}
