package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * HWorkhourDetail generated by hbm2java
 */
public class HWorkhourDetail implements java.io.Serializable {

	private String uniqueid;
	private HWorkhourHeader HWorkhourHeader;
	private String employeeid;
	private String resuid;
	private String worktype;
	private Date workdate;
	private String shiftid;
	private String taskuid;
	private String assnuid;
	private String partNumber;
	private String drawingid;
	private String batchnum;
	private String operationIddesc;
	private BigDecimal preoptime;
	private BigDecimal runtime;
	private BigDecimal completeqty;
	private BigDecimal completework;
	private BigDecimal actualwork;
	private BigDecimal optype;
	private String creator;
	private Date createtime;
	private String notes;
	private String sourceType;
	private Long verifyState;
	private BigDecimal overtimework;
	private BigDecimal vacationwork;
	private String opuid;
	private String deptid;
	private String deptname;
	private String verifyReason;
	private String verifyEmployee;
	private Date verifyTime;
	private String partname;
	private String versionid;
	private String operationname;

	public HWorkhourDetail() {
	}

	public HWorkhourDetail(String uniqueid) {
		this.uniqueid = uniqueid;
	}

	public HWorkhourDetail(String uniqueid, HWorkhourHeader HWorkhourHeader, String employeeid, String resuid,
			String worktype, Date workdate, String shiftid, String taskuid, String assnuid, String partNumber,
			String drawingid, String batchnum, String operationIddesc, BigDecimal preoptime, BigDecimal runtime,
			BigDecimal completeqty, BigDecimal completework, BigDecimal actualwork, BigDecimal optype, String creator,
			Date createtime, String notes, String sourceType, Long verifyState, BigDecimal overtimework,
			BigDecimal vacationwork, String opuid, String deptid, String deptname, String verifyReason,
			String verifyEmployee, Date verifyTime, String partname, String versionid, String operationname) {
		this.uniqueid = uniqueid;
		this.HWorkhourHeader = HWorkhourHeader;
		this.employeeid = employeeid;
		this.resuid = resuid;
		this.worktype = worktype;
		this.workdate = workdate;
		this.shiftid = shiftid;
		this.taskuid = taskuid;
		this.assnuid = assnuid;
		this.partNumber = partNumber;
		this.drawingid = drawingid;
		this.batchnum = batchnum;
		this.operationIddesc = operationIddesc;
		this.preoptime = preoptime;
		this.runtime = runtime;
		this.completeqty = completeqty;
		this.completework = completework;
		this.actualwork = actualwork;
		this.optype = optype;
		this.creator = creator;
		this.createtime = createtime;
		this.notes = notes;
		this.sourceType = sourceType;
		this.verifyState = verifyState;
		this.overtimework = overtimework;
		this.vacationwork = vacationwork;
		this.opuid = opuid;
		this.deptid = deptid;
		this.deptname = deptname;
		this.verifyReason = verifyReason;
		this.verifyEmployee = verifyEmployee;
		this.verifyTime = verifyTime;
		this.partname = partname;
		this.versionid = versionid;
		this.operationname = operationname;
	}

	public String getUniqueid() {
		return this.uniqueid;
	}

	public void setUniqueid(String uniqueid) {
		this.uniqueid = uniqueid;
	}

	public HWorkhourHeader getHWorkhourHeader() {
		return this.HWorkhourHeader;
	}

	public void setHWorkhourHeader(HWorkhourHeader HWorkhourHeader) {
		this.HWorkhourHeader = HWorkhourHeader;
	}

	public String getEmployeeid() {
		return this.employeeid;
	}

	public void setEmployeeid(String employeeid) {
		this.employeeid = employeeid;
	}

	public String getResuid() {
		return this.resuid;
	}

	public void setResuid(String resuid) {
		this.resuid = resuid;
	}

	public String getWorktype() {
		return this.worktype;
	}

	public void setWorktype(String worktype) {
		this.worktype = worktype;
	}

	public Date getWorkdate() {
		return this.workdate;
	}

	public void setWorkdate(Date workdate) {
		this.workdate = workdate;
	}

	public String getShiftid() {
		return this.shiftid;
	}

	public void setShiftid(String shiftid) {
		this.shiftid = shiftid;
	}

	public String getTaskuid() {
		return this.taskuid;
	}

	public void setTaskuid(String taskuid) {
		this.taskuid = taskuid;
	}

	public String getAssnuid() {
		return this.assnuid;
	}

	public void setAssnuid(String assnuid) {
		this.assnuid = assnuid;
	}

	public String getPartNumber() {
		return this.partNumber;
	}

	public void setPartNumber(String partNumber) {
		this.partNumber = partNumber;
	}

	public String getDrawingid() {
		return this.drawingid;
	}

	public void setDrawingid(String drawingid) {
		this.drawingid = drawingid;
	}

	public String getBatchnum() {
		return this.batchnum;
	}

	public void setBatchnum(String batchnum) {
		this.batchnum = batchnum;
	}

	public String getOperationIddesc() {
		return this.operationIddesc;
	}

	public void setOperationIddesc(String operationIddesc) {
		this.operationIddesc = operationIddesc;
	}

	public BigDecimal getPreoptime() {
		return this.preoptime;
	}

	public void setPreoptime(BigDecimal preoptime) {
		this.preoptime = preoptime;
	}

	public BigDecimal getRuntime() {
		return this.runtime;
	}

	public void setRuntime(BigDecimal runtime) {
		this.runtime = runtime;
	}

	public BigDecimal getCompleteqty() {
		return this.completeqty;
	}

	public void setCompleteqty(BigDecimal completeqty) {
		this.completeqty = completeqty;
	}

	public BigDecimal getCompletework() {
		return this.completework;
	}

	public void setCompletework(BigDecimal completework) {
		this.completework = completework;
	}

	public BigDecimal getActualwork() {
		return this.actualwork;
	}

	public void setActualwork(BigDecimal actualwork) {
		this.actualwork = actualwork;
	}

	public BigDecimal getOptype() {
		return this.optype;
	}

	public void setOptype(BigDecimal optype) {
		this.optype = optype;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getSourceType() {
		return this.sourceType;
	}

	public void setSourceType(String sourceType) {
		this.sourceType = sourceType;
	}

	public Long getVerifyState() {
		return this.verifyState;
	}

	public void setVerifyState(Long verifyState) {
		this.verifyState = verifyState;
	}

	public BigDecimal getOvertimework() {
		return this.overtimework;
	}

	public void setOvertimework(BigDecimal overtimework) {
		this.overtimework = overtimework;
	}

	public BigDecimal getVacationwork() {
		return this.vacationwork;
	}

	public void setVacationwork(BigDecimal vacationwork) {
		this.vacationwork = vacationwork;
	}

	public String getOpuid() {
		return this.opuid;
	}

	public void setOpuid(String opuid) {
		this.opuid = opuid;
	}

	public String getDeptid() {
		return this.deptid;
	}

	public void setDeptid(String deptid) {
		this.deptid = deptid;
	}

	public String getDeptname() {
		return this.deptname;
	}

	public void setDeptname(String deptname) {
		this.deptname = deptname;
	}

	public String getVerifyReason() {
		return this.verifyReason;
	}

	public void setVerifyReason(String verifyReason) {
		this.verifyReason = verifyReason;
	}

	public String getVerifyEmployee() {
		return this.verifyEmployee;
	}

	public void setVerifyEmployee(String verifyEmployee) {
		this.verifyEmployee = verifyEmployee;
	}

	public Date getVerifyTime() {
		return this.verifyTime;
	}

	public void setVerifyTime(Date verifyTime) {
		this.verifyTime = verifyTime;
	}

	public String getPartname() {
		return this.partname;
	}

	public void setPartname(String partname) {
		this.partname = partname;
	}

	public String getVersionid() {
		return this.versionid;
	}

	public void setVersionid(String versionid) {
		this.versionid = versionid;
	}

	public String getOperationname() {
		return this.operationname;
	}

	public void setOperationname(String operationname) {
		this.operationname = operationname;
	}

}
