package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

/**
 * IIoboxDetailId generated by hbm2java
 */
public class IIoboxDetailId implements java.io.Serializable {

	private String invioid;
	private String turnBoxId;
	private String warehouseid;
	private String binid;
	private String materialusn;
	private Long ioqty;

	public IIoboxDetailId() {
	}

	public IIoboxDetailId(String invioid, String turnBoxId, String warehouseid, String binid, String materialusn,
			Long ioqty) {
		this.invioid = invioid;
		this.turnBoxId = turnBoxId;
		this.warehouseid = warehouseid;
		this.binid = binid;
		this.materialusn = materialusn;
		this.ioqty = ioqty;
	}

	public String getInvioid() {
		return this.invioid;
	}

	public void setInvioid(String invioid) {
		this.invioid = invioid;
	}

	public String getTurnBoxId() {
		return this.turnBoxId;
	}

	public void setTurnBoxId(String turnBoxId) {
		this.turnBoxId = turnBoxId;
	}

	public String getWarehouseid() {
		return this.warehouseid;
	}

	public void setWarehouseid(String warehouseid) {
		this.warehouseid = warehouseid;
	}

	public String getBinid() {
		return this.binid;
	}

	public void setBinid(String binid) {
		this.binid = binid;
	}

	public String getMaterialusn() {
		return this.materialusn;
	}

	public void setMaterialusn(String materialusn) {
		this.materialusn = materialusn;
	}

	public Long getIoqty() {
		return this.ioqty;
	}

	public void setIoqty(Long ioqty) {
		this.ioqty = ioqty;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IIoboxDetailId))
			return false;
		IIoboxDetailId castOther = (IIoboxDetailId) other;

		return ((this.getInvioid() == castOther.getInvioid()) || (this.getInvioid() != null
				&& castOther.getInvioid() != null && this.getInvioid().equals(castOther.getInvioid())))
				&& ((this.getTurnBoxId() == castOther.getTurnBoxId()) || (this.getTurnBoxId() != null
						&& castOther.getTurnBoxId() != null && this.getTurnBoxId().equals(castOther.getTurnBoxId())))
				&& ((this.getWarehouseid() == castOther.getWarehouseid())
						|| (this.getWarehouseid() != null && castOther.getWarehouseid() != null
								&& this.getWarehouseid().equals(castOther.getWarehouseid())))
				&& ((this.getBinid() == castOther.getBinid()) || (this.getBinid() != null
						&& castOther.getBinid() != null && this.getBinid().equals(castOther.getBinid())))
				&& ((this.getMaterialusn() == castOther.getMaterialusn())
						|| (this.getMaterialusn() != null && castOther.getMaterialusn() != null
								&& this.getMaterialusn().equals(castOther.getMaterialusn())))
				&& ((this.getIoqty() == castOther.getIoqty()) || (this.getIoqty() != null
						&& castOther.getIoqty() != null && this.getIoqty().equals(castOther.getIoqty())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getInvioid() == null ? 0 : this.getInvioid().hashCode());
		result = 37 * result + (getTurnBoxId() == null ? 0 : this.getTurnBoxId().hashCode());
		result = 37 * result + (getWarehouseid() == null ? 0 : this.getWarehouseid().hashCode());
		result = 37 * result + (getBinid() == null ? 0 : this.getBinid().hashCode());
		result = 37 * result + (getMaterialusn() == null ? 0 : this.getMaterialusn().hashCode());
		result = 37 * result + (getIoqty() == null ? 0 : this.getIoqty().hashCode());
		return result;
	}

}
