package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * IIodemandHeader generated by hbm2java
 */
public class IIodemandHeader implements java.io.Serializable {

	private String invdemandid;
	private String invdemandtype;
	private String invdemandstate;
	private String taskuid;
	private String operationIddesc;
	private String taskname;
	private String drawingid;
	private String batchnum;
	private String prepareTaskuid;
	private String routing;
	private String opuid;
	private String creator;
	private Date createtime;
	private String deployer;
	private Date deploytime;
	private String mastershop;
	private String deptid;
	private String employeeid;
	private Date finishtime;
	private Set IIodemandDetails = new HashSet(0);

	public IIodemandHeader() {
	}

	public IIodemandHeader(String invdemandid) {
		this.invdemandid = invdemandid;
	}

	public IIodemandHeader(String invdemandid, String invdemandtype, String invdemandstate, String taskuid,
			String operationIddesc, String taskname, String drawingid, String batchnum, String prepareTaskuid,
			String routing, String opuid, String creator, Date createtime, String deployer, Date deploytime,
			String mastershop, String deptid, String employeeid, Date finishtime, Set IIodemandDetails) {
		this.invdemandid = invdemandid;
		this.invdemandtype = invdemandtype;
		this.invdemandstate = invdemandstate;
		this.taskuid = taskuid;
		this.operationIddesc = operationIddesc;
		this.taskname = taskname;
		this.drawingid = drawingid;
		this.batchnum = batchnum;
		this.prepareTaskuid = prepareTaskuid;
		this.routing = routing;
		this.opuid = opuid;
		this.creator = creator;
		this.createtime = createtime;
		this.deployer = deployer;
		this.deploytime = deploytime;
		this.mastershop = mastershop;
		this.deptid = deptid;
		this.employeeid = employeeid;
		this.finishtime = finishtime;
		this.IIodemandDetails = IIodemandDetails;
	}

	public String getInvdemandid() {
		return this.invdemandid;
	}

	public void setInvdemandid(String invdemandid) {
		this.invdemandid = invdemandid;
	}

	public String getInvdemandtype() {
		return this.invdemandtype;
	}

	public void setInvdemandtype(String invdemandtype) {
		this.invdemandtype = invdemandtype;
	}

	public String getInvdemandstate() {
		return this.invdemandstate;
	}

	public void setInvdemandstate(String invdemandstate) {
		this.invdemandstate = invdemandstate;
	}

	public String getTaskuid() {
		return this.taskuid;
	}

	public void setTaskuid(String taskuid) {
		this.taskuid = taskuid;
	}

	public String getOperationIddesc() {
		return this.operationIddesc;
	}

	public void setOperationIddesc(String operationIddesc) {
		this.operationIddesc = operationIddesc;
	}

	public String getTaskname() {
		return this.taskname;
	}

	public void setTaskname(String taskname) {
		this.taskname = taskname;
	}

	public String getDrawingid() {
		return this.drawingid;
	}

	public void setDrawingid(String drawingid) {
		this.drawingid = drawingid;
	}

	public String getBatchnum() {
		return this.batchnum;
	}

	public void setBatchnum(String batchnum) {
		this.batchnum = batchnum;
	}

	public String getPrepareTaskuid() {
		return this.prepareTaskuid;
	}

	public void setPrepareTaskuid(String prepareTaskuid) {
		this.prepareTaskuid = prepareTaskuid;
	}

	public String getRouting() {
		return this.routing;
	}

	public void setRouting(String routing) {
		this.routing = routing;
	}

	public String getOpuid() {
		return this.opuid;
	}

	public void setOpuid(String opuid) {
		this.opuid = opuid;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getDeployer() {
		return this.deployer;
	}

	public void setDeployer(String deployer) {
		this.deployer = deployer;
	}

	public Date getDeploytime() {
		return this.deploytime;
	}

	public void setDeploytime(Date deploytime) {
		this.deploytime = deploytime;
	}

	public String getMastershop() {
		return this.mastershop;
	}

	public void setMastershop(String mastershop) {
		this.mastershop = mastershop;
	}

	public String getDeptid() {
		return this.deptid;
	}

	public void setDeptid(String deptid) {
		this.deptid = deptid;
	}

	public String getEmployeeid() {
		return this.employeeid;
	}

	public void setEmployeeid(String employeeid) {
		this.employeeid = employeeid;
	}

	public Date getFinishtime() {
		return this.finishtime;
	}

	public void setFinishtime(Date finishtime) {
		this.finishtime = finishtime;
	}

	public Set getIIodemandDetails() {
		return this.IIodemandDetails;
	}

	public void setIIodemandDetails(Set IIodemandDetails) {
		this.IIodemandDetails = IIodemandDetails;
	}

}
