package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

/**
 * IvMonthcheckdetail generated by hbm2java
 */
public class IvMonthcheckdetail implements java.io.Serializable {

	private IvMonthcheckdetailId id;

	public IvMonthcheckdetail() {
	}

	public IvMonthcheckdetail(IvMonthcheckdetailId id) {
		this.id = id;
	}

	public IvMonthcheckdetailId getId() {
		return this.id;
	}

	public void setId(IvMonthcheckdetailId id) {
		this.id = id;
	}

}
