package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

/**
 * IvWarebinmanagerId generated by hbm2java
 */
public class IvWarebinmanagerId implements java.io.Serializable {

	private String warehouseid;
	private String binid;
	private String employeeid;
	private String duty;
	private Byte isdefault;
	private String binname;
	private String bintype;
	private String employeename;

	public IvWarebinmanagerId() {
	}

	public IvWarebinmanagerId(String warehouseid, String binid, String employeeid, String employeename) {
		this.warehouseid = warehouseid;
		this.binid = binid;
		this.employeeid = employeeid;
		this.employeename = employeename;
	}

	public IvWarebinmanagerId(String warehouseid, String binid, String employeeid, String duty, Byte isdefault,
			String binname, String bintype, String employeename) {
		this.warehouseid = warehouseid;
		this.binid = binid;
		this.employeeid = employeeid;
		this.duty = duty;
		this.isdefault = isdefault;
		this.binname = binname;
		this.bintype = bintype;
		this.employeename = employeename;
	}

	public String getWarehouseid() {
		return this.warehouseid;
	}

	public void setWarehouseid(String warehouseid) {
		this.warehouseid = warehouseid;
	}

	public String getBinid() {
		return this.binid;
	}

	public void setBinid(String binid) {
		this.binid = binid;
	}

	public String getEmployeeid() {
		return this.employeeid;
	}

	public void setEmployeeid(String employeeid) {
		this.employeeid = employeeid;
	}

	public String getDuty() {
		return this.duty;
	}

	public void setDuty(String duty) {
		this.duty = duty;
	}

	public Byte getIsdefault() {
		return this.isdefault;
	}

	public void setIsdefault(Byte isdefault) {
		this.isdefault = isdefault;
	}

	public String getBinname() {
		return this.binname;
	}

	public void setBinname(String binname) {
		this.binname = binname;
	}

	public String getBintype() {
		return this.bintype;
	}

	public void setBintype(String bintype) {
		this.bintype = bintype;
	}

	public String getEmployeename() {
		return this.employeename;
	}

	public void setEmployeename(String employeename) {
		this.employeename = employeename;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IvWarebinmanagerId))
			return false;
		IvWarebinmanagerId castOther = (IvWarebinmanagerId) other;

		return ((this.getWarehouseid() == castOther.getWarehouseid()) || (this.getWarehouseid() != null
				&& castOther.getWarehouseid() != null && this.getWarehouseid().equals(castOther.getWarehouseid())))
				&& ((this.getBinid() == castOther.getBinid()) || (this.getBinid() != null
						&& castOther.getBinid() != null && this.getBinid().equals(castOther.getBinid())))
				&& ((this.getEmployeeid() == castOther.getEmployeeid()) || (this.getEmployeeid() != null
						&& castOther.getEmployeeid() != null && this.getEmployeeid().equals(castOther.getEmployeeid())))
				&& ((this.getDuty() == castOther.getDuty()) || (this.getDuty() != null && castOther.getDuty() != null
						&& this.getDuty().equals(castOther.getDuty())))
				&& ((this.getIsdefault() == castOther.getIsdefault()) || (this.getIsdefault() != null
						&& castOther.getIsdefault() != null && this.getIsdefault().equals(castOther.getIsdefault())))
				&& ((this.getBinname() == castOther.getBinname()) || (this.getBinname() != null
						&& castOther.getBinname() != null && this.getBinname().equals(castOther.getBinname())))
				&& ((this.getBintype() == castOther.getBintype()) || (this.getBintype() != null
						&& castOther.getBintype() != null && this.getBintype().equals(castOther.getBintype())))
				&& ((this.getEmployeename() == castOther.getEmployeename())
						|| (this.getEmployeename() != null && castOther.getEmployeename() != null
								&& this.getEmployeename().equals(castOther.getEmployeename())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getWarehouseid() == null ? 0 : this.getWarehouseid().hashCode());
		result = 37 * result + (getBinid() == null ? 0 : this.getBinid().hashCode());
		result = 37 * result + (getEmployeeid() == null ? 0 : this.getEmployeeid().hashCode());
		result = 37 * result + (getDuty() == null ? 0 : this.getDuty().hashCode());
		result = 37 * result + (getIsdefault() == null ? 0 : this.getIsdefault().hashCode());
		result = 37 * result + (getBinname() == null ? 0 : this.getBinname().hashCode());
		result = 37 * result + (getBintype() == null ? 0 : this.getBintype().hashCode());
		result = 37 * result + (getEmployeename() == null ? 0 : this.getEmployeename().hashCode());
		return result;
	}

}
