package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

/**
 * J4Bills generated by hbm2java
 */
public class J4Bills implements java.io.Serializable {

	private J4BillsId id;

	public J4Bills() {
	}

	public J4Bills(J4BillsId id) {
		this.id = id;
	}

	public J4BillsId getId() {
		return this.id;
	}

	public void setId(J4BillsId id) {
		this.id = id;
	}

}
