package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Jbpm4Swimlane generated by hbm2java
 */
public class Jbpm4Swimlane implements java.io.Serializable {

	private BigDecimal dbid;
	private Jbpm4Execution jbpm4Execution;
	private long dbversion;
	private String name;
	private String assignee;
	private Set jbpm4Participations = new HashSet(0);
	private Set jbpm4Tasks = new HashSet(0);

	public Jbpm4Swimlane() {
	}

	public Jbpm4Swimlane(BigDecimal dbid, long dbversion) {
		this.dbid = dbid;
		this.dbversion = dbversion;
	}

	public Jbpm4Swimlane(BigDecimal dbid, Jbpm4Execution jbpm4Execution, long dbversion, String name, String assignee,
			Set jbpm4Participations, Set jbpm4Tasks) {
		this.dbid = dbid;
		this.jbpm4Execution = jbpm4Execution;
		this.dbversion = dbversion;
		this.name = name;
		this.assignee = assignee;
		this.jbpm4Participations = jbpm4Participations;
		this.jbpm4Tasks = jbpm4Tasks;
	}

	public BigDecimal getDbid() {
		return this.dbid;
	}

	public void setDbid(BigDecimal dbid) {
		this.dbid = dbid;
	}

	public Jbpm4Execution getJbpm4Execution() {
		return this.jbpm4Execution;
	}

	public void setJbpm4Execution(Jbpm4Execution jbpm4Execution) {
		this.jbpm4Execution = jbpm4Execution;
	}

	public long getDbversion() {
		return this.dbversion;
	}

	public void setDbversion(long dbversion) {
		this.dbversion = dbversion;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAssignee() {
		return this.assignee;
	}

	public void setAssignee(String assignee) {
		this.assignee = assignee;
	}

	public Set getJbpm4Participations() {
		return this.jbpm4Participations;
	}

	public void setJbpm4Participations(Set jbpm4Participations) {
		this.jbpm4Participations = jbpm4Participations;
	}

	public Set getJbpm4Tasks() {
		return this.jbpm4Tasks;
	}

	public void setJbpm4Tasks(Set jbpm4Tasks) {
		this.jbpm4Tasks = jbpm4Tasks;
	}

}
