package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

/**
 * JbpmIdPermissions generated by hbm2java
 */
public class JbpmIdPermissions implements java.io.Serializable {

	private JbpmIdPermissionsId id;

	public JbpmIdPermissions() {
	}

	public JbpmIdPermissions(JbpmIdPermissionsId id) {
		this.id = id;
	}

	public JbpmIdPermissionsId getId() {
		return this.id;
	}

	public void setId(JbpmIdPermissionsId id) {
		this.id = id;
	}

}
