package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Jbpm4HistTask generated by hbm2java
 */
public class Jbpm4HistTask implements java.io.Serializable {

	private BigDecimal dbid;
	private Jbpm4HistTask jbpm4HistTask;
	private long dbversion;
	private String execution;
	private String outcome;
	private String assignee;
	private Long priority;
	private String state;
	private Serializable create;
	private Serializable end;
	private BigDecimal duration;
	private Long nextidx;
	private Set jbpm4HistDetails = new HashSet(0);
	private Set jbpm4HistActinsts = new HashSet(0);
	private Set jbpm4HistTasks = new HashSet(0);
	private Set jbpm4HistVars = new HashSet(0);

	public Jbpm4HistTask() {
	}

	public Jbpm4HistTask(BigDecimal dbid, long dbversion) {
		this.dbid = dbid;
		this.dbversion = dbversion;
	}

	public Jbpm4HistTask(BigDecimal dbid, Jbpm4HistTask jbpm4HistTask, long dbversion, String execution, String outcome,
			String assignee, Long priority, String state, Serializable create, Serializable end, BigDecimal duration,
			Long nextidx, Set jbpm4HistDetails, Set jbpm4HistActinsts, Set jbpm4HistTasks, Set jbpm4HistVars) {
		this.dbid = dbid;
		this.jbpm4HistTask = jbpm4HistTask;
		this.dbversion = dbversion;
		this.execution = execution;
		this.outcome = outcome;
		this.assignee = assignee;
		this.priority = priority;
		this.state = state;
		this.create = create;
		this.end = end;
		this.duration = duration;
		this.nextidx = nextidx;
		this.jbpm4HistDetails = jbpm4HistDetails;
		this.jbpm4HistActinsts = jbpm4HistActinsts;
		this.jbpm4HistTasks = jbpm4HistTasks;
		this.jbpm4HistVars = jbpm4HistVars;
	}

	public BigDecimal getDbid() {
		return this.dbid;
	}

	public void setDbid(BigDecimal dbid) {
		this.dbid = dbid;
	}

	public Jbpm4HistTask getJbpm4HistTask() {
		return this.jbpm4HistTask;
	}

	public void setJbpm4HistTask(Jbpm4HistTask jbpm4HistTask) {
		this.jbpm4HistTask = jbpm4HistTask;
	}

	public long getDbversion() {
		return this.dbversion;
	}

	public void setDbversion(long dbversion) {
		this.dbversion = dbversion;
	}

	public String getExecution() {
		return this.execution;
	}

	public void setExecution(String execution) {
		this.execution = execution;
	}

	public String getOutcome() {
		return this.outcome;
	}

	public void setOutcome(String outcome) {
		this.outcome = outcome;
	}

	public String getAssignee() {
		return this.assignee;
	}

	public void setAssignee(String assignee) {
		this.assignee = assignee;
	}

	public Long getPriority() {
		return this.priority;
	}

	public void setPriority(Long priority) {
		this.priority = priority;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Serializable getCreate() {
		return this.create;
	}

	public void setCreate(Serializable create) {
		this.create = create;
	}

	public Serializable getEnd() {
		return this.end;
	}

	public void setEnd(Serializable end) {
		this.end = end;
	}

	public BigDecimal getDuration() {
		return this.duration;
	}

	public void setDuration(BigDecimal duration) {
		this.duration = duration;
	}

	public Long getNextidx() {
		return this.nextidx;
	}

	public void setNextidx(Long nextidx) {
		this.nextidx = nextidx;
	}

	public Set getJbpm4HistDetails() {
		return this.jbpm4HistDetails;
	}

	public void setJbpm4HistDetails(Set jbpm4HistDetails) {
		this.jbpm4HistDetails = jbpm4HistDetails;
	}

	public Set getJbpm4HistActinsts() {
		return this.jbpm4HistActinsts;
	}

	public void setJbpm4HistActinsts(Set jbpm4HistActinsts) {
		this.jbpm4HistActinsts = jbpm4HistActinsts;
	}

	public Set getJbpm4HistTasks() {
		return this.jbpm4HistTasks;
	}

	public void setJbpm4HistTasks(Set jbpm4HistTasks) {
		this.jbpm4HistTasks = jbpm4HistTasks;
	}

	public Set getJbpm4HistVars() {
		return this.jbpm4HistVars;
	}

	public void setJbpm4HistVars(Set jbpm4HistVars) {
		this.jbpm4HistVars = jbpm4HistVars;
	}

}
