package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * JbpmNode generated by hbm2java
 */
public class JbpmNode implements java.io.Serializable {

	private BigDecimal id;
	private JbpmAction jbpmAction;
	private JbpmDelegation jbpmDelegation;
	private JbpmNode jbpmNode;
	private JbpmProcessdefinition jbpmProcessdefinitionByProcessdefinition;
	private JbpmProcessdefinition jbpmProcessdefinitionBySubprocessdefinition;
	private char class_;
	private String name;
	private Boolean isasync;
	private String decisionexpression;
	private Long signal;
	private Boolean createtasks;
	private Boolean endtasks;
	private Long nodecollectionindex;
	private Set jbpmTransitionsForFrom = new HashSet(0);
	private Set jbpmNodes = new HashSet(0);
	private Set jbpmTasksForTasknode = new HashSet(0);
	private Set jbpmLogsForNode = new HashSet(0);
	private Set jbpmMessages = new HashSet(0);
	private Set jbpmLogsForDestinationnode = new HashSet(0);
	private Set jbpmLogsForSourcenode = new HashSet(0);
	private Set jbpmDecisionconditionses = new HashSet(0);
	private Set jbpmVariableaccesses = new HashSet(0);
	private Set jbpmEvents = new HashSet(0);
	private Set jbpmTasksForStartstate = new HashSet(0);
	private Set jbpmTokens = new HashSet(0);
	private Set jbpmProcessdefinitions = new HashSet(0);
	private Set jbpmTransitionsForTo = new HashSet(0);

	public JbpmNode() {
	}

	public JbpmNode(BigDecimal id, char class_) {
		this.id = id;
		this.class_ = class_;
	}

	public JbpmNode(BigDecimal id, JbpmAction jbpmAction, JbpmDelegation jbpmDelegation, JbpmNode jbpmNode,
			JbpmProcessdefinition jbpmProcessdefinitionByProcessdefinition,
			JbpmProcessdefinition jbpmProcessdefinitionBySubprocessdefinition, char class_, String name,
			Boolean isasync, String decisionexpression, Long signal, Boolean createtasks, Boolean endtasks,
			Long nodecollectionindex, Set jbpmTransitionsForFrom, Set jbpmNodes, Set jbpmTasksForTasknode,
			Set jbpmLogsForNode, Set jbpmMessages, Set jbpmLogsForDestinationnode, Set jbpmLogsForSourcenode,
			Set jbpmDecisionconditionses, Set jbpmVariableaccesses, Set jbpmEvents, Set jbpmTasksForStartstate,
			Set jbpmTokens, Set jbpmProcessdefinitions, Set jbpmTransitionsForTo) {
		this.id = id;
		this.jbpmAction = jbpmAction;
		this.jbpmDelegation = jbpmDelegation;
		this.jbpmNode = jbpmNode;
		this.jbpmProcessdefinitionByProcessdefinition = jbpmProcessdefinitionByProcessdefinition;
		this.jbpmProcessdefinitionBySubprocessdefinition = jbpmProcessdefinitionBySubprocessdefinition;
		this.class_ = class_;
		this.name = name;
		this.isasync = isasync;
		this.decisionexpression = decisionexpression;
		this.signal = signal;
		this.createtasks = createtasks;
		this.endtasks = endtasks;
		this.nodecollectionindex = nodecollectionindex;
		this.jbpmTransitionsForFrom = jbpmTransitionsForFrom;
		this.jbpmNodes = jbpmNodes;
		this.jbpmTasksForTasknode = jbpmTasksForTasknode;
		this.jbpmLogsForNode = jbpmLogsForNode;
		this.jbpmMessages = jbpmMessages;
		this.jbpmLogsForDestinationnode = jbpmLogsForDestinationnode;
		this.jbpmLogsForSourcenode = jbpmLogsForSourcenode;
		this.jbpmDecisionconditionses = jbpmDecisionconditionses;
		this.jbpmVariableaccesses = jbpmVariableaccesses;
		this.jbpmEvents = jbpmEvents;
		this.jbpmTasksForStartstate = jbpmTasksForStartstate;
		this.jbpmTokens = jbpmTokens;
		this.jbpmProcessdefinitions = jbpmProcessdefinitions;
		this.jbpmTransitionsForTo = jbpmTransitionsForTo;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public JbpmAction getJbpmAction() {
		return this.jbpmAction;
	}

	public void setJbpmAction(JbpmAction jbpmAction) {
		this.jbpmAction = jbpmAction;
	}

	public JbpmDelegation getJbpmDelegation() {
		return this.jbpmDelegation;
	}

	public void setJbpmDelegation(JbpmDelegation jbpmDelegation) {
		this.jbpmDelegation = jbpmDelegation;
	}

	public JbpmNode getJbpmNode() {
		return this.jbpmNode;
	}

	public void setJbpmNode(JbpmNode jbpmNode) {
		this.jbpmNode = jbpmNode;
	}

	public JbpmProcessdefinition getJbpmProcessdefinitionByProcessdefinition() {
		return this.jbpmProcessdefinitionByProcessdefinition;
	}

	public void setJbpmProcessdefinitionByProcessdefinition(
			JbpmProcessdefinition jbpmProcessdefinitionByProcessdefinition) {
		this.jbpmProcessdefinitionByProcessdefinition = jbpmProcessdefinitionByProcessdefinition;
	}

	public JbpmProcessdefinition getJbpmProcessdefinitionBySubprocessdefinition() {
		return this.jbpmProcessdefinitionBySubprocessdefinition;
	}

	public void setJbpmProcessdefinitionBySubprocessdefinition(
			JbpmProcessdefinition jbpmProcessdefinitionBySubprocessdefinition) {
		this.jbpmProcessdefinitionBySubprocessdefinition = jbpmProcessdefinitionBySubprocessdefinition;
	}

	public char getClass_() {
		return this.class_;
	}

	public void setClass_(char class_) {
		this.class_ = class_;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getIsasync() {
		return this.isasync;
	}

	public void setIsasync(Boolean isasync) {
		this.isasync = isasync;
	}

	public String getDecisionexpression() {
		return this.decisionexpression;
	}

	public void setDecisionexpression(String decisionexpression) {
		this.decisionexpression = decisionexpression;
	}

	public Long getSignal() {
		return this.signal;
	}

	public void setSignal(Long signal) {
		this.signal = signal;
	}

	public Boolean getCreatetasks() {
		return this.createtasks;
	}

	public void setCreatetasks(Boolean createtasks) {
		this.createtasks = createtasks;
	}

	public Boolean getEndtasks() {
		return this.endtasks;
	}

	public void setEndtasks(Boolean endtasks) {
		this.endtasks = endtasks;
	}

	public Long getNodecollectionindex() {
		return this.nodecollectionindex;
	}

	public void setNodecollectionindex(Long nodecollectionindex) {
		this.nodecollectionindex = nodecollectionindex;
	}

	public Set getJbpmTransitionsForFrom() {
		return this.jbpmTransitionsForFrom;
	}

	public void setJbpmTransitionsForFrom(Set jbpmTransitionsForFrom) {
		this.jbpmTransitionsForFrom = jbpmTransitionsForFrom;
	}

	public Set getJbpmNodes() {
		return this.jbpmNodes;
	}

	public void setJbpmNodes(Set jbpmNodes) {
		this.jbpmNodes = jbpmNodes;
	}

	public Set getJbpmTasksForTasknode() {
		return this.jbpmTasksForTasknode;
	}

	public void setJbpmTasksForTasknode(Set jbpmTasksForTasknode) {
		this.jbpmTasksForTasknode = jbpmTasksForTasknode;
	}

	public Set getJbpmLogsForNode() {
		return this.jbpmLogsForNode;
	}

	public void setJbpmLogsForNode(Set jbpmLogsForNode) {
		this.jbpmLogsForNode = jbpmLogsForNode;
	}

	public Set getJbpmMessages() {
		return this.jbpmMessages;
	}

	public void setJbpmMessages(Set jbpmMessages) {
		this.jbpmMessages = jbpmMessages;
	}

	public Set getJbpmLogsForDestinationnode() {
		return this.jbpmLogsForDestinationnode;
	}

	public void setJbpmLogsForDestinationnode(Set jbpmLogsForDestinationnode) {
		this.jbpmLogsForDestinationnode = jbpmLogsForDestinationnode;
	}

	public Set getJbpmLogsForSourcenode() {
		return this.jbpmLogsForSourcenode;
	}

	public void setJbpmLogsForSourcenode(Set jbpmLogsForSourcenode) {
		this.jbpmLogsForSourcenode = jbpmLogsForSourcenode;
	}

	public Set getJbpmDecisionconditionses() {
		return this.jbpmDecisionconditionses;
	}

	public void setJbpmDecisionconditionses(Set jbpmDecisionconditionses) {
		this.jbpmDecisionconditionses = jbpmDecisionconditionses;
	}

	public Set getJbpmVariableaccesses() {
		return this.jbpmVariableaccesses;
	}

	public void setJbpmVariableaccesses(Set jbpmVariableaccesses) {
		this.jbpmVariableaccesses = jbpmVariableaccesses;
	}

	public Set getJbpmEvents() {
		return this.jbpmEvents;
	}

	public void setJbpmEvents(Set jbpmEvents) {
		this.jbpmEvents = jbpmEvents;
	}

	public Set getJbpmTasksForStartstate() {
		return this.jbpmTasksForStartstate;
	}

	public void setJbpmTasksForStartstate(Set jbpmTasksForStartstate) {
		this.jbpmTasksForStartstate = jbpmTasksForStartstate;
	}

	public Set getJbpmTokens() {
		return this.jbpmTokens;
	}

	public void setJbpmTokens(Set jbpmTokens) {
		this.jbpmTokens = jbpmTokens;
	}

	public Set getJbpmProcessdefinitions() {
		return this.jbpmProcessdefinitions;
	}

	public void setJbpmProcessdefinitions(Set jbpmProcessdefinitions) {
		this.jbpmProcessdefinitions = jbpmProcessdefinitions;
	}

	public Set getJbpmTransitionsForTo() {
		return this.jbpmTransitionsForTo;
	}

	public void setJbpmTransitionsForTo(Set jbpmTransitionsForTo) {
		this.jbpmTransitionsForTo = jbpmTransitionsForTo;
	}

}
