package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * JbpmComment generated by hbm2java
 */
public class JbpmComment implements java.io.Serializable {

	private BigDecimal id;
	private JbpmTaskinstance jbpmTaskinstance;
	private JbpmToken jbpmToken;
	private long version;
	private String actorid;
	private Date time;
	private String message;
	private Long tokenindex;
	private Long taskinstanceindex;

	public JbpmComment() {
	}

	public JbpmComment(BigDecimal id, long version) {
		this.id = id;
		this.version = version;
	}

	public JbpmComment(BigDecimal id, JbpmTaskinstance jbpmTaskinstance, JbpmToken jbpmToken, long version,
			String actorid, Date time, String message, Long tokenindex, Long taskinstanceindex) {
		this.id = id;
		this.jbpmTaskinstance = jbpmTaskinstance;
		this.jbpmToken = jbpmToken;
		this.version = version;
		this.actorid = actorid;
		this.time = time;
		this.message = message;
		this.tokenindex = tokenindex;
		this.taskinstanceindex = taskinstanceindex;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public JbpmTaskinstance getJbpmTaskinstance() {
		return this.jbpmTaskinstance;
	}

	public void setJbpmTaskinstance(JbpmTaskinstance jbpmTaskinstance) {
		this.jbpmTaskinstance = jbpmTaskinstance;
	}

	public JbpmToken getJbpmToken() {
		return this.jbpmToken;
	}

	public void setJbpmToken(JbpmToken jbpmToken) {
		this.jbpmToken = jbpmToken;
	}

	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	public String getActorid() {
		return this.actorid;
	}

	public void setActorid(String actorid) {
		this.actorid = actorid;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public Long getTokenindex() {
		return this.tokenindex;
	}

	public void setTokenindex(Long tokenindex) {
		this.tokenindex = tokenindex;
	}

	public Long getTaskinstanceindex() {
		return this.taskinstanceindex;
	}

	public void setTaskinstanceindex(Long taskinstanceindex) {
		this.taskinstanceindex = taskinstanceindex;
	}

}
