package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

/**
 * JobshopTaskCompleterateId generated by hbm2java
 */
public class JobshopTaskCompleterateId implements java.io.Serializable {

	private String deptid;
	private String completerate;

	public JobshopTaskCompleterateId() {
	}

	public JobshopTaskCompleterateId(String deptid) {
		this.deptid = deptid;
	}

	public JobshopTaskCompleterateId(String deptid, String completerate) {
		this.deptid = deptid;
		this.completerate = completerate;
	}

	public String getDeptid() {
		return this.deptid;
	}

	public void setDeptid(String deptid) {
		this.deptid = deptid;
	}

	public String getCompleterate() {
		return this.completerate;
	}

	public void setCompleterate(String completerate) {
		this.completerate = completerate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof JobshopTaskCompleterateId))
			return false;
		JobshopTaskCompleterateId castOther = (JobshopTaskCompleterateId) other;

		return ((this.getDeptid() == castOther.getDeptid()) || (this.getDeptid() != null
				&& castOther.getDeptid() != null && this.getDeptid().equals(castOther.getDeptid())))
				&& ((this.getCompleterate() == castOther.getCompleterate())
						|| (this.getCompleterate() != null && castOther.getCompleterate() != null
								&& this.getCompleterate().equals(castOther.getCompleterate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDeptid() == null ? 0 : this.getDeptid().hashCode());
		result = 37 * result + (getCompleterate() == null ? 0 : this.getCompleterate().hashCode());
		return result;
	}

}
