package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;

/**
 * Jobshop产品外协率Id generated by hbm2java
 */
public class Jobshop产品外协率Id implements java.io.Serializable {

	private String deptid;
	private String deptname;
	private String mm;
	private BigDecimal c;

	public Jobshop产品外协率Id() {
	}

	public Jobshop产品外协率Id(String deptid) {
		this.deptid = deptid;
	}

	public Jobshop产品外协率Id(String deptid, String deptname, String mm, BigDecimal c) {
		this.deptid = deptid;
		this.deptname = deptname;
		this.mm = mm;
		this.c = c;
	}

	public String getDeptid() {
		return this.deptid;
	}

	public void setDeptid(String deptid) {
		this.deptid = deptid;
	}

	public String getDeptname() {
		return this.deptname;
	}

	public void setDeptname(String deptname) {
		this.deptname = deptname;
	}

	public String getMm() {
		return this.mm;
	}

	public void setMm(String mm) {
		this.mm = mm;
	}

	public BigDecimal getC() {
		return this.c;
	}

	public void setC(BigDecimal c) {
		this.c = c;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Jobshop产品外协率Id))
			return false;
		Jobshop产品外协率Id castOther = (Jobshop产品外协率Id) other;

		return ((this.getDeptid() == castOther.getDeptid()) || (this.getDeptid() != null
				&& castOther.getDeptid() != null && this.getDeptid().equals(castOther.getDeptid())))
				&& ((this.getDeptname() == castOther.getDeptname()) || (this.getDeptname() != null
						&& castOther.getDeptname() != null && this.getDeptname().equals(castOther.getDeptname())))
				&& ((this.getMm() == castOther.getMm()) || (this.getMm() != null && castOther.getMm() != null
						&& this.getMm().equals(castOther.getMm())))
				&& ((this.getC() == castOther.getC())
						|| (this.getC() != null && castOther.getC() != null && this.getC().equals(castOther.getC())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDeptid() == null ? 0 : this.getDeptid().hashCode());
		result = 37 * result + (getDeptname() == null ? 0 : this.getDeptname().hashCode());
		result = 37 * result + (getMm() == null ? 0 : this.getMm().hashCode());
		result = 37 * result + (getC() == null ? 0 : this.getC().hashCode());
		return result;
	}

}
