package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Jobshop当月短缺产品分析Id generated by hbm2java
 */
public class Jobshop当月短缺产品分析Id implements java.io.Serializable {

	private String deptid;
	private String model;
	private BigDecimal planqty1;
	private BigDecimal lackqty1;
	private BigDecimal planqty2;
	private BigDecimal lackqty2;
	private BigDecimal planqty3;
	private BigDecimal lackqty3;
	private BigDecimal minusday;
	private Date planstart;

	public Jobshop当月短缺产品分析Id() {
	}

	public Jobshop当月短缺产品分析Id(String deptid) {
		this.deptid = deptid;
	}

	public Jobshop当月短缺产品分析Id(String deptid, String model, BigDecimal planqty1, BigDecimal lackqty1, BigDecimal planqty2,
			BigDecimal lackqty2, BigDecimal planqty3, BigDecimal lackqty3, BigDecimal minusday, Date planstart) {
		this.deptid = deptid;
		this.model = model;
		this.planqty1 = planqty1;
		this.lackqty1 = lackqty1;
		this.planqty2 = planqty2;
		this.lackqty2 = lackqty2;
		this.planqty3 = planqty3;
		this.lackqty3 = lackqty3;
		this.minusday = minusday;
		this.planstart = planstart;
	}

	public String getDeptid() {
		return this.deptid;
	}

	public void setDeptid(String deptid) {
		this.deptid = deptid;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public BigDecimal getPlanqty1() {
		return this.planqty1;
	}

	public void setPlanqty1(BigDecimal planqty1) {
		this.planqty1 = planqty1;
	}

	public BigDecimal getLackqty1() {
		return this.lackqty1;
	}

	public void setLackqty1(BigDecimal lackqty1) {
		this.lackqty1 = lackqty1;
	}

	public BigDecimal getPlanqty2() {
		return this.planqty2;
	}

	public void setPlanqty2(BigDecimal planqty2) {
		this.planqty2 = planqty2;
	}

	public BigDecimal getLackqty2() {
		return this.lackqty2;
	}

	public void setLackqty2(BigDecimal lackqty2) {
		this.lackqty2 = lackqty2;
	}

	public BigDecimal getPlanqty3() {
		return this.planqty3;
	}

	public void setPlanqty3(BigDecimal planqty3) {
		this.planqty3 = planqty3;
	}

	public BigDecimal getLackqty3() {
		return this.lackqty3;
	}

	public void setLackqty3(BigDecimal lackqty3) {
		this.lackqty3 = lackqty3;
	}

	public BigDecimal getMinusday() {
		return this.minusday;
	}

	public void setMinusday(BigDecimal minusday) {
		this.minusday = minusday;
	}

	public Date getPlanstart() {
		return this.planstart;
	}

	public void setPlanstart(Date planstart) {
		this.planstart = planstart;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Jobshop当月短缺产品分析Id))
			return false;
		Jobshop当月短缺产品分析Id castOther = (Jobshop当月短缺产品分析Id) other;

		return ((this.getDeptid() == castOther.getDeptid()) || (this.getDeptid() != null
				&& castOther.getDeptid() != null && this.getDeptid().equals(castOther.getDeptid())))
				&& ((this.getModel() == castOther.getModel()) || (this.getModel() != null
						&& castOther.getModel() != null && this.getModel().equals(castOther.getModel())))
				&& ((this.getPlanqty1() == castOther.getPlanqty1()) || (this.getPlanqty1() != null
						&& castOther.getPlanqty1() != null && this.getPlanqty1().equals(castOther.getPlanqty1())))
				&& ((this.getLackqty1() == castOther.getLackqty1()) || (this.getLackqty1() != null
						&& castOther.getLackqty1() != null && this.getLackqty1().equals(castOther.getLackqty1())))
				&& ((this.getPlanqty2() == castOther.getPlanqty2()) || (this.getPlanqty2() != null
						&& castOther.getPlanqty2() != null && this.getPlanqty2().equals(castOther.getPlanqty2())))
				&& ((this.getLackqty2() == castOther.getLackqty2()) || (this.getLackqty2() != null
						&& castOther.getLackqty2() != null && this.getLackqty2().equals(castOther.getLackqty2())))
				&& ((this.getPlanqty3() == castOther.getPlanqty3()) || (this.getPlanqty3() != null
						&& castOther.getPlanqty3() != null && this.getPlanqty3().equals(castOther.getPlanqty3())))
				&& ((this.getLackqty3() == castOther.getLackqty3()) || (this.getLackqty3() != null
						&& castOther.getLackqty3() != null && this.getLackqty3().equals(castOther.getLackqty3())))
				&& ((this.getMinusday() == castOther.getMinusday()) || (this.getMinusday() != null
						&& castOther.getMinusday() != null && this.getMinusday().equals(castOther.getMinusday())))
				&& ((this.getPlanstart() == castOther.getPlanstart()) || (this.getPlanstart() != null
						&& castOther.getPlanstart() != null && this.getPlanstart().equals(castOther.getPlanstart())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDeptid() == null ? 0 : this.getDeptid().hashCode());
		result = 37 * result + (getModel() == null ? 0 : this.getModel().hashCode());
		result = 37 * result + (getPlanqty1() == null ? 0 : this.getPlanqty1().hashCode());
		result = 37 * result + (getLackqty1() == null ? 0 : this.getLackqty1().hashCode());
		result = 37 * result + (getPlanqty2() == null ? 0 : this.getPlanqty2().hashCode());
		result = 37 * result + (getLackqty2() == null ? 0 : this.getLackqty2().hashCode());
		result = 37 * result + (getPlanqty3() == null ? 0 : this.getPlanqty3().hashCode());
		result = 37 * result + (getLackqty3() == null ? 0 : this.getLackqty3().hashCode());
		result = 37 * result + (getMinusday() == null ? 0 : this.getMinusday().hashCode());
		result = 37 * result + (getPlanstart() == null ? 0 : this.getPlanstart().hashCode());
		return result;
	}

}
