package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

/**
 * Jobshop瓶颈设备任务分析 generated by hbm2java
 */
public class Jobshop瓶颈设备任务分析 implements java.io.Serializable {

	private Jobshop瓶颈设备任务分析Id id;

	public Jobshop瓶颈设备任务分析() {
	}

	public Jobshop瓶颈设备任务分析(Jobshop瓶颈设备任务分析Id id) {
		this.id = id;
	}

	public Jobshop瓶颈设备任务分析Id getId() {
		return this.id;
	}

	public void setId(Jobshop瓶颈设备任务分析Id id) {
		this.id = id;
	}

}
