package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;

/**
 * Jobshop件次质量合格率周统计Id generated by hbm2java
 */
public class Jobshop件次质量合格率周统计Id implements java.io.Serializable {

	private String deptid;
	private String kyear;
	private String kweek;
	private BigDecimal submitqty;
	private BigDecimal defectqty;
	private BigDecimal qualityrate;

	public Jobshop件次质量合格率周统计Id() {
	}

	public Jobshop件次质量合格率周统计Id(String deptid) {
		this.deptid = deptid;
	}

	public Jobshop件次质量合格率周统计Id(String deptid, String kyear, String kweek, BigDecimal submitqty, BigDecimal defectqty,
			BigDecimal qualityrate) {
		this.deptid = deptid;
		this.kyear = kyear;
		this.kweek = kweek;
		this.submitqty = submitqty;
		this.defectqty = defectqty;
		this.qualityrate = qualityrate;
	}

	public String getDeptid() {
		return this.deptid;
	}

	public void setDeptid(String deptid) {
		this.deptid = deptid;
	}

	public String getKyear() {
		return this.kyear;
	}

	public void setKyear(String kyear) {
		this.kyear = kyear;
	}

	public String getKweek() {
		return this.kweek;
	}

	public void setKweek(String kweek) {
		this.kweek = kweek;
	}

	public BigDecimal getSubmitqty() {
		return this.submitqty;
	}

	public void setSubmitqty(BigDecimal submitqty) {
		this.submitqty = submitqty;
	}

	public BigDecimal getDefectqty() {
		return this.defectqty;
	}

	public void setDefectqty(BigDecimal defectqty) {
		this.defectqty = defectqty;
	}

	public BigDecimal getQualityrate() {
		return this.qualityrate;
	}

	public void setQualityrate(BigDecimal qualityrate) {
		this.qualityrate = qualityrate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Jobshop件次质量合格率周统计Id))
			return false;
		Jobshop件次质量合格率周统计Id castOther = (Jobshop件次质量合格率周统计Id) other;

		return ((this.getDeptid() == castOther.getDeptid()) || (this.getDeptid() != null
				&& castOther.getDeptid() != null && this.getDeptid().equals(castOther.getDeptid())))
				&& ((this.getKyear() == castOther.getKyear()) || (this.getKyear() != null
						&& castOther.getKyear() != null && this.getKyear().equals(castOther.getKyear())))
				&& ((this.getKweek() == castOther.getKweek()) || (this.getKweek() != null
						&& castOther.getKweek() != null && this.getKweek().equals(castOther.getKweek())))
				&& ((this.getSubmitqty() == castOther.getSubmitqty()) || (this.getSubmitqty() != null
						&& castOther.getSubmitqty() != null && this.getSubmitqty().equals(castOther.getSubmitqty())))
				&& ((this.getDefectqty() == castOther.getDefectqty()) || (this.getDefectqty() != null
						&& castOther.getDefectqty() != null && this.getDefectqty().equals(castOther.getDefectqty())))
				&& ((this.getQualityrate() == castOther.getQualityrate())
						|| (this.getQualityrate() != null && castOther.getQualityrate() != null
								&& this.getQualityrate().equals(castOther.getQualityrate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDeptid() == null ? 0 : this.getDeptid().hashCode());
		result = 37 * result + (getKyear() == null ? 0 : this.getKyear().hashCode());
		result = 37 * result + (getKweek() == null ? 0 : this.getKweek().hashCode());
		result = 37 * result + (getSubmitqty() == null ? 0 : this.getSubmitqty().hashCode());
		result = 37 * result + (getDefectqty() == null ? 0 : this.getDefectqty().hashCode());
		result = 37 * result + (getQualityrate() == null ? 0 : this.getQualityrate().hashCode());
		return result;
	}

}
