package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;

/**
 * KControlPara generated by hbm2java
 */
public class KControlPara implements java.io.Serializable {

	private KControlParaId id;
	private BigDecimal interval;

	public KControlPara() {
	}

	public KControlPara(KControlParaId id, BigDecimal interval) {
		this.id = id;
		this.interval = interval;
	}

	public KControlParaId getId() {
		return this.id;
	}

	public void setId(KControlParaId id) {
		this.id = id;
	}

	public BigDecimal getInterval() {
		return this.interval;
	}

	public void setInterval(BigDecimal interval) {
		this.interval = interval;
	}

}
