package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

/**
 * KManuCycle generated by hbm2java
 */
public class KManuCycle implements java.io.Serializable {

	private KManuCycleId id;

	public KManuCycle() {
	}

	public KManuCycle(KManuCycleId id) {
		this.id = id;
	}

	public KManuCycleId getId() {
		return this.id;
	}

	public void setId(KManuCycleId id) {
		this.id = id;
	}

}
