package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * KQualitymessageId generated by hbm2java
 */
public class KQualitymessageId implements java.io.Serializable {

	private String deptid;
	private String kyear;
	private String kweek;
	private String model;
	private String drawingid;
	private Long defectqty;
	private Long submitqty;
	private BigDecimal qualityrate;
	private Long yicidefectqty;
	private Long yicisubmitqty;
	private BigDecimal yicirate;
	private Long rejectqty;
	private BigDecimal rejectrate;
	private Date kday;

	public KQualitymessageId() {
	}

	public KQualitymessageId(String deptid, String kyear, String kweek, String model, String drawingid, Long defectqty,
			Long submitqty, BigDecimal qualityrate, Long yicidefectqty, Long yicisubmitqty, BigDecimal yicirate,
			Long rejectqty, BigDecimal rejectrate, Date kday) {
		this.deptid = deptid;
		this.kyear = kyear;
		this.kweek = kweek;
		this.model = model;
		this.drawingid = drawingid;
		this.defectqty = defectqty;
		this.submitqty = submitqty;
		this.qualityrate = qualityrate;
		this.yicidefectqty = yicidefectqty;
		this.yicisubmitqty = yicisubmitqty;
		this.yicirate = yicirate;
		this.rejectqty = rejectqty;
		this.rejectrate = rejectrate;
		this.kday = kday;
	}

	public String getDeptid() {
		return this.deptid;
	}

	public void setDeptid(String deptid) {
		this.deptid = deptid;
	}

	public String getKyear() {
		return this.kyear;
	}

	public void setKyear(String kyear) {
		this.kyear = kyear;
	}

	public String getKweek() {
		return this.kweek;
	}

	public void setKweek(String kweek) {
		this.kweek = kweek;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getDrawingid() {
		return this.drawingid;
	}

	public void setDrawingid(String drawingid) {
		this.drawingid = drawingid;
	}

	public Long getDefectqty() {
		return this.defectqty;
	}

	public void setDefectqty(Long defectqty) {
		this.defectqty = defectqty;
	}

	public Long getSubmitqty() {
		return this.submitqty;
	}

	public void setSubmitqty(Long submitqty) {
		this.submitqty = submitqty;
	}

	public BigDecimal getQualityrate() {
		return this.qualityrate;
	}

	public void setQualityrate(BigDecimal qualityrate) {
		this.qualityrate = qualityrate;
	}

	public Long getYicidefectqty() {
		return this.yicidefectqty;
	}

	public void setYicidefectqty(Long yicidefectqty) {
		this.yicidefectqty = yicidefectqty;
	}

	public Long getYicisubmitqty() {
		return this.yicisubmitqty;
	}

	public void setYicisubmitqty(Long yicisubmitqty) {
		this.yicisubmitqty = yicisubmitqty;
	}

	public BigDecimal getYicirate() {
		return this.yicirate;
	}

	public void setYicirate(BigDecimal yicirate) {
		this.yicirate = yicirate;
	}

	public Long getRejectqty() {
		return this.rejectqty;
	}

	public void setRejectqty(Long rejectqty) {
		this.rejectqty = rejectqty;
	}

	public BigDecimal getRejectrate() {
		return this.rejectrate;
	}

	public void setRejectrate(BigDecimal rejectrate) {
		this.rejectrate = rejectrate;
	}

	public Date getKday() {
		return this.kday;
	}

	public void setKday(Date kday) {
		this.kday = kday;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KQualitymessageId))
			return false;
		KQualitymessageId castOther = (KQualitymessageId) other;

		return ((this.getDeptid() == castOther.getDeptid()) || (this.getDeptid() != null
				&& castOther.getDeptid() != null && this.getDeptid().equals(castOther.getDeptid())))
				&& ((this.getKyear() == castOther.getKyear()) || (this.getKyear() != null
						&& castOther.getKyear() != null && this.getKyear().equals(castOther.getKyear())))
				&& ((this.getKweek() == castOther.getKweek()) || (this.getKweek() != null
						&& castOther.getKweek() != null && this.getKweek().equals(castOther.getKweek())))
				&& ((this.getModel() == castOther.getModel()) || (this.getModel() != null
						&& castOther.getModel() != null && this.getModel().equals(castOther.getModel())))
				&& ((this.getDrawingid() == castOther.getDrawingid()) || (this.getDrawingid() != null
						&& castOther.getDrawingid() != null && this.getDrawingid().equals(castOther.getDrawingid())))
				&& ((this.getDefectqty() == castOther.getDefectqty()) || (this.getDefectqty() != null
						&& castOther.getDefectqty() != null && this.getDefectqty().equals(castOther.getDefectqty())))
				&& ((this.getSubmitqty() == castOther.getSubmitqty()) || (this.getSubmitqty() != null
						&& castOther.getSubmitqty() != null && this.getSubmitqty().equals(castOther.getSubmitqty())))
				&& ((this.getQualityrate() == castOther.getQualityrate())
						|| (this.getQualityrate() != null && castOther.getQualityrate() != null
								&& this.getQualityrate().equals(castOther.getQualityrate())))
				&& ((this.getYicidefectqty() == castOther.getYicidefectqty())
						|| (this.getYicidefectqty() != null && castOther.getYicidefectqty() != null
								&& this.getYicidefectqty().equals(castOther.getYicidefectqty())))
				&& ((this.getYicisubmitqty() == castOther.getYicisubmitqty())
						|| (this.getYicisubmitqty() != null && castOther.getYicisubmitqty() != null
								&& this.getYicisubmitqty().equals(castOther.getYicisubmitqty())))
				&& ((this.getYicirate() == castOther.getYicirate()) || (this.getYicirate() != null
						&& castOther.getYicirate() != null && this.getYicirate().equals(castOther.getYicirate())))
				&& ((this.getRejectqty() == castOther.getRejectqty()) || (this.getRejectqty() != null
						&& castOther.getRejectqty() != null && this.getRejectqty().equals(castOther.getRejectqty())))
				&& ((this.getRejectrate() == castOther.getRejectrate()) || (this.getRejectrate() != null
						&& castOther.getRejectrate() != null && this.getRejectrate().equals(castOther.getRejectrate())))
				&& ((this.getKday() == castOther.getKday()) || (this.getKday() != null && castOther.getKday() != null
						&& this.getKday().equals(castOther.getKday())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDeptid() == null ? 0 : this.getDeptid().hashCode());
		result = 37 * result + (getKyear() == null ? 0 : this.getKyear().hashCode());
		result = 37 * result + (getKweek() == null ? 0 : this.getKweek().hashCode());
		result = 37 * result + (getModel() == null ? 0 : this.getModel().hashCode());
		result = 37 * result + (getDrawingid() == null ? 0 : this.getDrawingid().hashCode());
		result = 37 * result + (getDefectqty() == null ? 0 : this.getDefectqty().hashCode());
		result = 37 * result + (getSubmitqty() == null ? 0 : this.getSubmitqty().hashCode());
		result = 37 * result + (getQualityrate() == null ? 0 : this.getQualityrate().hashCode());
		result = 37 * result + (getYicidefectqty() == null ? 0 : this.getYicidefectqty().hashCode());
		result = 37 * result + (getYicisubmitqty() == null ? 0 : this.getYicisubmitqty().hashCode());
		result = 37 * result + (getYicirate() == null ? 0 : this.getYicirate().hashCode());
		result = 37 * result + (getRejectqty() == null ? 0 : this.getRejectqty().hashCode());
		result = 37 * result + (getRejectrate() == null ? 0 : this.getRejectrate().hashCode());
		result = 37 * result + (getKday() == null ? 0 : this.getKday().hashCode());
		return result;
	}

}
