package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

/**
 * KSchedualPara generated by hbm2java
 */
public class KSchedualPara implements java.io.Serializable {

	private KSchedualParaId id;

	public KSchedualPara() {
	}

	public KSchedualPara(KSchedualParaId id) {
		this.id = id;
	}

	public KSchedualParaId getId() {
		return this.id;
	}

	public void setId(KSchedualParaId id) {
		this.id = id;
	}

}
