package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;

/**
 * LagdaysZongjianId generated by hbm2java
 */
public class LagdaysZongjianId implements java.io.Serializable {

	private String lagdesc;
	private BigDecimal 各阶段为检验产品数量;

	public LagdaysZongjianId() {
	}

	public LagdaysZongjianId(String lagdesc, BigDecimal 各阶段为检验产品数量) {
		this.lagdesc = lagdesc;
		this.各阶段为检验产品数量 = 各阶段为检验产品数量;
	}

	public String getLagdesc() {
		return this.lagdesc;
	}

	public void setLagdesc(String lagdesc) {
		this.lagdesc = lagdesc;
	}

	public BigDecimal get各阶段为检验产品数量() {
		return this.各阶段为检验产品数量;
	}

	public void set各阶段为检验产品数量(BigDecimal 各阶段为检验产品数量) {
		this.各阶段为检验产品数量 = 各阶段为检验产品数量;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LagdaysZongjianId))
			return false;
		LagdaysZongjianId castOther = (LagdaysZongjianId) other;

		return ((this.getLagdesc() == castOther.getLagdesc()) || (this.getLagdesc() != null
				&& castOther.getLagdesc() != null && this.getLagdesc().equals(castOther.getLagdesc())))
				&& ((this.get各阶段为检验产品数量() == castOther.get各阶段为检验产品数量())
						|| (this.get各阶段为检验产品数量() != null && castOther.get各阶段为检验产品数量() != null
								&& this.get各阶段为检验产品数量().equals(castOther.get各阶段为检验产品数量())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLagdesc() == null ? 0 : this.getLagdesc().hashCode());
		result = 37 * result + (get各阶段为检验产品数量() == null ? 0 : this.get各阶段为检验产品数量().hashCode());
		return result;
	}

}
