package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * MCheckdetail generated by hbm2java
 */
public class MCheckdetail implements java.io.Serializable {

	private MCheckdetailId id;
	private MCheckheader MCheckheader;
	private String actualsize;
	private String fieldtype;
	private String checker;
	private Date checktime;
	private String creator;
	private Date createtime;
	private String notes;
	private String fieldid;
	private String tooluid;
	private String checkerprint;
	private Long refcheckseq;
	private BigDecimal defectqty;
	private Long qualitystate;
	private String checkposition;
	private String measurebase;
	private BigDecimal lbound;
	private BigDecimal ubound;
	private String standardvalue;
	private String submitcheckuid;
	private BigDecimal spcstandardvalue;
	private String fieldorder;
	private String uniqueid;
	private String materialusn;
	private String checkPic;
	private String checkContent;
	private Boolean isneedcollect;
	private Byte issubmitcheck;
	private String checkpic;
	private String uom;
	private BigDecimal opuid;
	private String dmistollabel;
	private String dmisfeatlabel;
	private BigDecimal manufactureopuid;
	private String dmisfileversion;
	private BigDecimal operationcheckorder;
	private String barcode;
	private String deviation;
	private String checkresult;
	private String defectdesc;
	private String checker1;
	private Date checktime1;
	private String checker2;
	private Date checktime2;
	private String actualsize1;
	private String actualsize2;
	private String tooluid1;
	private String tooluid2;

	public MCheckdetail() {
	}

	public MCheckdetail(MCheckdetailId id, MCheckheader MCheckheader) {
		this.id = id;
		this.MCheckheader = MCheckheader;
	}

	public MCheckdetail(MCheckdetailId id, MCheckheader MCheckheader, String actualsize, String fieldtype,
			String checker, Date checktime, String creator, Date createtime, String notes, String fieldid,
			String tooluid, String checkerprint, Long refcheckseq, BigDecimal defectqty, Long qualitystate,
			String checkposition, String measurebase, BigDecimal lbound, BigDecimal ubound, String standardvalue,
			String submitcheckuid, BigDecimal spcstandardvalue, String fieldorder, String uniqueid, String materialusn,
			String checkPic, String checkContent, Boolean isneedcollect, Byte issubmitcheck, String checkpic,
			String uom, BigDecimal opuid, String dmistollabel, String dmisfeatlabel, BigDecimal manufactureopuid,
			String dmisfileversion, BigDecimal operationcheckorder, String barcode, String deviation,
			String checkresult, String defectdesc, String checker1, Date checktime1, String checker2, Date checktime2,
			String actualsize1, String actualsize2, String tooluid1, String tooluid2) {
		this.id = id;
		this.MCheckheader = MCheckheader;
		this.actualsize = actualsize;
		this.fieldtype = fieldtype;
		this.checker = checker;
		this.checktime = checktime;
		this.creator = creator;
		this.createtime = createtime;
		this.notes = notes;
		this.fieldid = fieldid;
		this.tooluid = tooluid;
		this.checkerprint = checkerprint;
		this.refcheckseq = refcheckseq;
		this.defectqty = defectqty;
		this.qualitystate = qualitystate;
		this.checkposition = checkposition;
		this.measurebase = measurebase;
		this.lbound = lbound;
		this.ubound = ubound;
		this.standardvalue = standardvalue;
		this.submitcheckuid = submitcheckuid;
		this.spcstandardvalue = spcstandardvalue;
		this.fieldorder = fieldorder;
		this.uniqueid = uniqueid;
		this.materialusn = materialusn;
		this.checkPic = checkPic;
		this.checkContent = checkContent;
		this.isneedcollect = isneedcollect;
		this.issubmitcheck = issubmitcheck;
		this.checkpic = checkpic;
		this.uom = uom;
		this.opuid = opuid;
		this.dmistollabel = dmistollabel;
		this.dmisfeatlabel = dmisfeatlabel;
		this.manufactureopuid = manufactureopuid;
		this.dmisfileversion = dmisfileversion;
		this.operationcheckorder = operationcheckorder;
		this.barcode = barcode;
		this.deviation = deviation;
		this.checkresult = checkresult;
		this.defectdesc = defectdesc;
		this.checker1 = checker1;
		this.checktime1 = checktime1;
		this.checker2 = checker2;
		this.checktime2 = checktime2;
		this.actualsize1 = actualsize1;
		this.actualsize2 = actualsize2;
		this.tooluid1 = tooluid1;
		this.tooluid2 = tooluid2;
	}

	public MCheckdetailId getId() {
		return this.id;
	}

	public void setId(MCheckdetailId id) {
		this.id = id;
	}

	public MCheckheader getMCheckheader() {
		return this.MCheckheader;
	}

	public void setMCheckheader(MCheckheader MCheckheader) {
		this.MCheckheader = MCheckheader;
	}

	public String getActualsize() {
		return this.actualsize;
	}

	public void setActualsize(String actualsize) {
		this.actualsize = actualsize;
	}

	public String getFieldtype() {
		return this.fieldtype;
	}

	public void setFieldtype(String fieldtype) {
		this.fieldtype = fieldtype;
	}

	public String getChecker() {
		return this.checker;
	}

	public void setChecker(String checker) {
		this.checker = checker;
	}

	public Date getChecktime() {
		return this.checktime;
	}

	public void setChecktime(Date checktime) {
		this.checktime = checktime;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getFieldid() {
		return this.fieldid;
	}

	public void setFieldid(String fieldid) {
		this.fieldid = fieldid;
	}

	public String getTooluid() {
		return this.tooluid;
	}

	public void setTooluid(String tooluid) {
		this.tooluid = tooluid;
	}

	public String getCheckerprint() {
		return this.checkerprint;
	}

	public void setCheckerprint(String checkerprint) {
		this.checkerprint = checkerprint;
	}

	public Long getRefcheckseq() {
		return this.refcheckseq;
	}

	public void setRefcheckseq(Long refcheckseq) {
		this.refcheckseq = refcheckseq;
	}

	public BigDecimal getDefectqty() {
		return this.defectqty;
	}

	public void setDefectqty(BigDecimal defectqty) {
		this.defectqty = defectqty;
	}

	public Long getQualitystate() {
		return this.qualitystate;
	}

	public void setQualitystate(Long qualitystate) {
		this.qualitystate = qualitystate;
	}

	public String getCheckposition() {
		return this.checkposition;
	}

	public void setCheckposition(String checkposition) {
		this.checkposition = checkposition;
	}

	public String getMeasurebase() {
		return this.measurebase;
	}

	public void setMeasurebase(String measurebase) {
		this.measurebase = measurebase;
	}

	public BigDecimal getLbound() {
		return this.lbound;
	}

	public void setLbound(BigDecimal lbound) {
		this.lbound = lbound;
	}

	public BigDecimal getUbound() {
		return this.ubound;
	}

	public void setUbound(BigDecimal ubound) {
		this.ubound = ubound;
	}

	public String getStandardvalue() {
		return this.standardvalue;
	}

	public void setStandardvalue(String standardvalue) {
		this.standardvalue = standardvalue;
	}

	public String getSubmitcheckuid() {
		return this.submitcheckuid;
	}

	public void setSubmitcheckuid(String submitcheckuid) {
		this.submitcheckuid = submitcheckuid;
	}

	public BigDecimal getSpcstandardvalue() {
		return this.spcstandardvalue;
	}

	public void setSpcstandardvalue(BigDecimal spcstandardvalue) {
		this.spcstandardvalue = spcstandardvalue;
	}

	public String getFieldorder() {
		return this.fieldorder;
	}

	public void setFieldorder(String fieldorder) {
		this.fieldorder = fieldorder;
	}

	public String getUniqueid() {
		return this.uniqueid;
	}

	public void setUniqueid(String uniqueid) {
		this.uniqueid = uniqueid;
	}

	public String getMaterialusn() {
		return this.materialusn;
	}

	public void setMaterialusn(String materialusn) {
		this.materialusn = materialusn;
	}

	public String getCheckPic() {
		return this.checkPic;
	}

	public void setCheckPic(String checkPic) {
		this.checkPic = checkPic;
	}

	public String getCheckContent() {
		return this.checkContent;
	}

	public void setCheckContent(String checkContent) {
		this.checkContent = checkContent;
	}

	public Boolean getIsneedcollect() {
		return this.isneedcollect;
	}

	public void setIsneedcollect(Boolean isneedcollect) {
		this.isneedcollect = isneedcollect;
	}

	public Byte getIssubmitcheck() {
		return this.issubmitcheck;
	}

	public void setIssubmitcheck(Byte issubmitcheck) {
		this.issubmitcheck = issubmitcheck;
	}

	public String getCheckpic() {
		return this.checkpic;
	}

	public void setCheckpic(String checkpic) {
		this.checkpic = checkpic;
	}

	public String getUom() {
		return this.uom;
	}

	public void setUom(String uom) {
		this.uom = uom;
	}

	public BigDecimal getOpuid() {
		return this.opuid;
	}

	public void setOpuid(BigDecimal opuid) {
		this.opuid = opuid;
	}

	public String getDmistollabel() {
		return this.dmistollabel;
	}

	public void setDmistollabel(String dmistollabel) {
		this.dmistollabel = dmistollabel;
	}

	public String getDmisfeatlabel() {
		return this.dmisfeatlabel;
	}

	public void setDmisfeatlabel(String dmisfeatlabel) {
		this.dmisfeatlabel = dmisfeatlabel;
	}

	public BigDecimal getManufactureopuid() {
		return this.manufactureopuid;
	}

	public void setManufactureopuid(BigDecimal manufactureopuid) {
		this.manufactureopuid = manufactureopuid;
	}

	public String getDmisfileversion() {
		return this.dmisfileversion;
	}

	public void setDmisfileversion(String dmisfileversion) {
		this.dmisfileversion = dmisfileversion;
	}

	public BigDecimal getOperationcheckorder() {
		return this.operationcheckorder;
	}

	public void setOperationcheckorder(BigDecimal operationcheckorder) {
		this.operationcheckorder = operationcheckorder;
	}

	public String getBarcode() {
		return this.barcode;
	}

	public void setBarcode(String barcode) {
		this.barcode = barcode;
	}

	public String getDeviation() {
		return this.deviation;
	}

	public void setDeviation(String deviation) {
		this.deviation = deviation;
	}

	public String getCheckresult() {
		return this.checkresult;
	}

	public void setCheckresult(String checkresult) {
		this.checkresult = checkresult;
	}

	public String getDefectdesc() {
		return this.defectdesc;
	}

	public void setDefectdesc(String defectdesc) {
		this.defectdesc = defectdesc;
	}

	public String getChecker1() {
		return this.checker1;
	}

	public void setChecker1(String checker1) {
		this.checker1 = checker1;
	}

	public Date getChecktime1() {
		return this.checktime1;
	}

	public void setChecktime1(Date checktime1) {
		this.checktime1 = checktime1;
	}

	public String getChecker2() {
		return this.checker2;
	}

	public void setChecker2(String checker2) {
		this.checker2 = checker2;
	}

	public Date getChecktime2() {
		return this.checktime2;
	}

	public void setChecktime2(Date checktime2) {
		this.checktime2 = checktime2;
	}

	public String getActualsize1() {
		return this.actualsize1;
	}

	public void setActualsize1(String actualsize1) {
		this.actualsize1 = actualsize1;
	}

	public String getActualsize2() {
		return this.actualsize2;
	}

	public void setActualsize2(String actualsize2) {
		this.actualsize2 = actualsize2;
	}

	public String getTooluid1() {
		return this.tooluid1;
	}

	public void setTooluid1(String tooluid1) {
		this.tooluid1 = tooluid1;
	}

	public String getTooluid2() {
		return this.tooluid2;
	}

	public void setTooluid2(String tooluid2) {
		this.tooluid2 = tooluid2;
	}

}
