package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

/**
 * MmaLagdaysPrepare generated by hbm2java
 */
public class MmaLagdaysPrepare implements java.io.Serializable {

	private MmaLagdaysPrepareId id;

	public MmaLagdaysPrepare() {
	}

	public MmaLagdaysPrepare(MmaLagdaysPrepareId id) {
		this.id = id;
	}

	public MmaLagdaysPrepareId getId() {
		return this.id;
	}

	public void setId(MmaLagdaysPrepareId id) {
		this.id = id;
	}

}
