package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MRejectheader generated by hbm2java
 */
public class MRejectheader implements java.io.Serializable {

	private String rejectuid;
	private String version;
	private MDefectjudgeheader MDefectjudgeheader;
	private Date createtime;
	private String creator;
	private String rejectid;
	private String taskuid;
	private String dutier;
	private BigDecimal rejectqty;
	private String checkmanager;
	private String dutydeptmanager;
	private BigDecimal wastehour;
	private BigDecimal wastematerialmoney;
	private BigDecimal wasteworkmoney;
	private String dutydeptid;
	private String customerid;
	private String defectreason;
	private String notes;
	private String checker;
	private Long rejectstate;
	private Long isinbulk;
	private String deptid;
	private String attatchref;
	private Date checktime;
	private String segementmanager;
	private String checkerprint;
	private Long isineffect;
	private Long approvestate;
	private String approveperson;
	private String billnumber;
	private String materialusn;
	private BigDecimal qtyappearance;
	private BigDecimal qtydimension;
	private String text1;
	private Set MRejectdetails = new HashSet(0);

	public MRejectheader() {
	}

	public MRejectheader(String rejectuid, String rejectid, String billnumber) {
		this.rejectuid = rejectuid;
		this.rejectid = rejectid;
		this.billnumber = billnumber;
	}

	public MRejectheader(String rejectuid, MDefectjudgeheader MDefectjudgeheader, Date createtime, String creator,
			String rejectid, String taskuid, String dutier, BigDecimal rejectqty, String checkmanager,
			String dutydeptmanager, BigDecimal wastehour, BigDecimal wastematerialmoney, BigDecimal wasteworkmoney,
			String dutydeptid, String customerid, String defectreason, String notes, String checker, Long rejectstate,
			Long isinbulk, String deptid, String attatchref, Date checktime, String segementmanager,
			String checkerprint, Long isineffect, Long approvestate, String approveperson, String billnumber,
			String materialusn, BigDecimal qtyappearance, BigDecimal qtydimension, String text1, Set MRejectdetails) {
		this.rejectuid = rejectuid;
		this.MDefectjudgeheader = MDefectjudgeheader;
		this.createtime = createtime;
		this.creator = creator;
		this.rejectid = rejectid;
		this.taskuid = taskuid;
		this.dutier = dutier;
		this.rejectqty = rejectqty;
		this.checkmanager = checkmanager;
		this.dutydeptmanager = dutydeptmanager;
		this.wastehour = wastehour;
		this.wastematerialmoney = wastematerialmoney;
		this.wasteworkmoney = wasteworkmoney;
		this.dutydeptid = dutydeptid;
		this.customerid = customerid;
		this.defectreason = defectreason;
		this.notes = notes;
		this.checker = checker;
		this.rejectstate = rejectstate;
		this.isinbulk = isinbulk;
		this.deptid = deptid;
		this.attatchref = attatchref;
		this.checktime = checktime;
		this.segementmanager = segementmanager;
		this.checkerprint = checkerprint;
		this.isineffect = isineffect;
		this.approvestate = approvestate;
		this.approveperson = approveperson;
		this.billnumber = billnumber;
		this.materialusn = materialusn;
		this.qtyappearance = qtyappearance;
		this.qtydimension = qtydimension;
		this.text1 = text1;
		this.MRejectdetails = MRejectdetails;
	}

	public String getRejectuid() {
		return this.rejectuid;
	}

	public void setRejectuid(String rejectuid) {
		this.rejectuid = rejectuid;
	}

	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public MDefectjudgeheader getMDefectjudgeheader() {
		return this.MDefectjudgeheader;
	}

	public void setMDefectjudgeheader(MDefectjudgeheader MDefectjudgeheader) {
		this.MDefectjudgeheader = MDefectjudgeheader;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public String getRejectid() {
		return this.rejectid;
	}

	public void setRejectid(String rejectid) {
		this.rejectid = rejectid;
	}

	public String getTaskuid() {
		return this.taskuid;
	}

	public void setTaskuid(String taskuid) {
		this.taskuid = taskuid;
	}

	public String getDutier() {
		return this.dutier;
	}

	public void setDutier(String dutier) {
		this.dutier = dutier;
	}

	public BigDecimal getRejectqty() {
		return this.rejectqty;
	}

	public void setRejectqty(BigDecimal rejectqty) {
		this.rejectqty = rejectqty;
	}

	public String getCheckmanager() {
		return this.checkmanager;
	}

	public void setCheckmanager(String checkmanager) {
		this.checkmanager = checkmanager;
	}

	public String getDutydeptmanager() {
		return this.dutydeptmanager;
	}

	public void setDutydeptmanager(String dutydeptmanager) {
		this.dutydeptmanager = dutydeptmanager;
	}

	public BigDecimal getWastehour() {
		return this.wastehour;
	}

	public void setWastehour(BigDecimal wastehour) {
		this.wastehour = wastehour;
	}

	public BigDecimal getWastematerialmoney() {
		return this.wastematerialmoney;
	}

	public void setWastematerialmoney(BigDecimal wastematerialmoney) {
		this.wastematerialmoney = wastematerialmoney;
	}

	public BigDecimal getWasteworkmoney() {
		return this.wasteworkmoney;
	}

	public void setWasteworkmoney(BigDecimal wasteworkmoney) {
		this.wasteworkmoney = wasteworkmoney;
	}

	public String getDutydeptid() {
		return this.dutydeptid;
	}

	public void setDutydeptid(String dutydeptid) {
		this.dutydeptid = dutydeptid;
	}

	public String getCustomerid() {
		return this.customerid;
	}

	public void setCustomerid(String customerid) {
		this.customerid = customerid;
	}

	public String getDefectreason() {
		return this.defectreason;
	}

	public void setDefectreason(String defectreason) {
		this.defectreason = defectreason;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getChecker() {
		return this.checker;
	}

	public void setChecker(String checker) {
		this.checker = checker;
	}

	public Long getRejectstate() {
		return this.rejectstate;
	}

	public void setRejectstate(Long rejectstate) {
		this.rejectstate = rejectstate;
	}

	public Long getIsinbulk() {
		return this.isinbulk;
	}

	public void setIsinbulk(Long isinbulk) {
		this.isinbulk = isinbulk;
	}

	public String getDeptid() {
		return this.deptid;
	}

	public void setDeptid(String deptid) {
		this.deptid = deptid;
	}

	public String getAttatchref() {
		return this.attatchref;
	}

	public void setAttatchref(String attatchref) {
		this.attatchref = attatchref;
	}

	public Date getChecktime() {
		return this.checktime;
	}

	public void setChecktime(Date checktime) {
		this.checktime = checktime;
	}

	public String getSegementmanager() {
		return this.segementmanager;
	}

	public void setSegementmanager(String segementmanager) {
		this.segementmanager = segementmanager;
	}

	public String getCheckerprint() {
		return this.checkerprint;
	}

	public void setCheckerprint(String checkerprint) {
		this.checkerprint = checkerprint;
	}

	public Long getIsineffect() {
		return this.isineffect;
	}

	public void setIsineffect(Long isineffect) {
		this.isineffect = isineffect;
	}

	public Long getApprovestate() {
		return this.approvestate;
	}

	public void setApprovestate(Long approvestate) {
		this.approvestate = approvestate;
	}

	public String getApproveperson() {
		return this.approveperson;
	}

	public void setApproveperson(String approveperson) {
		this.approveperson = approveperson;
	}

	public String getBillnumber() {
		return this.billnumber;
	}

	public void setBillnumber(String billnumber) {
		this.billnumber = billnumber;
	}

	public String getMaterialusn() {
		return this.materialusn;
	}

	public void setMaterialusn(String materialusn) {
		this.materialusn = materialusn;
	}

	public BigDecimal getQtyappearance() {
		return this.qtyappearance;
	}

	public void setQtyappearance(BigDecimal qtyappearance) {
		this.qtyappearance = qtyappearance;
	}

	public BigDecimal getQtydimension() {
		return this.qtydimension;
	}

	public void setQtydimension(BigDecimal qtydimension) {
		this.qtydimension = qtydimension;
	}

	public String getText1() {
		return this.text1;
	}

	public void setText1(String text1) {
		this.text1 = text1;
	}

	public Set getMRejectdetails() {
		return this.MRejectdetails;
	}

	public void setMRejectdetails(Set MRejectdetails) {
		this.MRejectdetails = MRejectdetails;
	}

}
