package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

/**
 * MsdevTrialView generated by hbm2java
 */
public class MsdevTrialView implements java.io.Serializable {

	private String tableName;

	public MsdevTrialView() {
	}

	public MsdevTrialView(String tableName) {
		this.tableName = tableName;
	}

	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

}
