package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * MvQualityId generated by hbm2java
 */
public class MvQualityId implements java.io.Serializable {

	private String deptno;
	private String deptid;
	private Date splydate;
	private String prtlotno;
	private String lotno;
	private BigDecimal chkoutqty;
	private String itemno;
	private String prtno;
	private String workid1;
	private String material;
	private String materialid;
	private String prntno;
	private String overcode;
	private String washer;
	private String washname;
	private String extdate;
	private String maintenancer;
	private String oilname;
	private String extrckdate;
	private String checkercode;
	private String employeeid;
	private String chkname;
	private String customerchecker;
	private Byte armycheckqc;

	public MvQualityId() {
	}

	public MvQualityId(String prtno, String workid1, String employeeid, String chkname) {
		this.prtno = prtno;
		this.workid1 = workid1;
		this.employeeid = employeeid;
		this.chkname = chkname;
	}

	public MvQualityId(String deptno, String deptid, Date splydate, String prtlotno, String lotno, BigDecimal chkoutqty,
			String itemno, String prtno, String workid1, String material, String materialid, String prntno,
			String overcode, String washer, String washname, String extdate, String maintenancer, String oilname,
			String extrckdate, String checkercode, String employeeid, String chkname, String customerchecker,
			Byte armycheckqc) {
		this.deptno = deptno;
		this.deptid = deptid;
		this.splydate = splydate;
		this.prtlotno = prtlotno;
		this.lotno = lotno;
		this.chkoutqty = chkoutqty;
		this.itemno = itemno;
		this.prtno = prtno;
		this.workid1 = workid1;
		this.material = material;
		this.materialid = materialid;
		this.prntno = prntno;
		this.overcode = overcode;
		this.washer = washer;
		this.washname = washname;
		this.extdate = extdate;
		this.maintenancer = maintenancer;
		this.oilname = oilname;
		this.extrckdate = extrckdate;
		this.checkercode = checkercode;
		this.employeeid = employeeid;
		this.chkname = chkname;
		this.customerchecker = customerchecker;
		this.armycheckqc = armycheckqc;
	}

	public String getDeptno() {
		return this.deptno;
	}

	public void setDeptno(String deptno) {
		this.deptno = deptno;
	}

	public String getDeptid() {
		return this.deptid;
	}

	public void setDeptid(String deptid) {
		this.deptid = deptid;
	}

	public Date getSplydate() {
		return this.splydate;
	}

	public void setSplydate(Date splydate) {
		this.splydate = splydate;
	}

	public String getPrtlotno() {
		return this.prtlotno;
	}

	public void setPrtlotno(String prtlotno) {
		this.prtlotno = prtlotno;
	}

	public String getLotno() {
		return this.lotno;
	}

	public void setLotno(String lotno) {
		this.lotno = lotno;
	}

	public BigDecimal getChkoutqty() {
		return this.chkoutqty;
	}

	public void setChkoutqty(BigDecimal chkoutqty) {
		this.chkoutqty = chkoutqty;
	}

	public String getItemno() {
		return this.itemno;
	}

	public void setItemno(String itemno) {
		this.itemno = itemno;
	}

	public String getPrtno() {
		return this.prtno;
	}

	public void setPrtno(String prtno) {
		this.prtno = prtno;
	}

	public String getWorkid1() {
		return this.workid1;
	}

	public void setWorkid1(String workid1) {
		this.workid1 = workid1;
	}

	public String getMaterial() {
		return this.material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

	public String getMaterialid() {
		return this.materialid;
	}

	public void setMaterialid(String materialid) {
		this.materialid = materialid;
	}

	public String getPrntno() {
		return this.prntno;
	}

	public void setPrntno(String prntno) {
		this.prntno = prntno;
	}

	public String getOvercode() {
		return this.overcode;
	}

	public void setOvercode(String overcode) {
		this.overcode = overcode;
	}

	public String getWasher() {
		return this.washer;
	}

	public void setWasher(String washer) {
		this.washer = washer;
	}

	public String getWashname() {
		return this.washname;
	}

	public void setWashname(String washname) {
		this.washname = washname;
	}

	public String getExtdate() {
		return this.extdate;
	}

	public void setExtdate(String extdate) {
		this.extdate = extdate;
	}

	public String getMaintenancer() {
		return this.maintenancer;
	}

	public void setMaintenancer(String maintenancer) {
		this.maintenancer = maintenancer;
	}

	public String getOilname() {
		return this.oilname;
	}

	public void setOilname(String oilname) {
		this.oilname = oilname;
	}

	public String getExtrckdate() {
		return this.extrckdate;
	}

	public void setExtrckdate(String extrckdate) {
		this.extrckdate = extrckdate;
	}

	public String getCheckercode() {
		return this.checkercode;
	}

	public void setCheckercode(String checkercode) {
		this.checkercode = checkercode;
	}

	public String getEmployeeid() {
		return this.employeeid;
	}

	public void setEmployeeid(String employeeid) {
		this.employeeid = employeeid;
	}

	public String getChkname() {
		return this.chkname;
	}

	public void setChkname(String chkname) {
		this.chkname = chkname;
	}

	public String getCustomerchecker() {
		return this.customerchecker;
	}

	public void setCustomerchecker(String customerchecker) {
		this.customerchecker = customerchecker;
	}

	public Byte getArmycheckqc() {
		return this.armycheckqc;
	}

	public void setArmycheckqc(Byte armycheckqc) {
		this.armycheckqc = armycheckqc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MvQualityId))
			return false;
		MvQualityId castOther = (MvQualityId) other;

		return ((this.getDeptno() == castOther.getDeptno()) || (this.getDeptno() != null
				&& castOther.getDeptno() != null && this.getDeptno().equals(castOther.getDeptno())))
				&& ((this.getDeptid() == castOther.getDeptid()) || (this.getDeptid() != null
						&& castOther.getDeptid() != null && this.getDeptid().equals(castOther.getDeptid())))
				&& ((this.getSplydate() == castOther.getSplydate()) || (this.getSplydate() != null
						&& castOther.getSplydate() != null && this.getSplydate().equals(castOther.getSplydate())))
				&& ((this.getPrtlotno() == castOther.getPrtlotno()) || (this.getPrtlotno() != null
						&& castOther.getPrtlotno() != null && this.getPrtlotno().equals(castOther.getPrtlotno())))
				&& ((this.getLotno() == castOther.getLotno()) || (this.getLotno() != null
						&& castOther.getLotno() != null && this.getLotno().equals(castOther.getLotno())))
				&& ((this.getChkoutqty() == castOther.getChkoutqty()) || (this.getChkoutqty() != null
						&& castOther.getChkoutqty() != null && this.getChkoutqty().equals(castOther.getChkoutqty())))
				&& ((this.getItemno() == castOther.getItemno()) || (this.getItemno() != null
						&& castOther.getItemno() != null && this.getItemno().equals(castOther.getItemno())))
				&& ((this.getPrtno() == castOther.getPrtno()) || (this.getPrtno() != null
						&& castOther.getPrtno() != null && this.getPrtno().equals(castOther.getPrtno())))
				&& ((this.getWorkid1() == castOther.getWorkid1()) || (this.getWorkid1() != null
						&& castOther.getWorkid1() != null && this.getWorkid1().equals(castOther.getWorkid1())))
				&& ((this.getMaterial() == castOther.getMaterial()) || (this.getMaterial() != null
						&& castOther.getMaterial() != null && this.getMaterial().equals(castOther.getMaterial())))
				&& ((this.getMaterialid() == castOther.getMaterialid()) || (this.getMaterialid() != null
						&& castOther.getMaterialid() != null && this.getMaterialid().equals(castOther.getMaterialid())))
				&& ((this.getPrntno() == castOther.getPrntno()) || (this.getPrntno() != null
						&& castOther.getPrntno() != null && this.getPrntno().equals(castOther.getPrntno())))
				&& ((this.getOvercode() == castOther.getOvercode()) || (this.getOvercode() != null
						&& castOther.getOvercode() != null && this.getOvercode().equals(castOther.getOvercode())))
				&& ((this.getWasher() == castOther.getWasher()) || (this.getWasher() != null
						&& castOther.getWasher() != null && this.getWasher().equals(castOther.getWasher())))
				&& ((this.getWashname() == castOther.getWashname()) || (this.getWashname() != null
						&& castOther.getWashname() != null && this.getWashname().equals(castOther.getWashname())))
				&& ((this.getExtdate() == castOther.getExtdate()) || (this.getExtdate() != null
						&& castOther.getExtdate() != null && this.getExtdate().equals(castOther.getExtdate())))
				&& ((this.getMaintenancer() == castOther.getMaintenancer())
						|| (this.getMaintenancer() != null && castOther.getMaintenancer() != null
								&& this.getMaintenancer().equals(castOther.getMaintenancer())))
				&& ((this.getOilname() == castOther.getOilname()) || (this.getOilname() != null
						&& castOther.getOilname() != null && this.getOilname().equals(castOther.getOilname())))
				&& ((this.getExtrckdate() == castOther.getExtrckdate()) || (this.getExtrckdate() != null
						&& castOther.getExtrckdate() != null && this.getExtrckdate().equals(castOther.getExtrckdate())))
				&& ((this.getCheckercode() == castOther.getCheckercode())
						|| (this.getCheckercode() != null && castOther.getCheckercode() != null
								&& this.getCheckercode().equals(castOther.getCheckercode())))
				&& ((this.getEmployeeid() == castOther.getEmployeeid()) || (this.getEmployeeid() != null
						&& castOther.getEmployeeid() != null && this.getEmployeeid().equals(castOther.getEmployeeid())))
				&& ((this.getChkname() == castOther.getChkname()) || (this.getChkname() != null
						&& castOther.getChkname() != null && this.getChkname().equals(castOther.getChkname())))
				&& ((this.getCustomerchecker() == castOther.getCustomerchecker())
						|| (this.getCustomerchecker() != null && castOther.getCustomerchecker() != null
								&& this.getCustomerchecker().equals(castOther.getCustomerchecker())))
				&& ((this.getArmycheckqc() == castOther.getArmycheckqc())
						|| (this.getArmycheckqc() != null && castOther.getArmycheckqc() != null
								&& this.getArmycheckqc().equals(castOther.getArmycheckqc())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDeptno() == null ? 0 : this.getDeptno().hashCode());
		result = 37 * result + (getDeptid() == null ? 0 : this.getDeptid().hashCode());
		result = 37 * result + (getSplydate() == null ? 0 : this.getSplydate().hashCode());
		result = 37 * result + (getPrtlotno() == null ? 0 : this.getPrtlotno().hashCode());
		result = 37 * result + (getLotno() == null ? 0 : this.getLotno().hashCode());
		result = 37 * result + (getChkoutqty() == null ? 0 : this.getChkoutqty().hashCode());
		result = 37 * result + (getItemno() == null ? 0 : this.getItemno().hashCode());
		result = 37 * result + (getPrtno() == null ? 0 : this.getPrtno().hashCode());
		result = 37 * result + (getWorkid1() == null ? 0 : this.getWorkid1().hashCode());
		result = 37 * result + (getMaterial() == null ? 0 : this.getMaterial().hashCode());
		result = 37 * result + (getMaterialid() == null ? 0 : this.getMaterialid().hashCode());
		result = 37 * result + (getPrntno() == null ? 0 : this.getPrntno().hashCode());
		result = 37 * result + (getOvercode() == null ? 0 : this.getOvercode().hashCode());
		result = 37 * result + (getWasher() == null ? 0 : this.getWasher().hashCode());
		result = 37 * result + (getWashname() == null ? 0 : this.getWashname().hashCode());
		result = 37 * result + (getExtdate() == null ? 0 : this.getExtdate().hashCode());
		result = 37 * result + (getMaintenancer() == null ? 0 : this.getMaintenancer().hashCode());
		result = 37 * result + (getOilname() == null ? 0 : this.getOilname().hashCode());
		result = 37 * result + (getExtrckdate() == null ? 0 : this.getExtrckdate().hashCode());
		result = 37 * result + (getCheckercode() == null ? 0 : this.getCheckercode().hashCode());
		result = 37 * result + (getEmployeeid() == null ? 0 : this.getEmployeeid().hashCode());
		result = 37 * result + (getChkname() == null ? 0 : this.getChkname().hashCode());
		result = 37 * result + (getCustomerchecker() == null ? 0 : this.getCustomerchecker().hashCode());
		result = 37 * result + (getArmycheckqc() == null ? 0 : this.getArmycheckqc().hashCode());
		return result;
	}

}
