package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

/**
 * REmployeeWork generated by hbm2java
 */
public class REmployeeWork implements java.io.Serializable {

	private REmployeeWorkId id;

	public REmployeeWork() {
	}

	public REmployeeWork(REmployeeWorkId id) {
		this.id = id;
	}

	public REmployeeWorkId getId() {
		return this.id;
	}

	public void setId(REmployeeWorkId id) {
		this.id = id;
	}

}
