package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * RResworkId generated by hbm2java
 */
public class RResworkId implements java.io.Serializable {

	private BigDecimal uniqueid;
	private String resuid;
	private String employeeid;
	private Date workdate;
	private BigDecimal time1;
	private BigDecimal time2;
	private BigDecimal time3;
	private BigDecimal time4;
	private BigDecimal time5;
	private BigDecimal time6;
	private BigDecimal time7;
	private BigDecimal time8;
	private BigDecimal time9;
	private BigDecimal time10;
	private BigDecimal time11;
	private BigDecimal time12;
	private String note;
	private BigDecimal time13;
	private Date createtime;
	private String workrecuid;

	public RResworkId() {
	}

	public RResworkId(BigDecimal uniqueid, String employeeid, Date workdate) {
		this.uniqueid = uniqueid;
		this.employeeid = employeeid;
		this.workdate = workdate;
	}

	public RResworkId(BigDecimal uniqueid, String resuid, String employeeid, Date workdate, BigDecimal time1,
			BigDecimal time2, BigDecimal time3, BigDecimal time4, BigDecimal time5, BigDecimal time6, BigDecimal time7,
			BigDecimal time8, BigDecimal time9, BigDecimal time10, BigDecimal time11, BigDecimal time12, String note,
			BigDecimal time13, Date createtime, String workrecuid) {
		this.uniqueid = uniqueid;
		this.resuid = resuid;
		this.employeeid = employeeid;
		this.workdate = workdate;
		this.time1 = time1;
		this.time2 = time2;
		this.time3 = time3;
		this.time4 = time4;
		this.time5 = time5;
		this.time6 = time6;
		this.time7 = time7;
		this.time8 = time8;
		this.time9 = time9;
		this.time10 = time10;
		this.time11 = time11;
		this.time12 = time12;
		this.note = note;
		this.time13 = time13;
		this.createtime = createtime;
		this.workrecuid = workrecuid;
	}

	public BigDecimal getUniqueid() {
		return this.uniqueid;
	}

	public void setUniqueid(BigDecimal uniqueid) {
		this.uniqueid = uniqueid;
	}

	public String getResuid() {
		return this.resuid;
	}

	public void setResuid(String resuid) {
		this.resuid = resuid;
	}

	public String getEmployeeid() {
		return this.employeeid;
	}

	public void setEmployeeid(String employeeid) {
		this.employeeid = employeeid;
	}

	public Date getWorkdate() {
		return this.workdate;
	}

	public void setWorkdate(Date workdate) {
		this.workdate = workdate;
	}

	public BigDecimal getTime1() {
		return this.time1;
	}

	public void setTime1(BigDecimal time1) {
		this.time1 = time1;
	}

	public BigDecimal getTime2() {
		return this.time2;
	}

	public void setTime2(BigDecimal time2) {
		this.time2 = time2;
	}

	public BigDecimal getTime3() {
		return this.time3;
	}

	public void setTime3(BigDecimal time3) {
		this.time3 = time3;
	}

	public BigDecimal getTime4() {
		return this.time4;
	}

	public void setTime4(BigDecimal time4) {
		this.time4 = time4;
	}

	public BigDecimal getTime5() {
		return this.time5;
	}

	public void setTime5(BigDecimal time5) {
		this.time5 = time5;
	}

	public BigDecimal getTime6() {
		return this.time6;
	}

	public void setTime6(BigDecimal time6) {
		this.time6 = time6;
	}

	public BigDecimal getTime7() {
		return this.time7;
	}

	public void setTime7(BigDecimal time7) {
		this.time7 = time7;
	}

	public BigDecimal getTime8() {
		return this.time8;
	}

	public void setTime8(BigDecimal time8) {
		this.time8 = time8;
	}

	public BigDecimal getTime9() {
		return this.time9;
	}

	public void setTime9(BigDecimal time9) {
		this.time9 = time9;
	}

	public BigDecimal getTime10() {
		return this.time10;
	}

	public void setTime10(BigDecimal time10) {
		this.time10 = time10;
	}

	public BigDecimal getTime11() {
		return this.time11;
	}

	public void setTime11(BigDecimal time11) {
		this.time11 = time11;
	}

	public BigDecimal getTime12() {
		return this.time12;
	}

	public void setTime12(BigDecimal time12) {
		this.time12 = time12;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public BigDecimal getTime13() {
		return this.time13;
	}

	public void setTime13(BigDecimal time13) {
		this.time13 = time13;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getWorkrecuid() {
		return this.workrecuid;
	}

	public void setWorkrecuid(String workrecuid) {
		this.workrecuid = workrecuid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RResworkId))
			return false;
		RResworkId castOther = (RResworkId) other;

		return ((this.getUniqueid() == castOther.getUniqueid()) || (this.getUniqueid() != null
				&& castOther.getUniqueid() != null && this.getUniqueid().equals(castOther.getUniqueid())))
				&& ((this.getResuid() == castOther.getResuid()) || (this.getResuid() != null
						&& castOther.getResuid() != null && this.getResuid().equals(castOther.getResuid())))
				&& ((this.getEmployeeid() == castOther.getEmployeeid()) || (this.getEmployeeid() != null
						&& castOther.getEmployeeid() != null && this.getEmployeeid().equals(castOther.getEmployeeid())))
				&& ((this.getWorkdate() == castOther.getWorkdate()) || (this.getWorkdate() != null
						&& castOther.getWorkdate() != null && this.getWorkdate().equals(castOther.getWorkdate())))
				&& ((this.getTime1() == castOther.getTime1()) || (this.getTime1() != null
						&& castOther.getTime1() != null && this.getTime1().equals(castOther.getTime1())))
				&& ((this.getTime2() == castOther.getTime2()) || (this.getTime2() != null
						&& castOther.getTime2() != null && this.getTime2().equals(castOther.getTime2())))
				&& ((this.getTime3() == castOther.getTime3()) || (this.getTime3() != null
						&& castOther.getTime3() != null && this.getTime3().equals(castOther.getTime3())))
				&& ((this.getTime4() == castOther.getTime4()) || (this.getTime4() != null
						&& castOther.getTime4() != null && this.getTime4().equals(castOther.getTime4())))
				&& ((this.getTime5() == castOther.getTime5()) || (this.getTime5() != null
						&& castOther.getTime5() != null && this.getTime5().equals(castOther.getTime5())))
				&& ((this.getTime6() == castOther.getTime6()) || (this.getTime6() != null
						&& castOther.getTime6() != null && this.getTime6().equals(castOther.getTime6())))
				&& ((this.getTime7() == castOther.getTime7()) || (this.getTime7() != null
						&& castOther.getTime7() != null && this.getTime7().equals(castOther.getTime7())))
				&& ((this.getTime8() == castOther.getTime8()) || (this.getTime8() != null
						&& castOther.getTime8() != null && this.getTime8().equals(castOther.getTime8())))
				&& ((this.getTime9() == castOther.getTime9()) || (this.getTime9() != null
						&& castOther.getTime9() != null && this.getTime9().equals(castOther.getTime9())))
				&& ((this.getTime10() == castOther.getTime10()) || (this.getTime10() != null
						&& castOther.getTime10() != null && this.getTime10().equals(castOther.getTime10())))
				&& ((this.getTime11() == castOther.getTime11()) || (this.getTime11() != null
						&& castOther.getTime11() != null && this.getTime11().equals(castOther.getTime11())))
				&& ((this.getTime12() == castOther.getTime12()) || (this.getTime12() != null
						&& castOther.getTime12() != null && this.getTime12().equals(castOther.getTime12())))
				&& ((this.getNote() == castOther.getNote()) || (this.getNote() != null && castOther.getNote() != null
						&& this.getNote().equals(castOther.getNote())))
				&& ((this.getTime13() == castOther.getTime13()) || (this.getTime13() != null
						&& castOther.getTime13() != null && this.getTime13().equals(castOther.getTime13())))
				&& ((this.getCreatetime() == castOther.getCreatetime()) || (this.getCreatetime() != null
						&& castOther.getCreatetime() != null && this.getCreatetime().equals(castOther.getCreatetime())))
				&& ((this.getWorkrecuid() == castOther.getWorkrecuid())
						|| (this.getWorkrecuid() != null && castOther.getWorkrecuid() != null
								&& this.getWorkrecuid().equals(castOther.getWorkrecuid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUniqueid() == null ? 0 : this.getUniqueid().hashCode());
		result = 37 * result + (getResuid() == null ? 0 : this.getResuid().hashCode());
		result = 37 * result + (getEmployeeid() == null ? 0 : this.getEmployeeid().hashCode());
		result = 37 * result + (getWorkdate() == null ? 0 : this.getWorkdate().hashCode());
		result = 37 * result + (getTime1() == null ? 0 : this.getTime1().hashCode());
		result = 37 * result + (getTime2() == null ? 0 : this.getTime2().hashCode());
		result = 37 * result + (getTime3() == null ? 0 : this.getTime3().hashCode());
		result = 37 * result + (getTime4() == null ? 0 : this.getTime4().hashCode());
		result = 37 * result + (getTime5() == null ? 0 : this.getTime5().hashCode());
		result = 37 * result + (getTime6() == null ? 0 : this.getTime6().hashCode());
		result = 37 * result + (getTime7() == null ? 0 : this.getTime7().hashCode());
		result = 37 * result + (getTime8() == null ? 0 : this.getTime8().hashCode());
		result = 37 * result + (getTime9() == null ? 0 : this.getTime9().hashCode());
		result = 37 * result + (getTime10() == null ? 0 : this.getTime10().hashCode());
		result = 37 * result + (getTime11() == null ? 0 : this.getTime11().hashCode());
		result = 37 * result + (getTime12() == null ? 0 : this.getTime12().hashCode());
		result = 37 * result + (getNote() == null ? 0 : this.getNote().hashCode());
		result = 37 * result + (getTime13() == null ? 0 : this.getTime13().hashCode());
		result = 37 * result + (getCreatetime() == null ? 0 : this.getCreatetime().hashCode());
		result = 37 * result + (getWorkrecuid() == null ? 0 : this.getWorkrecuid().hashCode());
		return result;
	}

}
