package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

/**
 * RResourceLayout generated by hbm2java
 */
public class RResourceLayout implements java.io.Serializable {

	private RResourceLayoutId id;
	private Long width;
	private Long height;
	private String resuid;
	private String resname;
	private Long stateid;
	private String layouttype;
	private String areaid;
	private Long xnum;
	private Long ynum;

	public RResourceLayout() {
	}

	public RResourceLayout(RResourceLayoutId id) {
		this.id = id;
	}

	public RResourceLayout(RResourceLayoutId id, Long width, Long height, String resuid, String resname, Long stateid,
			String layouttype, String areaid, Long xnum, Long ynum) {
		this.id = id;
		this.width = width;
		this.height = height;
		this.resuid = resuid;
		this.resname = resname;
		this.stateid = stateid;
		this.layouttype = layouttype;
		this.areaid = areaid;
		this.xnum = xnum;
		this.ynum = ynum;
	}

	public RResourceLayoutId getId() {
		return this.id;
	}

	public void setId(RResourceLayoutId id) {
		this.id = id;
	}

	public Long getWidth() {
		return this.width;
	}

	public void setWidth(Long width) {
		this.width = width;
	}

	public Long getHeight() {
		return this.height;
	}

	public void setHeight(Long height) {
		this.height = height;
	}

	public String getResuid() {
		return this.resuid;
	}

	public void setResuid(String resuid) {
		this.resuid = resuid;
	}

	public String getResname() {
		return this.resname;
	}

	public void setResname(String resname) {
		this.resname = resname;
	}

	public Long getStateid() {
		return this.stateid;
	}

	public void setStateid(Long stateid) {
		this.stateid = stateid;
	}

	public String getLayouttype() {
		return this.layouttype;
	}

	public void setLayouttype(String layouttype) {
		this.layouttype = layouttype;
	}

	public String getAreaid() {
		return this.areaid;
	}

	public void setAreaid(String areaid) {
		this.areaid = areaid;
	}

	public Long getXnum() {
		return this.xnum;
	}

	public void setXnum(Long xnum) {
		this.xnum = xnum;
	}

	public Long getYnum() {
		return this.ynum;
	}

	public void setYnum(Long ynum) {
		this.ynum = ynum;
	}

}
