package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

/**
 * RRuleGroup generated by hbm2java
 */
public class RRuleGroup implements java.io.Serializable {

	private RRuleGroupId id;

	public RRuleGroup() {
	}

	public RRuleGroup(RRuleGroupId id) {
		this.id = id;
	}

	public RRuleGroupId getId() {
		return this.id;
	}

	public void setId(RRuleGroupId id) {
		this.id = id;
	}

}
