package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

/**
 * RSupplierManager generated by hbm2java
 */
public class RSupplierManager implements java.io.Serializable {

	private RSupplierManagerId id;

	public RSupplierManager() {
	}

	public RSupplierManager(RSupplierManagerId id) {
		this.id = id;
	}

	public RSupplierManagerId getId() {
		return this.id;
	}

	public void setId(RSupplierManagerId id) {
		this.id = id;
	}

}
