package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * RvDeptId generated by hbm2java
 */
public class RvDeptId implements java.io.Serializable {

	private String deptid;
	private String leaderid;
	private String deptname;
	private String contactid;
	private String creatorid;
	private BigDecimal depttype;
	private Date createtime;
	private String superdeptid;
	private String notes;
	private String schemaid;
	private String customerDeptid;
	private String RDeptOutUid;
	private String deptLevel;
	private String deptTreeCode;
	private String leadername;
	private String contactname;
	private String creatorname;
	private String depttypedesc;
	private String superdeptname;

	public RvDeptId() {
	}

	public RvDeptId(String deptid) {
		this.deptid = deptid;
	}

	public RvDeptId(String deptid, String leaderid, String deptname, String contactid, String creatorid,
			BigDecimal depttype, Date createtime, String superdeptid, String notes, String schemaid,
			String customerDeptid, String RDeptOutUid, String deptLevel, String deptTreeCode, String leadername,
			String contactname, String creatorname, String depttypedesc, String superdeptname) {
		this.deptid = deptid;
		this.leaderid = leaderid;
		this.deptname = deptname;
		this.contactid = contactid;
		this.creatorid = creatorid;
		this.depttype = depttype;
		this.createtime = createtime;
		this.superdeptid = superdeptid;
		this.notes = notes;
		this.schemaid = schemaid;
		this.customerDeptid = customerDeptid;
		this.RDeptOutUid = RDeptOutUid;
		this.deptLevel = deptLevel;
		this.deptTreeCode = deptTreeCode;
		this.leadername = leadername;
		this.contactname = contactname;
		this.creatorname = creatorname;
		this.depttypedesc = depttypedesc;
		this.superdeptname = superdeptname;
	}

	public String getDeptid() {
		return this.deptid;
	}

	public void setDeptid(String deptid) {
		this.deptid = deptid;
	}

	public String getLeaderid() {
		return this.leaderid;
	}

	public void setLeaderid(String leaderid) {
		this.leaderid = leaderid;
	}

	public String getDeptname() {
		return this.deptname;
	}

	public void setDeptname(String deptname) {
		this.deptname = deptname;
	}

	public String getContactid() {
		return this.contactid;
	}

	public void setContactid(String contactid) {
		this.contactid = contactid;
	}

	public String getCreatorid() {
		return this.creatorid;
	}

	public void setCreatorid(String creatorid) {
		this.creatorid = creatorid;
	}

	public BigDecimal getDepttype() {
		return this.depttype;
	}

	public void setDepttype(BigDecimal depttype) {
		this.depttype = depttype;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getSuperdeptid() {
		return this.superdeptid;
	}

	public void setSuperdeptid(String superdeptid) {
		this.superdeptid = superdeptid;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getSchemaid() {
		return this.schemaid;
	}

	public void setSchemaid(String schemaid) {
		this.schemaid = schemaid;
	}

	public String getCustomerDeptid() {
		return this.customerDeptid;
	}

	public void setCustomerDeptid(String customerDeptid) {
		this.customerDeptid = customerDeptid;
	}

	public String getRDeptOutUid() {
		return this.RDeptOutUid;
	}

	public void setRDeptOutUid(String RDeptOutUid) {
		this.RDeptOutUid = RDeptOutUid;
	}

	public String getDeptLevel() {
		return this.deptLevel;
	}

	public void setDeptLevel(String deptLevel) {
		this.deptLevel = deptLevel;
	}

	public String getDeptTreeCode() {
		return this.deptTreeCode;
	}

	public void setDeptTreeCode(String deptTreeCode) {
		this.deptTreeCode = deptTreeCode;
	}

	public String getLeadername() {
		return this.leadername;
	}

	public void setLeadername(String leadername) {
		this.leadername = leadername;
	}

	public String getContactname() {
		return this.contactname;
	}

	public void setContactname(String contactname) {
		this.contactname = contactname;
	}

	public String getCreatorname() {
		return this.creatorname;
	}

	public void setCreatorname(String creatorname) {
		this.creatorname = creatorname;
	}

	public String getDepttypedesc() {
		return this.depttypedesc;
	}

	public void setDepttypedesc(String depttypedesc) {
		this.depttypedesc = depttypedesc;
	}

	public String getSuperdeptname() {
		return this.superdeptname;
	}

	public void setSuperdeptname(String superdeptname) {
		this.superdeptname = superdeptname;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RvDeptId))
			return false;
		RvDeptId castOther = (RvDeptId) other;

		return ((this.getDeptid() == castOther.getDeptid()) || (this.getDeptid() != null
				&& castOther.getDeptid() != null && this.getDeptid().equals(castOther.getDeptid())))
				&& ((this.getLeaderid() == castOther.getLeaderid()) || (this.getLeaderid() != null
						&& castOther.getLeaderid() != null && this.getLeaderid().equals(castOther.getLeaderid())))
				&& ((this.getDeptname() == castOther.getDeptname()) || (this.getDeptname() != null
						&& castOther.getDeptname() != null && this.getDeptname().equals(castOther.getDeptname())))
				&& ((this.getContactid() == castOther.getContactid()) || (this.getContactid() != null
						&& castOther.getContactid() != null && this.getContactid().equals(castOther.getContactid())))
				&& ((this.getCreatorid() == castOther.getCreatorid()) || (this.getCreatorid() != null
						&& castOther.getCreatorid() != null && this.getCreatorid().equals(castOther.getCreatorid())))
				&& ((this.getDepttype() == castOther.getDepttype()) || (this.getDepttype() != null
						&& castOther.getDepttype() != null && this.getDepttype().equals(castOther.getDepttype())))
				&& ((this.getCreatetime() == castOther.getCreatetime()) || (this.getCreatetime() != null
						&& castOther.getCreatetime() != null && this.getCreatetime().equals(castOther.getCreatetime())))
				&& ((this.getSuperdeptid() == castOther.getSuperdeptid())
						|| (this.getSuperdeptid() != null && castOther.getSuperdeptid() != null
								&& this.getSuperdeptid().equals(castOther.getSuperdeptid())))
				&& ((this.getNotes() == castOther.getNotes()) || (this.getNotes() != null
						&& castOther.getNotes() != null && this.getNotes().equals(castOther.getNotes())))
				&& ((this.getSchemaid() == castOther.getSchemaid()) || (this.getSchemaid() != null
						&& castOther.getSchemaid() != null && this.getSchemaid().equals(castOther.getSchemaid())))
				&& ((this.getCustomerDeptid() == castOther.getCustomerDeptid())
						|| (this.getCustomerDeptid() != null && castOther.getCustomerDeptid() != null
								&& this.getCustomerDeptid().equals(castOther.getCustomerDeptid())))
				&& ((this.getRDeptOutUid() == castOther.getRDeptOutUid())
						|| (this.getRDeptOutUid() != null && castOther.getRDeptOutUid() != null
								&& this.getRDeptOutUid().equals(castOther.getRDeptOutUid())))
				&& ((this.getDeptLevel() == castOther.getDeptLevel()) || (this.getDeptLevel() != null
						&& castOther.getDeptLevel() != null && this.getDeptLevel().equals(castOther.getDeptLevel())))
				&& ((this.getDeptTreeCode() == castOther.getDeptTreeCode())
						|| (this.getDeptTreeCode() != null && castOther.getDeptTreeCode() != null
								&& this.getDeptTreeCode().equals(castOther.getDeptTreeCode())))
				&& ((this.getLeadername() == castOther.getLeadername()) || (this.getLeadername() != null
						&& castOther.getLeadername() != null && this.getLeadername().equals(castOther.getLeadername())))
				&& ((this.getContactname() == castOther.getContactname())
						|| (this.getContactname() != null && castOther.getContactname() != null
								&& this.getContactname().equals(castOther.getContactname())))
				&& ((this.getCreatorname() == castOther.getCreatorname())
						|| (this.getCreatorname() != null && castOther.getCreatorname() != null
								&& this.getCreatorname().equals(castOther.getCreatorname())))
				&& ((this.getDepttypedesc() == castOther.getDepttypedesc())
						|| (this.getDepttypedesc() != null && castOther.getDepttypedesc() != null
								&& this.getDepttypedesc().equals(castOther.getDepttypedesc())))
				&& ((this.getSuperdeptname() == castOther.getSuperdeptname())
						|| (this.getSuperdeptname() != null && castOther.getSuperdeptname() != null
								&& this.getSuperdeptname().equals(castOther.getSuperdeptname())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDeptid() == null ? 0 : this.getDeptid().hashCode());
		result = 37 * result + (getLeaderid() == null ? 0 : this.getLeaderid().hashCode());
		result = 37 * result + (getDeptname() == null ? 0 : this.getDeptname().hashCode());
		result = 37 * result + (getContactid() == null ? 0 : this.getContactid().hashCode());
		result = 37 * result + (getCreatorid() == null ? 0 : this.getCreatorid().hashCode());
		result = 37 * result + (getDepttype() == null ? 0 : this.getDepttype().hashCode());
		result = 37 * result + (getCreatetime() == null ? 0 : this.getCreatetime().hashCode());
		result = 37 * result + (getSuperdeptid() == null ? 0 : this.getSuperdeptid().hashCode());
		result = 37 * result + (getNotes() == null ? 0 : this.getNotes().hashCode());
		result = 37 * result + (getSchemaid() == null ? 0 : this.getSchemaid().hashCode());
		result = 37 * result + (getCustomerDeptid() == null ? 0 : this.getCustomerDeptid().hashCode());
		result = 37 * result + (getRDeptOutUid() == null ? 0 : this.getRDeptOutUid().hashCode());
		result = 37 * result + (getDeptLevel() == null ? 0 : this.getDeptLevel().hashCode());
		result = 37 * result + (getDeptTreeCode() == null ? 0 : this.getDeptTreeCode().hashCode());
		result = 37 * result + (getLeadername() == null ? 0 : this.getLeadername().hashCode());
		result = 37 * result + (getContactname() == null ? 0 : this.getContactname().hashCode());
		result = 37 * result + (getCreatorname() == null ? 0 : this.getCreatorname().hashCode());
		result = 37 * result + (getDepttypedesc() == null ? 0 : this.getDepttypedesc().hashCode());
		result = 37 * result + (getSuperdeptname() == null ? 0 : this.getSuperdeptname().hashCode());
		return result;
	}

}
