package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

/**
 * SGroupRoleId generated by hbm2java
 */
public class SGroupRoleId implements java.io.Serializable {

	private String groupid;
	private String roleid;

	public SGroupRoleId() {
	}

	public SGroupRoleId(String groupid, String roleid) {
		this.groupid = groupid;
		this.roleid = roleid;
	}

	public String getGroupid() {
		return this.groupid;
	}

	public void setGroupid(String groupid) {
		this.groupid = groupid;
	}

	public String getRoleid() {
		return this.roleid;
	}

	public void setRoleid(String roleid) {
		this.roleid = roleid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SGroupRoleId))
			return false;
		SGroupRoleId castOther = (SGroupRoleId) other;

		return ((this.getGroupid() == castOther.getGroupid()) || (this.getGroupid() != null
				&& castOther.getGroupid() != null && this.getGroupid().equals(castOther.getGroupid())))
				&& ((this.getRoleid() == castOther.getRoleid()) || (this.getRoleid() != null
						&& castOther.getRoleid() != null && this.getRoleid().equals(castOther.getRoleid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getGroupid() == null ? 0 : this.getGroupid().hashCode());
		result = 37 * result + (getRoleid() == null ? 0 : this.getRoleid().hashCode());
		return result;
	}

}
