package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

/**
 * SMainXml generated by hbm2java
 */
public class SMainXml implements java.io.Serializable {

	private long xmlid;
	private String xmlname;
	private long mainid;
	private String xmlurl;
	private String company;
	private String notes;

	public SMainXml() {
	}

	public SMainXml(long xmlid, long mainid, String company) {
		this.xmlid = xmlid;
		this.mainid = mainid;
		this.company = company;
	}

	public SMainXml(long xmlid, String xmlname, long mainid, String xmlurl, String company, String notes) {
		this.xmlid = xmlid;
		this.xmlname = xmlname;
		this.mainid = mainid;
		this.xmlurl = xmlurl;
		this.company = company;
		this.notes = notes;
	}

	public long getXmlid() {
		return this.xmlid;
	}

	public void setXmlid(long xmlid) {
		this.xmlid = xmlid;
	}

	public String getXmlname() {
		return this.xmlname;
	}

	public void setXmlname(String xmlname) {
		this.xmlname = xmlname;
	}

	public long getMainid() {
		return this.mainid;
	}

	public void setMainid(long mainid) {
		this.mainid = mainid;
	}

	public String getXmlurl() {
		return this.xmlurl;
	}

	public void setXmlurl(String xmlurl) {
		this.xmlurl = xmlurl;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

}
