package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;

/**
 * SMenuitem generated by hbm2java
 */
public class SMenuitem implements java.io.Serializable {

	private SMenuitemId id;
	private BigDecimal treeid;
	private String menuitemlabel;
	private BigDecimal defaultmenuitem;
	private BigDecimal menuitemvisible;

	public SMenuitem() {
	}

	public SMenuitem(SMenuitemId id, BigDecimal treeid) {
		this.id = id;
		this.treeid = treeid;
	}

	public SMenuitem(SMenuitemId id, BigDecimal treeid, String menuitemlabel, BigDecimal defaultmenuitem,
			BigDecimal menuitemvisible) {
		this.id = id;
		this.treeid = treeid;
		this.menuitemlabel = menuitemlabel;
		this.defaultmenuitem = defaultmenuitem;
		this.menuitemvisible = menuitemvisible;
	}

	public SMenuitemId getId() {
		return this.id;
	}

	public void setId(SMenuitemId id) {
		this.id = id;
	}

	public BigDecimal getTreeid() {
		return this.treeid;
	}

	public void setTreeid(BigDecimal treeid) {
		this.treeid = treeid;
	}

	public String getMenuitemlabel() {
		return this.menuitemlabel;
	}

	public void setMenuitemlabel(String menuitemlabel) {
		this.menuitemlabel = menuitemlabel;
	}

	public BigDecimal getDefaultmenuitem() {
		return this.defaultmenuitem;
	}

	public void setDefaultmenuitem(BigDecimal defaultmenuitem) {
		this.defaultmenuitem = defaultmenuitem;
	}

	public BigDecimal getMenuitemvisible() {
		return this.menuitemvisible;
	}

	public void setMenuitemvisible(BigDecimal menuitemvisible) {
		this.menuitemvisible = menuitemvisible;
	}

}
