package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * SObjectExtend generated by hbm2java
 */
public class SObjectExtend implements java.io.Serializable {

	private String uniqueid;
	private String objectUid;
	private String objectType;
	private String text1;
	private String text2;
	private String text3;
	private String text4;
	private String text5;
	private String text6;
	private String text7;
	private String text8;
	private String text9;
	private String text10;
	private String text11;
	private String text12;
	private String text13;
	private String text14;
	private String text15;
	private String text16;
	private String text17;
	private String text18;
	private String text19;
	private String text20;
	private Date date1;
	private Date date2;
	private Date date3;
	private Date date4;
	private Date date5;
	private Date date6;
	private Date date7;
	private Date date8;
	private Date date9;
	private Date date10;
	private BigDecimal number1;
	private BigDecimal number2;
	private BigDecimal number3;
	private BigDecimal number4;
	private BigDecimal number5;
	private BigDecimal number6;
	private BigDecimal number7;
	private BigDecimal number8;
	private BigDecimal number9;
	private BigDecimal number10;
	private BigDecimal float1;
	private BigDecimal float2;
	private BigDecimal float3;
	private BigDecimal float4;
	private BigDecimal float5;
	private BigDecimal float6;
	private BigDecimal float7;
	private BigDecimal float8;
	private BigDecimal float9;
	private BigDecimal float10;

	public SObjectExtend() {
	}

	public SObjectExtend(String uniqueid, String objectUid, String objectType) {
		this.uniqueid = uniqueid;
		this.objectUid = objectUid;
		this.objectType = objectType;
	}

	public SObjectExtend(String uniqueid, String objectUid, String objectType, String text1, String text2, String text3,
			String text4, String text5, String text6, String text7, String text8, String text9, String text10,
			String text11, String text12, String text13, String text14, String text15, String text16, String text17,
			String text18, String text19, String text20, Date date1, Date date2, Date date3, Date date4, Date date5,
			Date date6, Date date7, Date date8, Date date9, Date date10, BigDecimal number1, BigDecimal number2,
			BigDecimal number3, BigDecimal number4, BigDecimal number5, BigDecimal number6, BigDecimal number7,
			BigDecimal number8, BigDecimal number9, BigDecimal number10, BigDecimal float1, BigDecimal float2,
			BigDecimal float3, BigDecimal float4, BigDecimal float5, BigDecimal float6, BigDecimal float7,
			BigDecimal float8, BigDecimal float9, BigDecimal float10) {
		this.uniqueid = uniqueid;
		this.objectUid = objectUid;
		this.objectType = objectType;
		this.text1 = text1;
		this.text2 = text2;
		this.text3 = text3;
		this.text4 = text4;
		this.text5 = text5;
		this.text6 = text6;
		this.text7 = text7;
		this.text8 = text8;
		this.text9 = text9;
		this.text10 = text10;
		this.text11 = text11;
		this.text12 = text12;
		this.text13 = text13;
		this.text14 = text14;
		this.text15 = text15;
		this.text16 = text16;
		this.text17 = text17;
		this.text18 = text18;
		this.text19 = text19;
		this.text20 = text20;
		this.date1 = date1;
		this.date2 = date2;
		this.date3 = date3;
		this.date4 = date4;
		this.date5 = date5;
		this.date6 = date6;
		this.date7 = date7;
		this.date8 = date8;
		this.date9 = date9;
		this.date10 = date10;
		this.number1 = number1;
		this.number2 = number2;
		this.number3 = number3;
		this.number4 = number4;
		this.number5 = number5;
		this.number6 = number6;
		this.number7 = number7;
		this.number8 = number8;
		this.number9 = number9;
		this.number10 = number10;
		this.float1 = float1;
		this.float2 = float2;
		this.float3 = float3;
		this.float4 = float4;
		this.float5 = float5;
		this.float6 = float6;
		this.float7 = float7;
		this.float8 = float8;
		this.float9 = float9;
		this.float10 = float10;
	}

	public String getUniqueid() {
		return this.uniqueid;
	}

	public void setUniqueid(String uniqueid) {
		this.uniqueid = uniqueid;
	}

	public String getObjectUid() {
		return this.objectUid;
	}

	public void setObjectUid(String objectUid) {
		this.objectUid = objectUid;
	}

	public String getObjectType() {
		return this.objectType;
	}

	public void setObjectType(String objectType) {
		this.objectType = objectType;
	}

	public String getText1() {
		return this.text1;
	}

	public void setText1(String text1) {
		this.text1 = text1;
	}

	public String getText2() {
		return this.text2;
	}

	public void setText2(String text2) {
		this.text2 = text2;
	}

	public String getText3() {
		return this.text3;
	}

	public void setText3(String text3) {
		this.text3 = text3;
	}

	public String getText4() {
		return this.text4;
	}

	public void setText4(String text4) {
		this.text4 = text4;
	}

	public String getText5() {
		return this.text5;
	}

	public void setText5(String text5) {
		this.text5 = text5;
	}

	public String getText6() {
		return this.text6;
	}

	public void setText6(String text6) {
		this.text6 = text6;
	}

	public String getText7() {
		return this.text7;
	}

	public void setText7(String text7) {
		this.text7 = text7;
	}

	public String getText8() {
		return this.text8;
	}

	public void setText8(String text8) {
		this.text8 = text8;
	}

	public String getText9() {
		return this.text9;
	}

	public void setText9(String text9) {
		this.text9 = text9;
	}

	public String getText10() {
		return this.text10;
	}

	public void setText10(String text10) {
		this.text10 = text10;
	}

	public String getText11() {
		return this.text11;
	}

	public void setText11(String text11) {
		this.text11 = text11;
	}

	public String getText12() {
		return this.text12;
	}

	public void setText12(String text12) {
		this.text12 = text12;
	}

	public String getText13() {
		return this.text13;
	}

	public void setText13(String text13) {
		this.text13 = text13;
	}

	public String getText14() {
		return this.text14;
	}

	public void setText14(String text14) {
		this.text14 = text14;
	}

	public String getText15() {
		return this.text15;
	}

	public void setText15(String text15) {
		this.text15 = text15;
	}

	public String getText16() {
		return this.text16;
	}

	public void setText16(String text16) {
		this.text16 = text16;
	}

	public String getText17() {
		return this.text17;
	}

	public void setText17(String text17) {
		this.text17 = text17;
	}

	public String getText18() {
		return this.text18;
	}

	public void setText18(String text18) {
		this.text18 = text18;
	}

	public String getText19() {
		return this.text19;
	}

	public void setText19(String text19) {
		this.text19 = text19;
	}

	public String getText20() {
		return this.text20;
	}

	public void setText20(String text20) {
		this.text20 = text20;
	}

	public Date getDate1() {
		return this.date1;
	}

	public void setDate1(Date date1) {
		this.date1 = date1;
	}

	public Date getDate2() {
		return this.date2;
	}

	public void setDate2(Date date2) {
		this.date2 = date2;
	}

	public Date getDate3() {
		return this.date3;
	}

	public void setDate3(Date date3) {
		this.date3 = date3;
	}

	public Date getDate4() {
		return this.date4;
	}

	public void setDate4(Date date4) {
		this.date4 = date4;
	}

	public Date getDate5() {
		return this.date5;
	}

	public void setDate5(Date date5) {
		this.date5 = date5;
	}

	public Date getDate6() {
		return this.date6;
	}

	public void setDate6(Date date6) {
		this.date6 = date6;
	}

	public Date getDate7() {
		return this.date7;
	}

	public void setDate7(Date date7) {
		this.date7 = date7;
	}

	public Date getDate8() {
		return this.date8;
	}

	public void setDate8(Date date8) {
		this.date8 = date8;
	}

	public Date getDate9() {
		return this.date9;
	}

	public void setDate9(Date date9) {
		this.date9 = date9;
	}

	public Date getDate10() {
		return this.date10;
	}

	public void setDate10(Date date10) {
		this.date10 = date10;
	}

	public BigDecimal getNumber1() {
		return this.number1;
	}

	public void setNumber1(BigDecimal number1) {
		this.number1 = number1;
	}

	public BigDecimal getNumber2() {
		return this.number2;
	}

	public void setNumber2(BigDecimal number2) {
		this.number2 = number2;
	}

	public BigDecimal getNumber3() {
		return this.number3;
	}

	public void setNumber3(BigDecimal number3) {
		this.number3 = number3;
	}

	public BigDecimal getNumber4() {
		return this.number4;
	}

	public void setNumber4(BigDecimal number4) {
		this.number4 = number4;
	}

	public BigDecimal getNumber5() {
		return this.number5;
	}

	public void setNumber5(BigDecimal number5) {
		this.number5 = number5;
	}

	public BigDecimal getNumber6() {
		return this.number6;
	}

	public void setNumber6(BigDecimal number6) {
		this.number6 = number6;
	}

	public BigDecimal getNumber7() {
		return this.number7;
	}

	public void setNumber7(BigDecimal number7) {
		this.number7 = number7;
	}

	public BigDecimal getNumber8() {
		return this.number8;
	}

	public void setNumber8(BigDecimal number8) {
		this.number8 = number8;
	}

	public BigDecimal getNumber9() {
		return this.number9;
	}

	public void setNumber9(BigDecimal number9) {
		this.number9 = number9;
	}

	public BigDecimal getNumber10() {
		return this.number10;
	}

	public void setNumber10(BigDecimal number10) {
		this.number10 = number10;
	}

	public BigDecimal getFloat1() {
		return this.float1;
	}

	public void setFloat1(BigDecimal float1) {
		this.float1 = float1;
	}

	public BigDecimal getFloat2() {
		return this.float2;
	}

	public void setFloat2(BigDecimal float2) {
		this.float2 = float2;
	}

	public BigDecimal getFloat3() {
		return this.float3;
	}

	public void setFloat3(BigDecimal float3) {
		this.float3 = float3;
	}

	public BigDecimal getFloat4() {
		return this.float4;
	}

	public void setFloat4(BigDecimal float4) {
		this.float4 = float4;
	}

	public BigDecimal getFloat5() {
		return this.float5;
	}

	public void setFloat5(BigDecimal float5) {
		this.float5 = float5;
	}

	public BigDecimal getFloat6() {
		return this.float6;
	}

	public void setFloat6(BigDecimal float6) {
		this.float6 = float6;
	}

	public BigDecimal getFloat7() {
		return this.float7;
	}

	public void setFloat7(BigDecimal float7) {
		this.float7 = float7;
	}

	public BigDecimal getFloat8() {
		return this.float8;
	}

	public void setFloat8(BigDecimal float8) {
		this.float8 = float8;
	}

	public BigDecimal getFloat9() {
		return this.float9;
	}

	public void setFloat9(BigDecimal float9) {
		this.float9 = float9;
	}

	public BigDecimal getFloat10() {
		return this.float10;
	}

	public void setFloat10(BigDecimal float10) {
		this.float10 = float10;
	}

}
