package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

/**
 * SSearch generated by hbm2java
 */
public class SSearch implements java.io.Serializable {

	private SSearchId id;
	private String url;
	private Long accesstype;
	private String notes;
	private String paramname;

	public SSearch() {
	}

	public SSearch(SSearchId id) {
		this.id = id;
	}

	public SSearch(SSearchId id, String url, Long accesstype, String notes, String paramname) {
		this.id = id;
		this.url = url;
		this.accesstype = accesstype;
		this.notes = notes;
		this.paramname = paramname;
	}

	public SSearchId getId() {
		return this.id;
	}

	public void setId(SSearchId id) {
		this.id = id;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Long getAccesstype() {
		return this.accesstype;
	}

	public void setAccesstype(Long accesstype) {
		this.accesstype = accesstype;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getParamname() {
		return this.paramname;
	}

	public void setParamname(String paramname) {
		this.paramname = paramname;
	}

}
