package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * SShowDeviceId generated by hbm2java
 */
public class SShowDeviceId implements java.io.Serializable {

	private String showDeviceUid;
	private String showDeviceId;
	private String ipAddress;
	private String location;
	private String showUrl;
	private String deptid;
	private String dutyEmployeeid;
	private String creator;
	private Date createtime;
	private String notes;
	private String showDeviceType;
	private String showDeviceState;

	public SShowDeviceId() {
	}

	public SShowDeviceId(String showDeviceUid, String showDeviceId, String ipAddress, String location, String showUrl,
			String deptid, String dutyEmployeeid, String creator, Date createtime, String notes, String showDeviceType,
			String showDeviceState) {
		this.showDeviceUid = showDeviceUid;
		this.showDeviceId = showDeviceId;
		this.ipAddress = ipAddress;
		this.location = location;
		this.showUrl = showUrl;
		this.deptid = deptid;
		this.dutyEmployeeid = dutyEmployeeid;
		this.creator = creator;
		this.createtime = createtime;
		this.notes = notes;
		this.showDeviceType = showDeviceType;
		this.showDeviceState = showDeviceState;
	}

	public String getShowDeviceUid() {
		return this.showDeviceUid;
	}

	public void setShowDeviceUid(String showDeviceUid) {
		this.showDeviceUid = showDeviceUid;
	}

	public String getShowDeviceId() {
		return this.showDeviceId;
	}

	public void setShowDeviceId(String showDeviceId) {
		this.showDeviceId = showDeviceId;
	}

	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getShowUrl() {
		return this.showUrl;
	}

	public void setShowUrl(String showUrl) {
		this.showUrl = showUrl;
	}

	public String getDeptid() {
		return this.deptid;
	}

	public void setDeptid(String deptid) {
		this.deptid = deptid;
	}

	public String getDutyEmployeeid() {
		return this.dutyEmployeeid;
	}

	public void setDutyEmployeeid(String dutyEmployeeid) {
		this.dutyEmployeeid = dutyEmployeeid;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getShowDeviceType() {
		return this.showDeviceType;
	}

	public void setShowDeviceType(String showDeviceType) {
		this.showDeviceType = showDeviceType;
	}

	public String getShowDeviceState() {
		return this.showDeviceState;
	}

	public void setShowDeviceState(String showDeviceState) {
		this.showDeviceState = showDeviceState;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SShowDeviceId))
			return false;
		SShowDeviceId castOther = (SShowDeviceId) other;

		return ((this.getShowDeviceUid() == castOther.getShowDeviceUid())
				|| (this.getShowDeviceUid() != null && castOther.getShowDeviceUid() != null
						&& this.getShowDeviceUid().equals(castOther.getShowDeviceUid())))
				&& ((this.getShowDeviceId() == castOther.getShowDeviceId())
						|| (this.getShowDeviceId() != null && castOther.getShowDeviceId() != null
								&& this.getShowDeviceId().equals(castOther.getShowDeviceId())))
				&& ((this.getIpAddress() == castOther.getIpAddress()) || (this.getIpAddress() != null
						&& castOther.getIpAddress() != null && this.getIpAddress().equals(castOther.getIpAddress())))
				&& ((this.getLocation() == castOther.getLocation()) || (this.getLocation() != null
						&& castOther.getLocation() != null && this.getLocation().equals(castOther.getLocation())))
				&& ((this.getShowUrl() == castOther.getShowUrl()) || (this.getShowUrl() != null
						&& castOther.getShowUrl() != null && this.getShowUrl().equals(castOther.getShowUrl())))
				&& ((this.getDeptid() == castOther.getDeptid()) || (this.getDeptid() != null
						&& castOther.getDeptid() != null && this.getDeptid().equals(castOther.getDeptid())))
				&& ((this.getDutyEmployeeid() == castOther.getDutyEmployeeid())
						|| (this.getDutyEmployeeid() != null && castOther.getDutyEmployeeid() != null
								&& this.getDutyEmployeeid().equals(castOther.getDutyEmployeeid())))
				&& ((this.getCreator() == castOther.getCreator()) || (this.getCreator() != null
						&& castOther.getCreator() != null && this.getCreator().equals(castOther.getCreator())))
				&& ((this.getCreatetime() == castOther.getCreatetime()) || (this.getCreatetime() != null
						&& castOther.getCreatetime() != null && this.getCreatetime().equals(castOther.getCreatetime())))
				&& ((this.getNotes() == castOther.getNotes()) || (this.getNotes() != null
						&& castOther.getNotes() != null && this.getNotes().equals(castOther.getNotes())))
				&& ((this.getShowDeviceType() == castOther.getShowDeviceType())
						|| (this.getShowDeviceType() != null && castOther.getShowDeviceType() != null
								&& this.getShowDeviceType().equals(castOther.getShowDeviceType())))
				&& ((this.getShowDeviceState() == castOther.getShowDeviceState())
						|| (this.getShowDeviceState() != null && castOther.getShowDeviceState() != null
								&& this.getShowDeviceState().equals(castOther.getShowDeviceState())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getShowDeviceUid() == null ? 0 : this.getShowDeviceUid().hashCode());
		result = 37 * result + (getShowDeviceId() == null ? 0 : this.getShowDeviceId().hashCode());
		result = 37 * result + (getIpAddress() == null ? 0 : this.getIpAddress().hashCode());
		result = 37 * result + (getLocation() == null ? 0 : this.getLocation().hashCode());
		result = 37 * result + (getShowUrl() == null ? 0 : this.getShowUrl().hashCode());
		result = 37 * result + (getDeptid() == null ? 0 : this.getDeptid().hashCode());
		result = 37 * result + (getDutyEmployeeid() == null ? 0 : this.getDutyEmployeeid().hashCode());
		result = 37 * result + (getCreator() == null ? 0 : this.getCreator().hashCode());
		result = 37 * result + (getCreatetime() == null ? 0 : this.getCreatetime().hashCode());
		result = 37 * result + (getNotes() == null ? 0 : this.getNotes().hashCode());
		result = 37 * result + (getShowDeviceType() == null ? 0 : this.getShowDeviceType().hashCode());
		result = 37 * result + (getShowDeviceState() == null ? 0 : this.getShowDeviceState().hashCode());
		return result;
	}

}
