package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TDemand generated by hbm2java
 */
public class TDemand implements java.io.Serializable {

	private String demanduid;
	private BPartNumber BPartNumber;
	private String demandid;
	private String demandname;
	private String model;
	private String batchnum;
	private BigDecimal dueqty;
	private Date earlystart;
	private Date earlyfinish;
	private Date latestart;
	private Date latefinish;
	private Date actualstart;
	private Date actualfinish;
	private Date demandstart;
	private Date demandfinish;
	private Long priority;
	private BigDecimal completepercent;
	private BigDecimal runtime;
	private BigDecimal shrinkqty;
	private Byte suspended;
	private BigDecimal deliveryqty;
	private Byte demandstate;
	private String deptid;
	private String mastershop;
	private Integer routinestate;
	private Integer materialstate;
	private Integer resourcestate;
	private String warehouseid;
	private Long responsetime;
	private String creator;
	private Date createtime;
	private String notes;
	private Long demandtype;
	private byte isbreak;
	private Byte ismps;
	private String parentuid;
	private BigDecimal planqty;
	private Byte iscritical;
	private Long readypoint;
	private Set TDemandtasklinkses = new HashSet(0);
	private Set TDemandlinksesForSuccuid = new HashSet(0);
	private Set TDemandlinksesForPreduid = new HashSet(0);
	private Set TDemandChanges = new HashSet(0);

	public TDemand() {
	}

	public TDemand(String demanduid, BPartNumber BPartNumber, String deptid, byte isbreak) {
		this.demanduid = demanduid;
		this.BPartNumber = BPartNumber;
		this.deptid = deptid;
		this.isbreak = isbreak;
	}

	public TDemand(String demanduid, BPartNumber BPartNumber, String demandid, String demandname, String model,
			String batchnum, BigDecimal dueqty, Date earlystart, Date earlyfinish, Date latestart, Date latefinish,
			Date actualstart, Date actualfinish, Date demandstart, Date demandfinish, Long priority,
			BigDecimal completepercent, BigDecimal runtime, BigDecimal shrinkqty, Byte suspended,
			BigDecimal deliveryqty, Byte demandstate, String deptid, String mastershop, Integer routinestate,
			Integer materialstate, Integer resourcestate, String warehouseid, Long responsetime, String creator,
			Date createtime, String notes, Long demandtype, byte isbreak, Byte ismps, String parentuid,
			BigDecimal planqty, Byte iscritical, Long readypoint, Set TDemandtasklinkses, Set TDemandlinksesForSuccuid,
			Set TDemandlinksesForPreduid, Set TDemandChanges) {
		this.demanduid = demanduid;
		this.BPartNumber = BPartNumber;
		this.demandid = demandid;
		this.demandname = demandname;
		this.model = model;
		this.batchnum = batchnum;
		this.dueqty = dueqty;
		this.earlystart = earlystart;
		this.earlyfinish = earlyfinish;
		this.latestart = latestart;
		this.latefinish = latefinish;
		this.actualstart = actualstart;
		this.actualfinish = actualfinish;
		this.demandstart = demandstart;
		this.demandfinish = demandfinish;
		this.priority = priority;
		this.completepercent = completepercent;
		this.runtime = runtime;
		this.shrinkqty = shrinkqty;
		this.suspended = suspended;
		this.deliveryqty = deliveryqty;
		this.demandstate = demandstate;
		this.deptid = deptid;
		this.mastershop = mastershop;
		this.routinestate = routinestate;
		this.materialstate = materialstate;
		this.resourcestate = resourcestate;
		this.warehouseid = warehouseid;
		this.responsetime = responsetime;
		this.creator = creator;
		this.createtime = createtime;
		this.notes = notes;
		this.demandtype = demandtype;
		this.isbreak = isbreak;
		this.ismps = ismps;
		this.parentuid = parentuid;
		this.planqty = planqty;
		this.iscritical = iscritical;
		this.readypoint = readypoint;
		this.TDemandtasklinkses = TDemandtasklinkses;
		this.TDemandlinksesForSuccuid = TDemandlinksesForSuccuid;
		this.TDemandlinksesForPreduid = TDemandlinksesForPreduid;
		this.TDemandChanges = TDemandChanges;
	}

	public String getDemanduid() {
		return this.demanduid;
	}

	public void setDemanduid(String demanduid) {
		this.demanduid = demanduid;
	}

	public BPartNumber getBPartNumber() {
		return this.BPartNumber;
	}

	public void setBPartNumber(BPartNumber BPartNumber) {
		this.BPartNumber = BPartNumber;
	}

	public String getDemandid() {
		return this.demandid;
	}

	public void setDemandid(String demandid) {
		this.demandid = demandid;
	}

	public String getDemandname() {
		return this.demandname;
	}

	public void setDemandname(String demandname) {
		this.demandname = demandname;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getBatchnum() {
		return this.batchnum;
	}

	public void setBatchnum(String batchnum) {
		this.batchnum = batchnum;
	}

	public BigDecimal getDueqty() {
		return this.dueqty;
	}

	public void setDueqty(BigDecimal dueqty) {
		this.dueqty = dueqty;
	}

	public Date getEarlystart() {
		return this.earlystart;
	}

	public void setEarlystart(Date earlystart) {
		this.earlystart = earlystart;
	}

	public Date getEarlyfinish() {
		return this.earlyfinish;
	}

	public void setEarlyfinish(Date earlyfinish) {
		this.earlyfinish = earlyfinish;
	}

	public Date getLatestart() {
		return this.latestart;
	}

	public void setLatestart(Date latestart) {
		this.latestart = latestart;
	}

	public Date getLatefinish() {
		return this.latefinish;
	}

	public void setLatefinish(Date latefinish) {
		this.latefinish = latefinish;
	}

	public Date getActualstart() {
		return this.actualstart;
	}

	public void setActualstart(Date actualstart) {
		this.actualstart = actualstart;
	}

	public Date getActualfinish() {
		return this.actualfinish;
	}

	public void setActualfinish(Date actualfinish) {
		this.actualfinish = actualfinish;
	}

	public Date getDemandstart() {
		return this.demandstart;
	}

	public void setDemandstart(Date demandstart) {
		this.demandstart = demandstart;
	}

	public Date getDemandfinish() {
		return this.demandfinish;
	}

	public void setDemandfinish(Date demandfinish) {
		this.demandfinish = demandfinish;
	}

	public Long getPriority() {
		return this.priority;
	}

	public void setPriority(Long priority) {
		this.priority = priority;
	}

	public BigDecimal getCompletepercent() {
		return this.completepercent;
	}

	public void setCompletepercent(BigDecimal completepercent) {
		this.completepercent = completepercent;
	}

	public BigDecimal getRuntime() {
		return this.runtime;
	}

	public void setRuntime(BigDecimal runtime) {
		this.runtime = runtime;
	}

	public BigDecimal getShrinkqty() {
		return this.shrinkqty;
	}

	public void setShrinkqty(BigDecimal shrinkqty) {
		this.shrinkqty = shrinkqty;
	}

	public Byte getSuspended() {
		return this.suspended;
	}

	public void setSuspended(Byte suspended) {
		this.suspended = suspended;
	}

	public BigDecimal getDeliveryqty() {
		return this.deliveryqty;
	}

	public void setDeliveryqty(BigDecimal deliveryqty) {
		this.deliveryqty = deliveryqty;
	}

	public Byte getDemandstate() {
		return this.demandstate;
	}

	public void setDemandstate(Byte demandstate) {
		this.demandstate = demandstate;
	}

	public String getDeptid() {
		return this.deptid;
	}

	public void setDeptid(String deptid) {
		this.deptid = deptid;
	}

	public String getMastershop() {
		return this.mastershop;
	}

	public void setMastershop(String mastershop) {
		this.mastershop = mastershop;
	}

	public Integer getRoutinestate() {
		return this.routinestate;
	}

	public void setRoutinestate(Integer routinestate) {
		this.routinestate = routinestate;
	}

	public Integer getMaterialstate() {
		return this.materialstate;
	}

	public void setMaterialstate(Integer materialstate) {
		this.materialstate = materialstate;
	}

	public Integer getResourcestate() {
		return this.resourcestate;
	}

	public void setResourcestate(Integer resourcestate) {
		this.resourcestate = resourcestate;
	}

	public String getWarehouseid() {
		return this.warehouseid;
	}

	public void setWarehouseid(String warehouseid) {
		this.warehouseid = warehouseid;
	}

	public Long getResponsetime() {
		return this.responsetime;
	}

	public void setResponsetime(Long responsetime) {
		this.responsetime = responsetime;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public Long getDemandtype() {
		return this.demandtype;
	}

	public void setDemandtype(Long demandtype) {
		this.demandtype = demandtype;
	}

	public byte getIsbreak() {
		return this.isbreak;
	}

	public void setIsbreak(byte isbreak) {
		this.isbreak = isbreak;
	}

	public Byte getIsmps() {
		return this.ismps;
	}

	public void setIsmps(Byte ismps) {
		this.ismps = ismps;
	}

	public String getParentuid() {
		return this.parentuid;
	}

	public void setParentuid(String parentuid) {
		this.parentuid = parentuid;
	}

	public BigDecimal getPlanqty() {
		return this.planqty;
	}

	public void setPlanqty(BigDecimal planqty) {
		this.planqty = planqty;
	}

	public Byte getIscritical() {
		return this.iscritical;
	}

	public void setIscritical(Byte iscritical) {
		this.iscritical = iscritical;
	}

	public Long getReadypoint() {
		return this.readypoint;
	}

	public void setReadypoint(Long readypoint) {
		this.readypoint = readypoint;
	}

	public Set getTDemandtasklinkses() {
		return this.TDemandtasklinkses;
	}

	public void setTDemandtasklinkses(Set TDemandtasklinkses) {
		this.TDemandtasklinkses = TDemandtasklinkses;
	}

	public Set getTDemandlinksesForSuccuid() {
		return this.TDemandlinksesForSuccuid;
	}

	public void setTDemandlinksesForSuccuid(Set TDemandlinksesForSuccuid) {
		this.TDemandlinksesForSuccuid = TDemandlinksesForSuccuid;
	}

	public Set getTDemandlinksesForPreduid() {
		return this.TDemandlinksesForPreduid;
	}

	public void setTDemandlinksesForPreduid(Set TDemandlinksesForPreduid) {
		this.TDemandlinksesForPreduid = TDemandlinksesForPreduid;
	}

	public Set getTDemandChanges() {
		return this.TDemandChanges;
	}

	public void setTDemandChanges(Set TDemandChanges) {
		this.TDemandChanges = TDemandChanges;
	}

}
