package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * TDemandPartId generated by hbm2java
 */
public class TDemandPartId implements java.io.Serializable {

	private String uniqueid;
	private String demanduid;
	private String partNumber;
	private BigDecimal qtyreq;
	private Long reqtype;
	private BigDecimal allocatedqty;
	private BigDecimal singlein;
	private BigDecimal singleout;
	private String creator;
	private Date createtime;
	private String notes;
	private Long locklevel;
	private Long readypoint;
	private Byte iscritical;

	public TDemandPartId() {
	}

	public TDemandPartId(String uniqueid, String demanduid, String partNumber) {
		this.uniqueid = uniqueid;
		this.demanduid = demanduid;
		this.partNumber = partNumber;
	}

	public TDemandPartId(String uniqueid, String demanduid, String partNumber, BigDecimal qtyreq, Long reqtype,
			BigDecimal allocatedqty, BigDecimal singlein, BigDecimal singleout, String creator, Date createtime,
			String notes, Long locklevel, Long readypoint, Byte iscritical) {
		this.uniqueid = uniqueid;
		this.demanduid = demanduid;
		this.partNumber = partNumber;
		this.qtyreq = qtyreq;
		this.reqtype = reqtype;
		this.allocatedqty = allocatedqty;
		this.singlein = singlein;
		this.singleout = singleout;
		this.creator = creator;
		this.createtime = createtime;
		this.notes = notes;
		this.locklevel = locklevel;
		this.readypoint = readypoint;
		this.iscritical = iscritical;
	}

	public String getUniqueid() {
		return this.uniqueid;
	}

	public void setUniqueid(String uniqueid) {
		this.uniqueid = uniqueid;
	}

	public String getDemanduid() {
		return this.demanduid;
	}

	public void setDemanduid(String demanduid) {
		this.demanduid = demanduid;
	}

	public String getPartNumber() {
		return this.partNumber;
	}

	public void setPartNumber(String partNumber) {
		this.partNumber = partNumber;
	}

	public BigDecimal getQtyreq() {
		return this.qtyreq;
	}

	public void setQtyreq(BigDecimal qtyreq) {
		this.qtyreq = qtyreq;
	}

	public Long getReqtype() {
		return this.reqtype;
	}

	public void setReqtype(Long reqtype) {
		this.reqtype = reqtype;
	}

	public BigDecimal getAllocatedqty() {
		return this.allocatedqty;
	}

	public void setAllocatedqty(BigDecimal allocatedqty) {
		this.allocatedqty = allocatedqty;
	}

	public BigDecimal getSinglein() {
		return this.singlein;
	}

	public void setSinglein(BigDecimal singlein) {
		this.singlein = singlein;
	}

	public BigDecimal getSingleout() {
		return this.singleout;
	}

	public void setSingleout(BigDecimal singleout) {
		this.singleout = singleout;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public Long getLocklevel() {
		return this.locklevel;
	}

	public void setLocklevel(Long locklevel) {
		this.locklevel = locklevel;
	}

	public Long getReadypoint() {
		return this.readypoint;
	}

	public void setReadypoint(Long readypoint) {
		this.readypoint = readypoint;
	}

	public Byte getIscritical() {
		return this.iscritical;
	}

	public void setIscritical(Byte iscritical) {
		this.iscritical = iscritical;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TDemandPartId))
			return false;
		TDemandPartId castOther = (TDemandPartId) other;

		return ((this.getUniqueid() == castOther.getUniqueid()) || (this.getUniqueid() != null
				&& castOther.getUniqueid() != null && this.getUniqueid().equals(castOther.getUniqueid())))
				&& ((this.getDemanduid() == castOther.getDemanduid()) || (this.getDemanduid() != null
						&& castOther.getDemanduid() != null && this.getDemanduid().equals(castOther.getDemanduid())))
				&& ((this.getPartNumber() == castOther.getPartNumber()) || (this.getPartNumber() != null
						&& castOther.getPartNumber() != null && this.getPartNumber().equals(castOther.getPartNumber())))
				&& ((this.getQtyreq() == castOther.getQtyreq()) || (this.getQtyreq() != null
						&& castOther.getQtyreq() != null && this.getQtyreq().equals(castOther.getQtyreq())))
				&& ((this.getReqtype() == castOther.getReqtype()) || (this.getReqtype() != null
						&& castOther.getReqtype() != null && this.getReqtype().equals(castOther.getReqtype())))
				&& ((this.getAllocatedqty() == castOther.getAllocatedqty())
						|| (this.getAllocatedqty() != null && castOther.getAllocatedqty() != null
								&& this.getAllocatedqty().equals(castOther.getAllocatedqty())))
				&& ((this.getSinglein() == castOther.getSinglein()) || (this.getSinglein() != null
						&& castOther.getSinglein() != null && this.getSinglein().equals(castOther.getSinglein())))
				&& ((this.getSingleout() == castOther.getSingleout()) || (this.getSingleout() != null
						&& castOther.getSingleout() != null && this.getSingleout().equals(castOther.getSingleout())))
				&& ((this.getCreator() == castOther.getCreator()) || (this.getCreator() != null
						&& castOther.getCreator() != null && this.getCreator().equals(castOther.getCreator())))
				&& ((this.getCreatetime() == castOther.getCreatetime()) || (this.getCreatetime() != null
						&& castOther.getCreatetime() != null && this.getCreatetime().equals(castOther.getCreatetime())))
				&& ((this.getNotes() == castOther.getNotes()) || (this.getNotes() != null
						&& castOther.getNotes() != null && this.getNotes().equals(castOther.getNotes())))
				&& ((this.getLocklevel() == castOther.getLocklevel()) || (this.getLocklevel() != null
						&& castOther.getLocklevel() != null && this.getLocklevel().equals(castOther.getLocklevel())))
				&& ((this.getReadypoint() == castOther.getReadypoint()) || (this.getReadypoint() != null
						&& castOther.getReadypoint() != null && this.getReadypoint().equals(castOther.getReadypoint())))
				&& ((this.getIscritical() == castOther.getIscritical())
						|| (this.getIscritical() != null && castOther.getIscritical() != null
								&& this.getIscritical().equals(castOther.getIscritical())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUniqueid() == null ? 0 : this.getUniqueid().hashCode());
		result = 37 * result + (getDemanduid() == null ? 0 : this.getDemanduid().hashCode());
		result = 37 * result + (getPartNumber() == null ? 0 : this.getPartNumber().hashCode());
		result = 37 * result + (getQtyreq() == null ? 0 : this.getQtyreq().hashCode());
		result = 37 * result + (getReqtype() == null ? 0 : this.getReqtype().hashCode());
		result = 37 * result + (getAllocatedqty() == null ? 0 : this.getAllocatedqty().hashCode());
		result = 37 * result + (getSinglein() == null ? 0 : this.getSinglein().hashCode());
		result = 37 * result + (getSingleout() == null ? 0 : this.getSingleout().hashCode());
		result = 37 * result + (getCreator() == null ? 0 : this.getCreator().hashCode());
		result = 37 * result + (getCreatetime() == null ? 0 : this.getCreatetime().hashCode());
		result = 37 * result + (getNotes() == null ? 0 : this.getNotes().hashCode());
		result = 37 * result + (getLocklevel() == null ? 0 : this.getLocklevel().hashCode());
		result = 37 * result + (getReadypoint() == null ? 0 : this.getReadypoint().hashCode());
		result = 37 * result + (getIscritical() == null ? 0 : this.getIscritical().hashCode());
		return result;
	}

}
