package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * TDemandlinks generated by hbm2java
 */
public class TDemandlinks implements java.io.Serializable {

	private TDemandlinksId id;
	private TDemand TDemandBySuccuid;
	private TDemand TDemandByPreduid;
	private BigDecimal linkqty;
	private Long linktype;
	private Long linklag;
	private Byte isineffect;
	private String uniqueId;
	private String dependtype;
	private Boolean locklevel;
	private Date lockexpiredate;

	public TDemandlinks() {
	}

	public TDemandlinks(TDemandlinksId id, TDemand TDemandBySuccuid, TDemand TDemandByPreduid, String dependtype) {
		this.id = id;
		this.TDemandBySuccuid = TDemandBySuccuid;
		this.TDemandByPreduid = TDemandByPreduid;
		this.dependtype = dependtype;
	}

	public TDemandlinks(TDemandlinksId id, TDemand TDemandBySuccuid, TDemand TDemandByPreduid, BigDecimal linkqty,
			Long linktype, Long linklag, Byte isineffect, String uniqueId, String dependtype, Boolean locklevel,
			Date lockexpiredate) {
		this.id = id;
		this.TDemandBySuccuid = TDemandBySuccuid;
		this.TDemandByPreduid = TDemandByPreduid;
		this.linkqty = linkqty;
		this.linktype = linktype;
		this.linklag = linklag;
		this.isineffect = isineffect;
		this.uniqueId = uniqueId;
		this.dependtype = dependtype;
		this.locklevel = locklevel;
		this.lockexpiredate = lockexpiredate;
	}

	public TDemandlinksId getId() {
		return this.id;
	}

	public void setId(TDemandlinksId id) {
		this.id = id;
	}

	public TDemand getTDemandBySuccuid() {
		return this.TDemandBySuccuid;
	}

	public void setTDemandBySuccuid(TDemand TDemandBySuccuid) {
		this.TDemandBySuccuid = TDemandBySuccuid;
	}

	public TDemand getTDemandByPreduid() {
		return this.TDemandByPreduid;
	}

	public void setTDemandByPreduid(TDemand TDemandByPreduid) {
		this.TDemandByPreduid = TDemandByPreduid;
	}

	public BigDecimal getLinkqty() {
		return this.linkqty;
	}

	public void setLinkqty(BigDecimal linkqty) {
		this.linkqty = linkqty;
	}

	public Long getLinktype() {
		return this.linktype;
	}

	public void setLinktype(Long linktype) {
		this.linktype = linktype;
	}

	public Long getLinklag() {
		return this.linklag;
	}

	public void setLinklag(Long linklag) {
		this.linklag = linklag;
	}

	public Byte getIsineffect() {
		return this.isineffect;
	}

	public void setIsineffect(Byte isineffect) {
		this.isineffect = isineffect;
	}

	public String getUniqueId() {
		return this.uniqueId;
	}

	public void setUniqueId(String uniqueId) {
		this.uniqueId = uniqueId;
	}

	public String getDependtype() {
		return this.dependtype;
	}

	public void setDependtype(String dependtype) {
		this.dependtype = dependtype;
	}

	public Boolean getLocklevel() {
		return this.locklevel;
	}

	public void setLocklevel(Boolean locklevel) {
		this.locklevel = locklevel;
	}

	public Date getLockexpiredate() {
		return this.lockexpiredate;
	}

	public void setLockexpiredate(Date lockexpiredate) {
		this.lockexpiredate = lockexpiredate;
	}

}
