package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * TDwesdId generated by hbm2java
 */
public class TDwesdId implements java.io.Serializable {

	private String scheduleuid;
	private String taskuid;
	private Date earlystart;
	private Date latefinish;
	private Date planstart;
	private Date planfinish;
	private Long priority;
	private String deptid;
	private BigDecimal psduration;
	private BigDecimal remainwork;
	private BigDecimal remainCriticalWork;
	private Long issuccess;
	private Boolean locked;
	private String partNumber;
	private String batchnum;
	private Long taskstate;
	private BigDecimal planqty;
	private String drawingid;
	private Boolean issplitted;
	private BigDecimal slackfactor;
	private String partName;
	private String model;
	private Long plangrade;
	private Byte taskschedulestate;
	private Byte taskscheduletype;
	private String notes;
	private Long delaycost;
	private Byte iscritical;

	public TDwesdId() {
	}

	public TDwesdId(String scheduleuid, String taskuid) {
		this.scheduleuid = scheduleuid;
		this.taskuid = taskuid;
	}

	public TDwesdId(String scheduleuid, String taskuid, Date earlystart, Date latefinish, Date planstart,
			Date planfinish, Long priority, String deptid, BigDecimal psduration, BigDecimal remainwork,
			BigDecimal remainCriticalWork, Long issuccess, Boolean locked, String partNumber, String batchnum,
			Long taskstate, BigDecimal planqty, String drawingid, Boolean issplitted, BigDecimal slackfactor,
			String partName, String model, Long plangrade, Byte taskschedulestate, Byte taskscheduletype, String notes,
			Long delaycost, Byte iscritical) {
		this.scheduleuid = scheduleuid;
		this.taskuid = taskuid;
		this.earlystart = earlystart;
		this.latefinish = latefinish;
		this.planstart = planstart;
		this.planfinish = planfinish;
		this.priority = priority;
		this.deptid = deptid;
		this.psduration = psduration;
		this.remainwork = remainwork;
		this.remainCriticalWork = remainCriticalWork;
		this.issuccess = issuccess;
		this.locked = locked;
		this.partNumber = partNumber;
		this.batchnum = batchnum;
		this.taskstate = taskstate;
		this.planqty = planqty;
		this.drawingid = drawingid;
		this.issplitted = issplitted;
		this.slackfactor = slackfactor;
		this.partName = partName;
		this.model = model;
		this.plangrade = plangrade;
		this.taskschedulestate = taskschedulestate;
		this.taskscheduletype = taskscheduletype;
		this.notes = notes;
		this.delaycost = delaycost;
		this.iscritical = iscritical;
	}

	public String getScheduleuid() {
		return this.scheduleuid;
	}

	public void setScheduleuid(String scheduleuid) {
		this.scheduleuid = scheduleuid;
	}

	public String getTaskuid() {
		return this.taskuid;
	}

	public void setTaskuid(String taskuid) {
		this.taskuid = taskuid;
	}

	public Date getEarlystart() {
		return this.earlystart;
	}

	public void setEarlystart(Date earlystart) {
		this.earlystart = earlystart;
	}

	public Date getLatefinish() {
		return this.latefinish;
	}

	public void setLatefinish(Date latefinish) {
		this.latefinish = latefinish;
	}

	public Date getPlanstart() {
		return this.planstart;
	}

	public void setPlanstart(Date planstart) {
		this.planstart = planstart;
	}

	public Date getPlanfinish() {
		return this.planfinish;
	}

	public void setPlanfinish(Date planfinish) {
		this.planfinish = planfinish;
	}

	public Long getPriority() {
		return this.priority;
	}

	public void setPriority(Long priority) {
		this.priority = priority;
	}

	public String getDeptid() {
		return this.deptid;
	}

	public void setDeptid(String deptid) {
		this.deptid = deptid;
	}

	public BigDecimal getPsduration() {
		return this.psduration;
	}

	public void setPsduration(BigDecimal psduration) {
		this.psduration = psduration;
	}

	public BigDecimal getRemainwork() {
		return this.remainwork;
	}

	public void setRemainwork(BigDecimal remainwork) {
		this.remainwork = remainwork;
	}

	public BigDecimal getRemainCriticalWork() {
		return this.remainCriticalWork;
	}

	public void setRemainCriticalWork(BigDecimal remainCriticalWork) {
		this.remainCriticalWork = remainCriticalWork;
	}

	public Long getIssuccess() {
		return this.issuccess;
	}

	public void setIssuccess(Long issuccess) {
		this.issuccess = issuccess;
	}

	public Boolean getLocked() {
		return this.locked;
	}

	public void setLocked(Boolean locked) {
		this.locked = locked;
	}

	public String getPartNumber() {
		return this.partNumber;
	}

	public void setPartNumber(String partNumber) {
		this.partNumber = partNumber;
	}

	public String getBatchnum() {
		return this.batchnum;
	}

	public void setBatchnum(String batchnum) {
		this.batchnum = batchnum;
	}

	public Long getTaskstate() {
		return this.taskstate;
	}

	public void setTaskstate(Long taskstate) {
		this.taskstate = taskstate;
	}

	public BigDecimal getPlanqty() {
		return this.planqty;
	}

	public void setPlanqty(BigDecimal planqty) {
		this.planqty = planqty;
	}

	public String getDrawingid() {
		return this.drawingid;
	}

	public void setDrawingid(String drawingid) {
		this.drawingid = drawingid;
	}

	public Boolean getIssplitted() {
		return this.issplitted;
	}

	public void setIssplitted(Boolean issplitted) {
		this.issplitted = issplitted;
	}

	public BigDecimal getSlackfactor() {
		return this.slackfactor;
	}

	public void setSlackfactor(BigDecimal slackfactor) {
		this.slackfactor = slackfactor;
	}

	public String getPartName() {
		return this.partName;
	}

	public void setPartName(String partName) {
		this.partName = partName;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public Long getPlangrade() {
		return this.plangrade;
	}

	public void setPlangrade(Long plangrade) {
		this.plangrade = plangrade;
	}

	public Byte getTaskschedulestate() {
		return this.taskschedulestate;
	}

	public void setTaskschedulestate(Byte taskschedulestate) {
		this.taskschedulestate = taskschedulestate;
	}

	public Byte getTaskscheduletype() {
		return this.taskscheduletype;
	}

	public void setTaskscheduletype(Byte taskscheduletype) {
		this.taskscheduletype = taskscheduletype;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public Long getDelaycost() {
		return this.delaycost;
	}

	public void setDelaycost(Long delaycost) {
		this.delaycost = delaycost;
	}

	public Byte getIscritical() {
		return this.iscritical;
	}

	public void setIscritical(Byte iscritical) {
		this.iscritical = iscritical;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TDwesdId))
			return false;
		TDwesdId castOther = (TDwesdId) other;

		return ((this.getScheduleuid() == castOther.getScheduleuid()) || (this.getScheduleuid() != null
				&& castOther.getScheduleuid() != null && this.getScheduleuid().equals(castOther.getScheduleuid())))
				&& ((this.getTaskuid() == castOther.getTaskuid()) || (this.getTaskuid() != null
						&& castOther.getTaskuid() != null && this.getTaskuid().equals(castOther.getTaskuid())))
				&& ((this.getEarlystart() == castOther.getEarlystart()) || (this.getEarlystart() != null
						&& castOther.getEarlystart() != null && this.getEarlystart().equals(castOther.getEarlystart())))
				&& ((this.getLatefinish() == castOther.getLatefinish()) || (this.getLatefinish() != null
						&& castOther.getLatefinish() != null && this.getLatefinish().equals(castOther.getLatefinish())))
				&& ((this.getPlanstart() == castOther.getPlanstart()) || (this.getPlanstart() != null
						&& castOther.getPlanstart() != null && this.getPlanstart().equals(castOther.getPlanstart())))
				&& ((this.getPlanfinish() == castOther.getPlanfinish()) || (this.getPlanfinish() != null
						&& castOther.getPlanfinish() != null && this.getPlanfinish().equals(castOther.getPlanfinish())))
				&& ((this.getPriority() == castOther.getPriority()) || (this.getPriority() != null
						&& castOther.getPriority() != null && this.getPriority().equals(castOther.getPriority())))
				&& ((this.getDeptid() == castOther.getDeptid()) || (this.getDeptid() != null
						&& castOther.getDeptid() != null && this.getDeptid().equals(castOther.getDeptid())))
				&& ((this.getPsduration() == castOther.getPsduration()) || (this.getPsduration() != null
						&& castOther.getPsduration() != null && this.getPsduration().equals(castOther.getPsduration())))
				&& ((this.getRemainwork() == castOther.getRemainwork()) || (this.getRemainwork() != null
						&& castOther.getRemainwork() != null && this.getRemainwork().equals(castOther.getRemainwork())))
				&& ((this.getRemainCriticalWork() == castOther.getRemainCriticalWork())
						|| (this.getRemainCriticalWork() != null && castOther.getRemainCriticalWork() != null
								&& this.getRemainCriticalWork().equals(castOther.getRemainCriticalWork())))
				&& ((this.getIssuccess() == castOther.getIssuccess()) || (this.getIssuccess() != null
						&& castOther.getIssuccess() != null && this.getIssuccess().equals(castOther.getIssuccess())))
				&& ((this.getLocked() == castOther.getLocked()) || (this.getLocked() != null
						&& castOther.getLocked() != null && this.getLocked().equals(castOther.getLocked())))
				&& ((this.getPartNumber() == castOther.getPartNumber()) || (this.getPartNumber() != null
						&& castOther.getPartNumber() != null && this.getPartNumber().equals(castOther.getPartNumber())))
				&& ((this.getBatchnum() == castOther.getBatchnum()) || (this.getBatchnum() != null
						&& castOther.getBatchnum() != null && this.getBatchnum().equals(castOther.getBatchnum())))
				&& ((this.getTaskstate() == castOther.getTaskstate()) || (this.getTaskstate() != null
						&& castOther.getTaskstate() != null && this.getTaskstate().equals(castOther.getTaskstate())))
				&& ((this.getPlanqty() == castOther.getPlanqty()) || (this.getPlanqty() != null
						&& castOther.getPlanqty() != null && this.getPlanqty().equals(castOther.getPlanqty())))
				&& ((this.getDrawingid() == castOther.getDrawingid()) || (this.getDrawingid() != null
						&& castOther.getDrawingid() != null && this.getDrawingid().equals(castOther.getDrawingid())))
				&& ((this.getIssplitted() == castOther.getIssplitted()) || (this.getIssplitted() != null
						&& castOther.getIssplitted() != null && this.getIssplitted().equals(castOther.getIssplitted())))
				&& ((this.getSlackfactor() == castOther.getSlackfactor())
						|| (this.getSlackfactor() != null && castOther.getSlackfactor() != null
								&& this.getSlackfactor().equals(castOther.getSlackfactor())))
				&& ((this.getPartName() == castOther.getPartName()) || (this.getPartName() != null
						&& castOther.getPartName() != null && this.getPartName().equals(castOther.getPartName())))
				&& ((this.getModel() == castOther.getModel()) || (this.getModel() != null
						&& castOther.getModel() != null && this.getModel().equals(castOther.getModel())))
				&& ((this.getPlangrade() == castOther.getPlangrade()) || (this.getPlangrade() != null
						&& castOther.getPlangrade() != null && this.getPlangrade().equals(castOther.getPlangrade())))
				&& ((this.getTaskschedulestate() == castOther.getTaskschedulestate())
						|| (this.getTaskschedulestate() != null && castOther.getTaskschedulestate() != null
								&& this.getTaskschedulestate().equals(castOther.getTaskschedulestate())))
				&& ((this.getTaskscheduletype() == castOther.getTaskscheduletype())
						|| (this.getTaskscheduletype() != null && castOther.getTaskscheduletype() != null
								&& this.getTaskscheduletype().equals(castOther.getTaskscheduletype())))
				&& ((this.getNotes() == castOther.getNotes()) || (this.getNotes() != null
						&& castOther.getNotes() != null && this.getNotes().equals(castOther.getNotes())))
				&& ((this.getDelaycost() == castOther.getDelaycost()) || (this.getDelaycost() != null
						&& castOther.getDelaycost() != null && this.getDelaycost().equals(castOther.getDelaycost())))
				&& ((this.getIscritical() == castOther.getIscritical())
						|| (this.getIscritical() != null && castOther.getIscritical() != null
								&& this.getIscritical().equals(castOther.getIscritical())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getScheduleuid() == null ? 0 : this.getScheduleuid().hashCode());
		result = 37 * result + (getTaskuid() == null ? 0 : this.getTaskuid().hashCode());
		result = 37 * result + (getEarlystart() == null ? 0 : this.getEarlystart().hashCode());
		result = 37 * result + (getLatefinish() == null ? 0 : this.getLatefinish().hashCode());
		result = 37 * result + (getPlanstart() == null ? 0 : this.getPlanstart().hashCode());
		result = 37 * result + (getPlanfinish() == null ? 0 : this.getPlanfinish().hashCode());
		result = 37 * result + (getPriority() == null ? 0 : this.getPriority().hashCode());
		result = 37 * result + (getDeptid() == null ? 0 : this.getDeptid().hashCode());
		result = 37 * result + (getPsduration() == null ? 0 : this.getPsduration().hashCode());
		result = 37 * result + (getRemainwork() == null ? 0 : this.getRemainwork().hashCode());
		result = 37 * result + (getRemainCriticalWork() == null ? 0 : this.getRemainCriticalWork().hashCode());
		result = 37 * result + (getIssuccess() == null ? 0 : this.getIssuccess().hashCode());
		result = 37 * result + (getLocked() == null ? 0 : this.getLocked().hashCode());
		result = 37 * result + (getPartNumber() == null ? 0 : this.getPartNumber().hashCode());
		result = 37 * result + (getBatchnum() == null ? 0 : this.getBatchnum().hashCode());
		result = 37 * result + (getTaskstate() == null ? 0 : this.getTaskstate().hashCode());
		result = 37 * result + (getPlanqty() == null ? 0 : this.getPlanqty().hashCode());
		result = 37 * result + (getDrawingid() == null ? 0 : this.getDrawingid().hashCode());
		result = 37 * result + (getIssplitted() == null ? 0 : this.getIssplitted().hashCode());
		result = 37 * result + (getSlackfactor() == null ? 0 : this.getSlackfactor().hashCode());
		result = 37 * result + (getPartName() == null ? 0 : this.getPartName().hashCode());
		result = 37 * result + (getModel() == null ? 0 : this.getModel().hashCode());
		result = 37 * result + (getPlangrade() == null ? 0 : this.getPlangrade().hashCode());
		result = 37 * result + (getTaskschedulestate() == null ? 0 : this.getTaskschedulestate().hashCode());
		result = 37 * result + (getTaskscheduletype() == null ? 0 : this.getTaskscheduletype().hashCode());
		result = 37 * result + (getNotes() == null ? 0 : this.getNotes().hashCode());
		result = 37 * result + (getDelaycost() == null ? 0 : this.getDelaycost().hashCode());
		result = 37 * result + (getIscritical() == null ? 0 : this.getIscritical().hashCode());
		return result;
	}

}
