package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * TLinks generated by hbm2java
 */
public class TLinks implements java.io.Serializable {

	private TLinksId id;
	private TTasks TTasksByPreduid;
	private TTasks TTasksBySuccuid;
	private BigDecimal linkqty;
	private Long linktype;
	private Long linklag;
	private Byte isineffect;
	private String uniqueId;
	private String dependtype;
	private Boolean locklevel;
	private Date lockexpiredate;

	public TLinks() {
	}

	public TLinks(TLinksId id, TTasks TTasksByPreduid, TTasks TTasksBySuccuid, String dependtype) {
		this.id = id;
		this.TTasksByPreduid = TTasksByPreduid;
		this.TTasksBySuccuid = TTasksBySuccuid;
		this.dependtype = dependtype;
	}

	public TLinks(TLinksId id, TTasks TTasksByPreduid, TTasks TTasksBySuccuid, BigDecimal linkqty, Long linktype,
			Long linklag, Byte isineffect, String uniqueId, String dependtype, Boolean locklevel, Date lockexpiredate) {
		this.id = id;
		this.TTasksByPreduid = TTasksByPreduid;
		this.TTasksBySuccuid = TTasksBySuccuid;
		this.linkqty = linkqty;
		this.linktype = linktype;
		this.linklag = linklag;
		this.isineffect = isineffect;
		this.uniqueId = uniqueId;
		this.dependtype = dependtype;
		this.locklevel = locklevel;
		this.lockexpiredate = lockexpiredate;
	}

	public TLinksId getId() {
		return this.id;
	}

	public void setId(TLinksId id) {
		this.id = id;
	}

	public TTasks getTTasksByPreduid() {
		return this.TTasksByPreduid;
	}

	public void setTTasksByPreduid(TTasks TTasksByPreduid) {
		this.TTasksByPreduid = TTasksByPreduid;
	}

	public TTasks getTTasksBySuccuid() {
		return this.TTasksBySuccuid;
	}

	public void setTTasksBySuccuid(TTasks TTasksBySuccuid) {
		this.TTasksBySuccuid = TTasksBySuccuid;
	}

	public BigDecimal getLinkqty() {
		return this.linkqty;
	}

	public void setLinkqty(BigDecimal linkqty) {
		this.linkqty = linkqty;
	}

	public Long getLinktype() {
		return this.linktype;
	}

	public void setLinktype(Long linktype) {
		this.linktype = linktype;
	}

	public Long getLinklag() {
		return this.linklag;
	}

	public void setLinklag(Long linklag) {
		this.linklag = linklag;
	}

	public Byte getIsineffect() {
		return this.isineffect;
	}

	public void setIsineffect(Byte isineffect) {
		this.isineffect = isineffect;
	}

	public String getUniqueId() {
		return this.uniqueId;
	}

	public void setUniqueId(String uniqueId) {
		this.uniqueId = uniqueId;
	}

	public String getDependtype() {
		return this.dependtype;
	}

	public void setDependtype(String dependtype) {
		this.dependtype = dependtype;
	}

	public Boolean getLocklevel() {
		return this.locklevel;
	}

	public void setLocklevel(Boolean locklevel) {
		this.locklevel = locklevel;
	}

	public Date getLockexpiredate() {
		return this.lockexpiredate;
	}

	public void setLockexpiredate(Date lockexpiredate) {
		this.lockexpiredate = lockexpiredate;
	}

}
