package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;

/**
 * TPompsLink generated by hbm2java
 */
public class TPompsLink implements java.io.Serializable {

	private String uniqueid;
	private TMps TMps;
	private TProductorder TProductorder;
	private BigDecimal linkqty;
	private String linktype;
	private Byte effective;

	public TPompsLink() {
	}

	public TPompsLink(String uniqueid, TMps TMps, TProductorder TProductorder) {
		this.uniqueid = uniqueid;
		this.TMps = TMps;
		this.TProductorder = TProductorder;
	}

	public TPompsLink(String uniqueid, TMps TMps, TProductorder TProductorder, BigDecimal linkqty, String linktype,
			Byte effective) {
		this.uniqueid = uniqueid;
		this.TMps = TMps;
		this.TProductorder = TProductorder;
		this.linkqty = linkqty;
		this.linktype = linktype;
		this.effective = effective;
	}

	public String getUniqueid() {
		return this.uniqueid;
	}

	public void setUniqueid(String uniqueid) {
		this.uniqueid = uniqueid;
	}

	public TMps getTMps() {
		return this.TMps;
	}

	public void setTMps(TMps TMps) {
		this.TMps = TMps;
	}

	public TProductorder getTProductorder() {
		return this.TProductorder;
	}

	public void setTProductorder(TProductorder TProductorder) {
		this.TProductorder = TProductorder;
	}

	public BigDecimal getLinkqty() {
		return this.linkqty;
	}

	public void setLinkqty(BigDecimal linkqty) {
		this.linkqty = linkqty;
	}

	public String getLinktype() {
		return this.linktype;
	}

	public void setLinktype(String linktype) {
		this.linktype = linktype;
	}

	public Byte getEffective() {
		return this.effective;
	}

	public void setEffective(Byte effective) {
		this.effective = effective;
	}

}
