package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * TPrepareTemplate generated by hbm2java
 */
public class TPrepareTemplate implements java.io.Serializable {

	private TPrepareTemplateId id;
	private String itemiddesc;
	private String notes;
	private String creator;
	private Date createtime;

	public TPrepareTemplate() {
	}

	public TPrepareTemplate(TPrepareTemplateId id) {
		this.id = id;
	}

	public TPrepareTemplate(TPrepareTemplateId id, String itemiddesc, String notes, String creator, Date createtime) {
		this.id = id;
		this.itemiddesc = itemiddesc;
		this.notes = notes;
		this.creator = creator;
		this.createtime = createtime;
	}

	public TPrepareTemplateId getId() {
		return this.id;
	}

	public void setId(TPrepareTemplateId id) {
		this.id = id;
	}

	public String getItemiddesc() {
		return this.itemiddesc;
	}

	public void setItemiddesc(String itemiddesc) {
		this.itemiddesc = itemiddesc;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

}
