package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;

/**
 * TRccpDetail generated by hbm2java
 */
public class TRccpDetail implements java.io.Serializable {

	private String uniqueid;
	private TRccpHeader TRccpHeader;
	private String mastershopuid;
	private String deviceClassUid;
	private String workcenteruid;
	private BigDecimal resUtilize;
	private BigDecimal resLoad;
	private BigDecimal totalcapacitytime;
	private BigDecimal totalsetuptime;
	private BigDecimal totalruntime;
	private BigDecimal totalrequiretime;
	private String segment;
	private String segmentType;

	public TRccpDetail() {
	}

	public TRccpDetail(String uniqueid, TRccpHeader TRccpHeader, String workcenteruid) {
		this.uniqueid = uniqueid;
		this.TRccpHeader = TRccpHeader;
		this.workcenteruid = workcenteruid;
	}

	public TRccpDetail(String uniqueid, TRccpHeader TRccpHeader, String mastershopuid, String deviceClassUid,
			String workcenteruid, BigDecimal resUtilize, BigDecimal resLoad, BigDecimal totalcapacitytime,
			BigDecimal totalsetuptime, BigDecimal totalruntime, BigDecimal totalrequiretime, String segment,
			String segmentType) {
		this.uniqueid = uniqueid;
		this.TRccpHeader = TRccpHeader;
		this.mastershopuid = mastershopuid;
		this.deviceClassUid = deviceClassUid;
		this.workcenteruid = workcenteruid;
		this.resUtilize = resUtilize;
		this.resLoad = resLoad;
		this.totalcapacitytime = totalcapacitytime;
		this.totalsetuptime = totalsetuptime;
		this.totalruntime = totalruntime;
		this.totalrequiretime = totalrequiretime;
		this.segment = segment;
		this.segmentType = segmentType;
	}

	public String getUniqueid() {
		return this.uniqueid;
	}

	public void setUniqueid(String uniqueid) {
		this.uniqueid = uniqueid;
	}

	public TRccpHeader getTRccpHeader() {
		return this.TRccpHeader;
	}

	public void setTRccpHeader(TRccpHeader TRccpHeader) {
		this.TRccpHeader = TRccpHeader;
	}

	public String getMastershopuid() {
		return this.mastershopuid;
	}

	public void setMastershopuid(String mastershopuid) {
		this.mastershopuid = mastershopuid;
	}

	public String getDeviceClassUid() {
		return this.deviceClassUid;
	}

	public void setDeviceClassUid(String deviceClassUid) {
		this.deviceClassUid = deviceClassUid;
	}

	public String getWorkcenteruid() {
		return this.workcenteruid;
	}

	public void setWorkcenteruid(String workcenteruid) {
		this.workcenteruid = workcenteruid;
	}

	public BigDecimal getResUtilize() {
		return this.resUtilize;
	}

	public void setResUtilize(BigDecimal resUtilize) {
		this.resUtilize = resUtilize;
	}

	public BigDecimal getResLoad() {
		return this.resLoad;
	}

	public void setResLoad(BigDecimal resLoad) {
		this.resLoad = resLoad;
	}

	public BigDecimal getTotalcapacitytime() {
		return this.totalcapacitytime;
	}

	public void setTotalcapacitytime(BigDecimal totalcapacitytime) {
		this.totalcapacitytime = totalcapacitytime;
	}

	public BigDecimal getTotalsetuptime() {
		return this.totalsetuptime;
	}

	public void setTotalsetuptime(BigDecimal totalsetuptime) {
		this.totalsetuptime = totalsetuptime;
	}

	public BigDecimal getTotalruntime() {
		return this.totalruntime;
	}

	public void setTotalruntime(BigDecimal totalruntime) {
		this.totalruntime = totalruntime;
	}

	public BigDecimal getTotalrequiretime() {
		return this.totalrequiretime;
	}

	public void setTotalrequiretime(BigDecimal totalrequiretime) {
		this.totalrequiretime = totalrequiretime;
	}

	public String getSegment() {
		return this.segment;
	}

	public void setSegment(String segment) {
		this.segment = segment;
	}

	public String getSegmentType() {
		return this.segmentType;
	}

	public void setSegmentType(String segmentType) {
		this.segmentType = segmentType;
	}

}
