package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

/**
 * TScheduleLinksId generated by hbm2java
 */
public class TScheduleLinksId implements java.io.Serializable {

	private String scheduleuid;
	private String preduid;
	private String succuid;

	public TScheduleLinksId() {
	}

	public TScheduleLinksId(String scheduleuid, String preduid, String succuid) {
		this.scheduleuid = scheduleuid;
		this.preduid = preduid;
		this.succuid = succuid;
	}

	public String getScheduleuid() {
		return this.scheduleuid;
	}

	public void setScheduleuid(String scheduleuid) {
		this.scheduleuid = scheduleuid;
	}

	public String getPreduid() {
		return this.preduid;
	}

	public void setPreduid(String preduid) {
		this.preduid = preduid;
	}

	public String getSuccuid() {
		return this.succuid;
	}

	public void setSuccuid(String succuid) {
		this.succuid = succuid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TScheduleLinksId))
			return false;
		TScheduleLinksId castOther = (TScheduleLinksId) other;

		return ((this.getScheduleuid() == castOther.getScheduleuid()) || (this.getScheduleuid() != null
				&& castOther.getScheduleuid() != null && this.getScheduleuid().equals(castOther.getScheduleuid())))
				&& ((this.getPreduid() == castOther.getPreduid()) || (this.getPreduid() != null
						&& castOther.getPreduid() != null && this.getPreduid().equals(castOther.getPreduid())))
				&& ((this.getSuccuid() == castOther.getSuccuid()) || (this.getSuccuid() != null
						&& castOther.getSuccuid() != null && this.getSuccuid().equals(castOther.getSuccuid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getScheduleuid() == null ? 0 : this.getScheduleuid().hashCode());
		result = 37 * result + (getPreduid() == null ? 0 : this.getPreduid().hashCode());
		result = 37 * result + (getSuccuid() == null ? 0 : this.getSuccuid().hashCode());
		return result;
	}

}
