package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * TTaskPart generated by hbm2java
 */
public class TTaskPart implements java.io.Serializable {

	private TTaskPartId id;
	private TTasks TTasks;
	private BigDecimal qtyreq;
	private Long reqtype;
	private BigDecimal allocatedqty;
	private Byte isineffect;
	private Date createtime;
	private String creator;
	private BigDecimal singlein;
	private BigDecimal singleout;
	private String uniqueId;
	private Date satisfydate;
	private String notes;
	private BigDecimal preassQty;
	private String preassEmp;
	private Date preassDate;
	private String warehouseid;
	private BigDecimal applyQty;
	private String prepareEmployeeid;
	private String prepareWarehouseid;
	private Byte prepareState;
	private long preassLevel;

	public TTaskPart() {
	}

	public TTaskPart(TTaskPartId id, TTasks TTasks, String uniqueId, long preassLevel) {
		this.id = id;
		this.TTasks = TTasks;
		this.uniqueId = uniqueId;
		this.preassLevel = preassLevel;
	}

	public TTaskPart(TTaskPartId id, TTasks TTasks, BigDecimal qtyreq, Long reqtype, BigDecimal allocatedqty,
			Byte isineffect, Date createtime, String creator, BigDecimal singlein, BigDecimal singleout,
			String uniqueId, Date satisfydate, String notes, BigDecimal preassQty, String preassEmp, Date preassDate,
			String warehouseid, BigDecimal applyQty, String prepareEmployeeid, String prepareWarehouseid,
			Byte prepareState, long preassLevel) {
		this.id = id;
		this.TTasks = TTasks;
		this.qtyreq = qtyreq;
		this.reqtype = reqtype;
		this.allocatedqty = allocatedqty;
		this.isineffect = isineffect;
		this.createtime = createtime;
		this.creator = creator;
		this.singlein = singlein;
		this.singleout = singleout;
		this.uniqueId = uniqueId;
		this.satisfydate = satisfydate;
		this.notes = notes;
		this.preassQty = preassQty;
		this.preassEmp = preassEmp;
		this.preassDate = preassDate;
		this.warehouseid = warehouseid;
		this.applyQty = applyQty;
		this.prepareEmployeeid = prepareEmployeeid;
		this.prepareWarehouseid = prepareWarehouseid;
		this.prepareState = prepareState;
		this.preassLevel = preassLevel;
	}

	public TTaskPartId getId() {
		return this.id;
	}

	public void setId(TTaskPartId id) {
		this.id = id;
	}

	public TTasks getTTasks() {
		return this.TTasks;
	}

	public void setTTasks(TTasks TTasks) {
		this.TTasks = TTasks;
	}

	public BigDecimal getQtyreq() {
		return this.qtyreq;
	}

	public void setQtyreq(BigDecimal qtyreq) {
		this.qtyreq = qtyreq;
	}

	public Long getReqtype() {
		return this.reqtype;
	}

	public void setReqtype(Long reqtype) {
		this.reqtype = reqtype;
	}

	public BigDecimal getAllocatedqty() {
		return this.allocatedqty;
	}

	public void setAllocatedqty(BigDecimal allocatedqty) {
		this.allocatedqty = allocatedqty;
	}

	public Byte getIsineffect() {
		return this.isineffect;
	}

	public void setIsineffect(Byte isineffect) {
		this.isineffect = isineffect;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public BigDecimal getSinglein() {
		return this.singlein;
	}

	public void setSinglein(BigDecimal singlein) {
		this.singlein = singlein;
	}

	public BigDecimal getSingleout() {
		return this.singleout;
	}

	public void setSingleout(BigDecimal singleout) {
		this.singleout = singleout;
	}

	public String getUniqueId() {
		return this.uniqueId;
	}

	public void setUniqueId(String uniqueId) {
		this.uniqueId = uniqueId;
	}

	public Date getSatisfydate() {
		return this.satisfydate;
	}

	public void setSatisfydate(Date satisfydate) {
		this.satisfydate = satisfydate;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public BigDecimal getPreassQty() {
		return this.preassQty;
	}

	public void setPreassQty(BigDecimal preassQty) {
		this.preassQty = preassQty;
	}

	public String getPreassEmp() {
		return this.preassEmp;
	}

	public void setPreassEmp(String preassEmp) {
		this.preassEmp = preassEmp;
	}

	public Date getPreassDate() {
		return this.preassDate;
	}

	public void setPreassDate(Date preassDate) {
		this.preassDate = preassDate;
	}

	public String getWarehouseid() {
		return this.warehouseid;
	}

	public void setWarehouseid(String warehouseid) {
		this.warehouseid = warehouseid;
	}

	public BigDecimal getApplyQty() {
		return this.applyQty;
	}

	public void setApplyQty(BigDecimal applyQty) {
		this.applyQty = applyQty;
	}

	public String getPrepareEmployeeid() {
		return this.prepareEmployeeid;
	}

	public void setPrepareEmployeeid(String prepareEmployeeid) {
		this.prepareEmployeeid = prepareEmployeeid;
	}

	public String getPrepareWarehouseid() {
		return this.prepareWarehouseid;
	}

	public void setPrepareWarehouseid(String prepareWarehouseid) {
		this.prepareWarehouseid = prepareWarehouseid;
	}

	public Byte getPrepareState() {
		return this.prepareState;
	}

	public void setPrepareState(Byte prepareState) {
		this.prepareState = prepareState;
	}

	public long getPreassLevel() {
		return this.preassLevel;
	}

	public void setPreassLevel(long preassLevel) {
		this.preassLevel = preassLevel;
	}

}
