package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * TvResourcePrjId generated by hbm2java
 */
public class TvResourcePrjId implements java.io.Serializable {

	private String resuid;
	private String resname;
	private String calUid;
	private String deptid;
	private Long resourcetype;
	private String location;
	private Long numOfPooledResources;
	private Long estimatedQueueTime;
	private String estimatedQueueTimeUom;
	private Long defaultSetupTime;
	private String defaultTimeUom;
	private BigDecimal idealUtilizationLevel;
	private String idealUtilCalName;
	private String wageRatePer;
	private BigDecimal wageRatePerTime;
	private String setupMatrixId;
	private String setupSequenceId;
	private Byte setupSequenceGoback;
	private Long minimumQueueTime;
	private String minimumQueueTimeUom;
	private String modelName;
	private Long scheduleFreezeHorizon;
	private String sfhUom;
	private Long batchingHorizon;
	private String batchingHorizonUom;
	private Long batchingLookahead;
	private String batchingLookaheadUom;
	private Long latenessTolerance;
	private String latenessToleranceUom;
	private Long earlinessTolerance;
	private String earlinessToleranceUom;
	private String queueSizeMode;
	private String maxQueueSize;
	private String queueConformanceMode;
	private Long outputRateLimit;
	private String outputRateLimitPer;
	private String outputRateLimitUom;
	private Long lowRwt;
	private String lowRwtPer;
	private String lowRwtUom;
	private String highRwtUom;
	private String highRwtPer;
	private Long highRwt;
	private String acmFlag;
	private String incOvertimeCostPer;
	private String incOvertimeCostPerT;
	private Long lastMaintDate;
	private String lastMaintDateFormat;
	private String lastMaintSeqNumber;
	private Long lastMaintTime;
	private String lastMaintTimeUom;
	private Long loadSinceLastMaint;
	private String loadSinceUom;
	private Long maximumUtilLevel;
	private String minOpTimeCalName;
	private Date minQueueConfLength;
	private String minQueueConfUom;
	private Long minimumUtilLevel;
	private Byte offloadableFrom;
	private Byte offloadableTo;
	private Long overtimeBasis;
	private String obertimeBasisUom;
	private Long overtimeThreshold;
	private String overtimeThresholdUom;
	private String processedMaterialTypes;
	private String queueSizeUom;
	private Long schedulingCriticality;
	private String unitSetupCostPer;
	private BigDecimal unitSetupCostPerTime;
	private Long caoPostProcDownstream;
	private Byte keepRelatedTasksTog;
	private Long preIcpOlRuntimeRatio;
	private Byte simulHierSetups;
	private Byte ignoreForCapPlan;
	private Boolean noneneeddispatch;
	private String resourceref;
	private Byte criticalLevel;
	private BigDecimal needNc;
	private String restype;
	private BigDecimal monthplanwork;
	private Long optype;
	private String RResourceOutUid;
	private Long resstate;
	private String customerResuid;
	private String toolShankSpec;
	private String ncSysModel;
	private Long deviceTableCount;
	private String currentEmployeeid;
	private String bottleneckLevel;
	private BigDecimal resourceunits;

	public TvResourcePrjId() {
	}

	public TvResourcePrjId(String resuid, String deptid) {
		this.resuid = resuid;
		this.deptid = deptid;
	}

	public TvResourcePrjId(String resuid, String resname, String calUid, String deptid, Long resourcetype,
			String location, Long numOfPooledResources, Long estimatedQueueTime, String estimatedQueueTimeUom,
			Long defaultSetupTime, String defaultTimeUom, BigDecimal idealUtilizationLevel, String idealUtilCalName,
			String wageRatePer, BigDecimal wageRatePerTime, String setupMatrixId, String setupSequenceId,
			Byte setupSequenceGoback, Long minimumQueueTime, String minimumQueueTimeUom, String modelName,
			Long scheduleFreezeHorizon, String sfhUom, Long batchingHorizon, String batchingHorizonUom,
			Long batchingLookahead, String batchingLookaheadUom, Long latenessTolerance, String latenessToleranceUom,
			Long earlinessTolerance, String earlinessToleranceUom, String queueSizeMode, String maxQueueSize,
			String queueConformanceMode, Long outputRateLimit, String outputRateLimitPer, String outputRateLimitUom,
			Long lowRwt, String lowRwtPer, String lowRwtUom, String highRwtUom, String highRwtPer, Long highRwt,
			String acmFlag, String incOvertimeCostPer, String incOvertimeCostPerT, Long lastMaintDate,
			String lastMaintDateFormat, String lastMaintSeqNumber, Long lastMaintTime, String lastMaintTimeUom,
			Long loadSinceLastMaint, String loadSinceUom, Long maximumUtilLevel, String minOpTimeCalName,
			Date minQueueConfLength, String minQueueConfUom, Long minimumUtilLevel, Byte offloadableFrom,
			Byte offloadableTo, Long overtimeBasis, String obertimeBasisUom, Long overtimeThreshold,
			String overtimeThresholdUom, String processedMaterialTypes, String queueSizeUom, Long schedulingCriticality,
			String unitSetupCostPer, BigDecimal unitSetupCostPerTime, Long caoPostProcDownstream,
			Byte keepRelatedTasksTog, Long preIcpOlRuntimeRatio, Byte simulHierSetups, Byte ignoreForCapPlan,
			Boolean noneneeddispatch, String resourceref, Byte criticalLevel, BigDecimal needNc, String restype,
			BigDecimal monthplanwork, Long optype, String RResourceOutUid, Long resstate, String customerResuid,
			String toolShankSpec, String ncSysModel, Long deviceTableCount, String currentEmployeeid,
			String bottleneckLevel, BigDecimal resourceunits) {
		this.resuid = resuid;
		this.resname = resname;
		this.calUid = calUid;
		this.deptid = deptid;
		this.resourcetype = resourcetype;
		this.location = location;
		this.numOfPooledResources = numOfPooledResources;
		this.estimatedQueueTime = estimatedQueueTime;
		this.estimatedQueueTimeUom = estimatedQueueTimeUom;
		this.defaultSetupTime = defaultSetupTime;
		this.defaultTimeUom = defaultTimeUom;
		this.idealUtilizationLevel = idealUtilizationLevel;
		this.idealUtilCalName = idealUtilCalName;
		this.wageRatePer = wageRatePer;
		this.wageRatePerTime = wageRatePerTime;
		this.setupMatrixId = setupMatrixId;
		this.setupSequenceId = setupSequenceId;
		this.setupSequenceGoback = setupSequenceGoback;
		this.minimumQueueTime = minimumQueueTime;
		this.minimumQueueTimeUom = minimumQueueTimeUom;
		this.modelName = modelName;
		this.scheduleFreezeHorizon = scheduleFreezeHorizon;
		this.sfhUom = sfhUom;
		this.batchingHorizon = batchingHorizon;
		this.batchingHorizonUom = batchingHorizonUom;
		this.batchingLookahead = batchingLookahead;
		this.batchingLookaheadUom = batchingLookaheadUom;
		this.latenessTolerance = latenessTolerance;
		this.latenessToleranceUom = latenessToleranceUom;
		this.earlinessTolerance = earlinessTolerance;
		this.earlinessToleranceUom = earlinessToleranceUom;
		this.queueSizeMode = queueSizeMode;
		this.maxQueueSize = maxQueueSize;
		this.queueConformanceMode = queueConformanceMode;
		this.outputRateLimit = outputRateLimit;
		this.outputRateLimitPer = outputRateLimitPer;
		this.outputRateLimitUom = outputRateLimitUom;
		this.lowRwt = lowRwt;
		this.lowRwtPer = lowRwtPer;
		this.lowRwtUom = lowRwtUom;
		this.highRwtUom = highRwtUom;
		this.highRwtPer = highRwtPer;
		this.highRwt = highRwt;
		this.acmFlag = acmFlag;
		this.incOvertimeCostPer = incOvertimeCostPer;
		this.incOvertimeCostPerT = incOvertimeCostPerT;
		this.lastMaintDate = lastMaintDate;
		this.lastMaintDateFormat = lastMaintDateFormat;
		this.lastMaintSeqNumber = lastMaintSeqNumber;
		this.lastMaintTime = lastMaintTime;
		this.lastMaintTimeUom = lastMaintTimeUom;
		this.loadSinceLastMaint = loadSinceLastMaint;
		this.loadSinceUom = loadSinceUom;
		this.maximumUtilLevel = maximumUtilLevel;
		this.minOpTimeCalName = minOpTimeCalName;
		this.minQueueConfLength = minQueueConfLength;
		this.minQueueConfUom = minQueueConfUom;
		this.minimumUtilLevel = minimumUtilLevel;
		this.offloadableFrom = offloadableFrom;
		this.offloadableTo = offloadableTo;
		this.overtimeBasis = overtimeBasis;
		this.obertimeBasisUom = obertimeBasisUom;
		this.overtimeThreshold = overtimeThreshold;
		this.overtimeThresholdUom = overtimeThresholdUom;
		this.processedMaterialTypes = processedMaterialTypes;
		this.queueSizeUom = queueSizeUom;
		this.schedulingCriticality = schedulingCriticality;
		this.unitSetupCostPer = unitSetupCostPer;
		this.unitSetupCostPerTime = unitSetupCostPerTime;
		this.caoPostProcDownstream = caoPostProcDownstream;
		this.keepRelatedTasksTog = keepRelatedTasksTog;
		this.preIcpOlRuntimeRatio = preIcpOlRuntimeRatio;
		this.simulHierSetups = simulHierSetups;
		this.ignoreForCapPlan = ignoreForCapPlan;
		this.noneneeddispatch = noneneeddispatch;
		this.resourceref = resourceref;
		this.criticalLevel = criticalLevel;
		this.needNc = needNc;
		this.restype = restype;
		this.monthplanwork = monthplanwork;
		this.optype = optype;
		this.RResourceOutUid = RResourceOutUid;
		this.resstate = resstate;
		this.customerResuid = customerResuid;
		this.toolShankSpec = toolShankSpec;
		this.ncSysModel = ncSysModel;
		this.deviceTableCount = deviceTableCount;
		this.currentEmployeeid = currentEmployeeid;
		this.bottleneckLevel = bottleneckLevel;
		this.resourceunits = resourceunits;
	}

	public String getResuid() {
		return this.resuid;
	}

	public void setResuid(String resuid) {
		this.resuid = resuid;
	}

	public String getResname() {
		return this.resname;
	}

	public void setResname(String resname) {
		this.resname = resname;
	}

	public String getCalUid() {
		return this.calUid;
	}

	public void setCalUid(String calUid) {
		this.calUid = calUid;
	}

	public String getDeptid() {
		return this.deptid;
	}

	public void setDeptid(String deptid) {
		this.deptid = deptid;
	}

	public Long getResourcetype() {
		return this.resourcetype;
	}

	public void setResourcetype(Long resourcetype) {
		this.resourcetype = resourcetype;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public Long getNumOfPooledResources() {
		return this.numOfPooledResources;
	}

	public void setNumOfPooledResources(Long numOfPooledResources) {
		this.numOfPooledResources = numOfPooledResources;
	}

	public Long getEstimatedQueueTime() {
		return this.estimatedQueueTime;
	}

	public void setEstimatedQueueTime(Long estimatedQueueTime) {
		this.estimatedQueueTime = estimatedQueueTime;
	}

	public String getEstimatedQueueTimeUom() {
		return this.estimatedQueueTimeUom;
	}

	public void setEstimatedQueueTimeUom(String estimatedQueueTimeUom) {
		this.estimatedQueueTimeUom = estimatedQueueTimeUom;
	}

	public Long getDefaultSetupTime() {
		return this.defaultSetupTime;
	}

	public void setDefaultSetupTime(Long defaultSetupTime) {
		this.defaultSetupTime = defaultSetupTime;
	}

	public String getDefaultTimeUom() {
		return this.defaultTimeUom;
	}

	public void setDefaultTimeUom(String defaultTimeUom) {
		this.defaultTimeUom = defaultTimeUom;
	}

	public BigDecimal getIdealUtilizationLevel() {
		return this.idealUtilizationLevel;
	}

	public void setIdealUtilizationLevel(BigDecimal idealUtilizationLevel) {
		this.idealUtilizationLevel = idealUtilizationLevel;
	}

	public String getIdealUtilCalName() {
		return this.idealUtilCalName;
	}

	public void setIdealUtilCalName(String idealUtilCalName) {
		this.idealUtilCalName = idealUtilCalName;
	}

	public String getWageRatePer() {
		return this.wageRatePer;
	}

	public void setWageRatePer(String wageRatePer) {
		this.wageRatePer = wageRatePer;
	}

	public BigDecimal getWageRatePerTime() {
		return this.wageRatePerTime;
	}

	public void setWageRatePerTime(BigDecimal wageRatePerTime) {
		this.wageRatePerTime = wageRatePerTime;
	}

	public String getSetupMatrixId() {
		return this.setupMatrixId;
	}

	public void setSetupMatrixId(String setupMatrixId) {
		this.setupMatrixId = setupMatrixId;
	}

	public String getSetupSequenceId() {
		return this.setupSequenceId;
	}

	public void setSetupSequenceId(String setupSequenceId) {
		this.setupSequenceId = setupSequenceId;
	}

	public Byte getSetupSequenceGoback() {
		return this.setupSequenceGoback;
	}

	public void setSetupSequenceGoback(Byte setupSequenceGoback) {
		this.setupSequenceGoback = setupSequenceGoback;
	}

	public Long getMinimumQueueTime() {
		return this.minimumQueueTime;
	}

	public void setMinimumQueueTime(Long minimumQueueTime) {
		this.minimumQueueTime = minimumQueueTime;
	}

	public String getMinimumQueueTimeUom() {
		return this.minimumQueueTimeUom;
	}

	public void setMinimumQueueTimeUom(String minimumQueueTimeUom) {
		this.minimumQueueTimeUom = minimumQueueTimeUom;
	}

	public String getModelName() {
		return this.modelName;
	}

	public void setModelName(String modelName) {
		this.modelName = modelName;
	}

	public Long getScheduleFreezeHorizon() {
		return this.scheduleFreezeHorizon;
	}

	public void setScheduleFreezeHorizon(Long scheduleFreezeHorizon) {
		this.scheduleFreezeHorizon = scheduleFreezeHorizon;
	}

	public String getSfhUom() {
		return this.sfhUom;
	}

	public void setSfhUom(String sfhUom) {
		this.sfhUom = sfhUom;
	}

	public Long getBatchingHorizon() {
		return this.batchingHorizon;
	}

	public void setBatchingHorizon(Long batchingHorizon) {
		this.batchingHorizon = batchingHorizon;
	}

	public String getBatchingHorizonUom() {
		return this.batchingHorizonUom;
	}

	public void setBatchingHorizonUom(String batchingHorizonUom) {
		this.batchingHorizonUom = batchingHorizonUom;
	}

	public Long getBatchingLookahead() {
		return this.batchingLookahead;
	}

	public void setBatchingLookahead(Long batchingLookahead) {
		this.batchingLookahead = batchingLookahead;
	}

	public String getBatchingLookaheadUom() {
		return this.batchingLookaheadUom;
	}

	public void setBatchingLookaheadUom(String batchingLookaheadUom) {
		this.batchingLookaheadUom = batchingLookaheadUom;
	}

	public Long getLatenessTolerance() {
		return this.latenessTolerance;
	}

	public void setLatenessTolerance(Long latenessTolerance) {
		this.latenessTolerance = latenessTolerance;
	}

	public String getLatenessToleranceUom() {
		return this.latenessToleranceUom;
	}

	public void setLatenessToleranceUom(String latenessToleranceUom) {
		this.latenessToleranceUom = latenessToleranceUom;
	}

	public Long getEarlinessTolerance() {
		return this.earlinessTolerance;
	}

	public void setEarlinessTolerance(Long earlinessTolerance) {
		this.earlinessTolerance = earlinessTolerance;
	}

	public String getEarlinessToleranceUom() {
		return this.earlinessToleranceUom;
	}

	public void setEarlinessToleranceUom(String earlinessToleranceUom) {
		this.earlinessToleranceUom = earlinessToleranceUom;
	}

	public String getQueueSizeMode() {
		return this.queueSizeMode;
	}

	public void setQueueSizeMode(String queueSizeMode) {
		this.queueSizeMode = queueSizeMode;
	}

	public String getMaxQueueSize() {
		return this.maxQueueSize;
	}

	public void setMaxQueueSize(String maxQueueSize) {
		this.maxQueueSize = maxQueueSize;
	}

	public String getQueueConformanceMode() {
		return this.queueConformanceMode;
	}

	public void setQueueConformanceMode(String queueConformanceMode) {
		this.queueConformanceMode = queueConformanceMode;
	}

	public Long getOutputRateLimit() {
		return this.outputRateLimit;
	}

	public void setOutputRateLimit(Long outputRateLimit) {
		this.outputRateLimit = outputRateLimit;
	}

	public String getOutputRateLimitPer() {
		return this.outputRateLimitPer;
	}

	public void setOutputRateLimitPer(String outputRateLimitPer) {
		this.outputRateLimitPer = outputRateLimitPer;
	}

	public String getOutputRateLimitUom() {
		return this.outputRateLimitUom;
	}

	public void setOutputRateLimitUom(String outputRateLimitUom) {
		this.outputRateLimitUom = outputRateLimitUom;
	}

	public Long getLowRwt() {
		return this.lowRwt;
	}

	public void setLowRwt(Long lowRwt) {
		this.lowRwt = lowRwt;
	}

	public String getLowRwtPer() {
		return this.lowRwtPer;
	}

	public void setLowRwtPer(String lowRwtPer) {
		this.lowRwtPer = lowRwtPer;
	}

	public String getLowRwtUom() {
		return this.lowRwtUom;
	}

	public void setLowRwtUom(String lowRwtUom) {
		this.lowRwtUom = lowRwtUom;
	}

	public String getHighRwtUom() {
		return this.highRwtUom;
	}

	public void setHighRwtUom(String highRwtUom) {
		this.highRwtUom = highRwtUom;
	}

	public String getHighRwtPer() {
		return this.highRwtPer;
	}

	public void setHighRwtPer(String highRwtPer) {
		this.highRwtPer = highRwtPer;
	}

	public Long getHighRwt() {
		return this.highRwt;
	}

	public void setHighRwt(Long highRwt) {
		this.highRwt = highRwt;
	}

	public String getAcmFlag() {
		return this.acmFlag;
	}

	public void setAcmFlag(String acmFlag) {
		this.acmFlag = acmFlag;
	}

	public String getIncOvertimeCostPer() {
		return this.incOvertimeCostPer;
	}

	public void setIncOvertimeCostPer(String incOvertimeCostPer) {
		this.incOvertimeCostPer = incOvertimeCostPer;
	}

	public String getIncOvertimeCostPerT() {
		return this.incOvertimeCostPerT;
	}

	public void setIncOvertimeCostPerT(String incOvertimeCostPerT) {
		this.incOvertimeCostPerT = incOvertimeCostPerT;
	}

	public Long getLastMaintDate() {
		return this.lastMaintDate;
	}

	public void setLastMaintDate(Long lastMaintDate) {
		this.lastMaintDate = lastMaintDate;
	}

	public String getLastMaintDateFormat() {
		return this.lastMaintDateFormat;
	}

	public void setLastMaintDateFormat(String lastMaintDateFormat) {
		this.lastMaintDateFormat = lastMaintDateFormat;
	}

	public String getLastMaintSeqNumber() {
		return this.lastMaintSeqNumber;
	}

	public void setLastMaintSeqNumber(String lastMaintSeqNumber) {
		this.lastMaintSeqNumber = lastMaintSeqNumber;
	}

	public Long getLastMaintTime() {
		return this.lastMaintTime;
	}

	public void setLastMaintTime(Long lastMaintTime) {
		this.lastMaintTime = lastMaintTime;
	}

	public String getLastMaintTimeUom() {
		return this.lastMaintTimeUom;
	}

	public void setLastMaintTimeUom(String lastMaintTimeUom) {
		this.lastMaintTimeUom = lastMaintTimeUom;
	}

	public Long getLoadSinceLastMaint() {
		return this.loadSinceLastMaint;
	}

	public void setLoadSinceLastMaint(Long loadSinceLastMaint) {
		this.loadSinceLastMaint = loadSinceLastMaint;
	}

	public String getLoadSinceUom() {
		return this.loadSinceUom;
	}

	public void setLoadSinceUom(String loadSinceUom) {
		this.loadSinceUom = loadSinceUom;
	}

	public Long getMaximumUtilLevel() {
		return this.maximumUtilLevel;
	}

	public void setMaximumUtilLevel(Long maximumUtilLevel) {
		this.maximumUtilLevel = maximumUtilLevel;
	}

	public String getMinOpTimeCalName() {
		return this.minOpTimeCalName;
	}

	public void setMinOpTimeCalName(String minOpTimeCalName) {
		this.minOpTimeCalName = minOpTimeCalName;
	}

	public Date getMinQueueConfLength() {
		return this.minQueueConfLength;
	}

	public void setMinQueueConfLength(Date minQueueConfLength) {
		this.minQueueConfLength = minQueueConfLength;
	}

	public String getMinQueueConfUom() {
		return this.minQueueConfUom;
	}

	public void setMinQueueConfUom(String minQueueConfUom) {
		this.minQueueConfUom = minQueueConfUom;
	}

	public Long getMinimumUtilLevel() {
		return this.minimumUtilLevel;
	}

	public void setMinimumUtilLevel(Long minimumUtilLevel) {
		this.minimumUtilLevel = minimumUtilLevel;
	}

	public Byte getOffloadableFrom() {
		return this.offloadableFrom;
	}

	public void setOffloadableFrom(Byte offloadableFrom) {
		this.offloadableFrom = offloadableFrom;
	}

	public Byte getOffloadableTo() {
		return this.offloadableTo;
	}

	public void setOffloadableTo(Byte offloadableTo) {
		this.offloadableTo = offloadableTo;
	}

	public Long getOvertimeBasis() {
		return this.overtimeBasis;
	}

	public void setOvertimeBasis(Long overtimeBasis) {
		this.overtimeBasis = overtimeBasis;
	}

	public String getObertimeBasisUom() {
		return this.obertimeBasisUom;
	}

	public void setObertimeBasisUom(String obertimeBasisUom) {
		this.obertimeBasisUom = obertimeBasisUom;
	}

	public Long getOvertimeThreshold() {
		return this.overtimeThreshold;
	}

	public void setOvertimeThreshold(Long overtimeThreshold) {
		this.overtimeThreshold = overtimeThreshold;
	}

	public String getOvertimeThresholdUom() {
		return this.overtimeThresholdUom;
	}

	public void setOvertimeThresholdUom(String overtimeThresholdUom) {
		this.overtimeThresholdUom = overtimeThresholdUom;
	}

	public String getProcessedMaterialTypes() {
		return this.processedMaterialTypes;
	}

	public void setProcessedMaterialTypes(String processedMaterialTypes) {
		this.processedMaterialTypes = processedMaterialTypes;
	}

	public String getQueueSizeUom() {
		return this.queueSizeUom;
	}

	public void setQueueSizeUom(String queueSizeUom) {
		this.queueSizeUom = queueSizeUom;
	}

	public Long getSchedulingCriticality() {
		return this.schedulingCriticality;
	}

	public void setSchedulingCriticality(Long schedulingCriticality) {
		this.schedulingCriticality = schedulingCriticality;
	}

	public String getUnitSetupCostPer() {
		return this.unitSetupCostPer;
	}

	public void setUnitSetupCostPer(String unitSetupCostPer) {
		this.unitSetupCostPer = unitSetupCostPer;
	}

	public BigDecimal getUnitSetupCostPerTime() {
		return this.unitSetupCostPerTime;
	}

	public void setUnitSetupCostPerTime(BigDecimal unitSetupCostPerTime) {
		this.unitSetupCostPerTime = unitSetupCostPerTime;
	}

	public Long getCaoPostProcDownstream() {
		return this.caoPostProcDownstream;
	}

	public void setCaoPostProcDownstream(Long caoPostProcDownstream) {
		this.caoPostProcDownstream = caoPostProcDownstream;
	}

	public Byte getKeepRelatedTasksTog() {
		return this.keepRelatedTasksTog;
	}

	public void setKeepRelatedTasksTog(Byte keepRelatedTasksTog) {
		this.keepRelatedTasksTog = keepRelatedTasksTog;
	}

	public Long getPreIcpOlRuntimeRatio() {
		return this.preIcpOlRuntimeRatio;
	}

	public void setPreIcpOlRuntimeRatio(Long preIcpOlRuntimeRatio) {
		this.preIcpOlRuntimeRatio = preIcpOlRuntimeRatio;
	}

	public Byte getSimulHierSetups() {
		return this.simulHierSetups;
	}

	public void setSimulHierSetups(Byte simulHierSetups) {
		this.simulHierSetups = simulHierSetups;
	}

	public Byte getIgnoreForCapPlan() {
		return this.ignoreForCapPlan;
	}

	public void setIgnoreForCapPlan(Byte ignoreForCapPlan) {
		this.ignoreForCapPlan = ignoreForCapPlan;
	}

	public Boolean getNoneneeddispatch() {
		return this.noneneeddispatch;
	}

	public void setNoneneeddispatch(Boolean noneneeddispatch) {
		this.noneneeddispatch = noneneeddispatch;
	}

	public String getResourceref() {
		return this.resourceref;
	}

	public void setResourceref(String resourceref) {
		this.resourceref = resourceref;
	}

	public Byte getCriticalLevel() {
		return this.criticalLevel;
	}

	public void setCriticalLevel(Byte criticalLevel) {
		this.criticalLevel = criticalLevel;
	}

	public BigDecimal getNeedNc() {
		return this.needNc;
	}

	public void setNeedNc(BigDecimal needNc) {
		this.needNc = needNc;
	}

	public String getRestype() {
		return this.restype;
	}

	public void setRestype(String restype) {
		this.restype = restype;
	}

	public BigDecimal getMonthplanwork() {
		return this.monthplanwork;
	}

	public void setMonthplanwork(BigDecimal monthplanwork) {
		this.monthplanwork = monthplanwork;
	}

	public Long getOptype() {
		return this.optype;
	}

	public void setOptype(Long optype) {
		this.optype = optype;
	}

	public String getRResourceOutUid() {
		return this.RResourceOutUid;
	}

	public void setRResourceOutUid(String RResourceOutUid) {
		this.RResourceOutUid = RResourceOutUid;
	}

	public Long getResstate() {
		return this.resstate;
	}

	public void setResstate(Long resstate) {
		this.resstate = resstate;
	}

	public String getCustomerResuid() {
		return this.customerResuid;
	}

	public void setCustomerResuid(String customerResuid) {
		this.customerResuid = customerResuid;
	}

	public String getToolShankSpec() {
		return this.toolShankSpec;
	}

	public void setToolShankSpec(String toolShankSpec) {
		this.toolShankSpec = toolShankSpec;
	}

	public String getNcSysModel() {
		return this.ncSysModel;
	}

	public void setNcSysModel(String ncSysModel) {
		this.ncSysModel = ncSysModel;
	}

	public Long getDeviceTableCount() {
		return this.deviceTableCount;
	}

	public void setDeviceTableCount(Long deviceTableCount) {
		this.deviceTableCount = deviceTableCount;
	}

	public String getCurrentEmployeeid() {
		return this.currentEmployeeid;
	}

	public void setCurrentEmployeeid(String currentEmployeeid) {
		this.currentEmployeeid = currentEmployeeid;
	}

	public String getBottleneckLevel() {
		return this.bottleneckLevel;
	}

	public void setBottleneckLevel(String bottleneckLevel) {
		this.bottleneckLevel = bottleneckLevel;
	}

	public BigDecimal getResourceunits() {
		return this.resourceunits;
	}

	public void setResourceunits(BigDecimal resourceunits) {
		this.resourceunits = resourceunits;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TvResourcePrjId))
			return false;
		TvResourcePrjId castOther = (TvResourcePrjId) other;

		return ((this.getResuid() == castOther.getResuid()) || (this.getResuid() != null
				&& castOther.getResuid() != null && this.getResuid().equals(castOther.getResuid())))
				&& ((this.getResname() == castOther.getResname()) || (this.getResname() != null
						&& castOther.getResname() != null && this.getResname().equals(castOther.getResname())))
				&& ((this.getCalUid() == castOther.getCalUid()) || (this.getCalUid() != null
						&& castOther.getCalUid() != null && this.getCalUid().equals(castOther.getCalUid())))
				&& ((this.getDeptid() == castOther.getDeptid()) || (this.getDeptid() != null
						&& castOther.getDeptid() != null && this.getDeptid().equals(castOther.getDeptid())))
				&& ((this.getResourcetype() == castOther.getResourcetype())
						|| (this.getResourcetype() != null && castOther.getResourcetype() != null
								&& this.getResourcetype().equals(castOther.getResourcetype())))
				&& ((this.getLocation() == castOther.getLocation()) || (this.getLocation() != null
						&& castOther.getLocation() != null && this.getLocation().equals(castOther.getLocation())))
				&& ((this.getNumOfPooledResources() == castOther.getNumOfPooledResources())
						|| (this.getNumOfPooledResources() != null && castOther.getNumOfPooledResources() != null
								&& this.getNumOfPooledResources().equals(castOther.getNumOfPooledResources())))
				&& ((this.getEstimatedQueueTime() == castOther.getEstimatedQueueTime())
						|| (this.getEstimatedQueueTime() != null && castOther.getEstimatedQueueTime() != null
								&& this.getEstimatedQueueTime().equals(castOther.getEstimatedQueueTime())))
				&& ((this.getEstimatedQueueTimeUom() == castOther.getEstimatedQueueTimeUom())
						|| (this.getEstimatedQueueTimeUom() != null && castOther.getEstimatedQueueTimeUom() != null
								&& this.getEstimatedQueueTimeUom().equals(castOther.getEstimatedQueueTimeUom())))
				&& ((this.getDefaultSetupTime() == castOther.getDefaultSetupTime())
						|| (this.getDefaultSetupTime() != null && castOther.getDefaultSetupTime() != null
								&& this.getDefaultSetupTime().equals(castOther.getDefaultSetupTime())))
				&& ((this.getDefaultTimeUom() == castOther.getDefaultTimeUom())
						|| (this.getDefaultTimeUom() != null && castOther.getDefaultTimeUom() != null
								&& this.getDefaultTimeUom().equals(castOther.getDefaultTimeUom())))
				&& ((this.getIdealUtilizationLevel() == castOther.getIdealUtilizationLevel())
						|| (this.getIdealUtilizationLevel() != null && castOther.getIdealUtilizationLevel() != null
								&& this.getIdealUtilizationLevel().equals(castOther.getIdealUtilizationLevel())))
				&& ((this.getIdealUtilCalName() == castOther.getIdealUtilCalName())
						|| (this.getIdealUtilCalName() != null && castOther.getIdealUtilCalName() != null
								&& this.getIdealUtilCalName().equals(castOther.getIdealUtilCalName())))
				&& ((this.getWageRatePer() == castOther.getWageRatePer())
						|| (this.getWageRatePer() != null && castOther.getWageRatePer() != null
								&& this.getWageRatePer().equals(castOther.getWageRatePer())))
				&& ((this.getWageRatePerTime() == castOther.getWageRatePerTime())
						|| (this.getWageRatePerTime() != null && castOther.getWageRatePerTime() != null
								&& this.getWageRatePerTime().equals(castOther.getWageRatePerTime())))
				&& ((this.getSetupMatrixId() == castOther.getSetupMatrixId())
						|| (this.getSetupMatrixId() != null && castOther.getSetupMatrixId() != null
								&& this.getSetupMatrixId().equals(castOther.getSetupMatrixId())))
				&& ((this.getSetupSequenceId() == castOther.getSetupSequenceId())
						|| (this.getSetupSequenceId() != null && castOther.getSetupSequenceId() != null
								&& this.getSetupSequenceId().equals(castOther.getSetupSequenceId())))
				&& ((this.getSetupSequenceGoback() == castOther.getSetupSequenceGoback())
						|| (this.getSetupSequenceGoback() != null && castOther.getSetupSequenceGoback() != null
								&& this.getSetupSequenceGoback().equals(castOther.getSetupSequenceGoback())))
				&& ((this.getMinimumQueueTime() == castOther.getMinimumQueueTime())
						|| (this.getMinimumQueueTime() != null && castOther.getMinimumQueueTime() != null
								&& this.getMinimumQueueTime().equals(castOther.getMinimumQueueTime())))
				&& ((this.getMinimumQueueTimeUom() == castOther.getMinimumQueueTimeUom())
						|| (this.getMinimumQueueTimeUom() != null && castOther.getMinimumQueueTimeUom() != null
								&& this.getMinimumQueueTimeUom().equals(castOther.getMinimumQueueTimeUom())))
				&& ((this.getModelName() == castOther.getModelName()) || (this.getModelName() != null
						&& castOther.getModelName() != null && this.getModelName().equals(castOther.getModelName())))
				&& ((this.getScheduleFreezeHorizon() == castOther.getScheduleFreezeHorizon())
						|| (this.getScheduleFreezeHorizon() != null && castOther.getScheduleFreezeHorizon() != null
								&& this.getScheduleFreezeHorizon().equals(castOther.getScheduleFreezeHorizon())))
				&& ((this.getSfhUom() == castOther.getSfhUom()) || (this.getSfhUom() != null
						&& castOther.getSfhUom() != null && this.getSfhUom().equals(castOther.getSfhUom())))
				&& ((this.getBatchingHorizon() == castOther.getBatchingHorizon())
						|| (this.getBatchingHorizon() != null && castOther.getBatchingHorizon() != null
								&& this.getBatchingHorizon().equals(castOther.getBatchingHorizon())))
				&& ((this.getBatchingHorizonUom() == castOther.getBatchingHorizonUom())
						|| (this.getBatchingHorizonUom() != null && castOther.getBatchingHorizonUom() != null
								&& this.getBatchingHorizonUom().equals(castOther.getBatchingHorizonUom())))
				&& ((this.getBatchingLookahead() == castOther.getBatchingLookahead())
						|| (this.getBatchingLookahead() != null && castOther.getBatchingLookahead() != null
								&& this.getBatchingLookahead().equals(castOther.getBatchingLookahead())))
				&& ((this.getBatchingLookaheadUom() == castOther.getBatchingLookaheadUom())
						|| (this.getBatchingLookaheadUom() != null && castOther.getBatchingLookaheadUom() != null
								&& this.getBatchingLookaheadUom().equals(castOther.getBatchingLookaheadUom())))
				&& ((this.getLatenessTolerance() == castOther.getLatenessTolerance())
						|| (this.getLatenessTolerance() != null && castOther.getLatenessTolerance() != null
								&& this.getLatenessTolerance().equals(castOther.getLatenessTolerance())))
				&& ((this.getLatenessToleranceUom() == castOther.getLatenessToleranceUom())
						|| (this.getLatenessToleranceUom() != null && castOther.getLatenessToleranceUom() != null
								&& this.getLatenessToleranceUom().equals(castOther.getLatenessToleranceUom())))
				&& ((this.getEarlinessTolerance() == castOther.getEarlinessTolerance())
						|| (this.getEarlinessTolerance() != null && castOther.getEarlinessTolerance() != null
								&& this.getEarlinessTolerance().equals(castOther.getEarlinessTolerance())))
				&& ((this.getEarlinessToleranceUom() == castOther.getEarlinessToleranceUom())
						|| (this.getEarlinessToleranceUom() != null && castOther.getEarlinessToleranceUom() != null
								&& this.getEarlinessToleranceUom().equals(castOther.getEarlinessToleranceUom())))
				&& ((this.getQueueSizeMode() == castOther.getQueueSizeMode())
						|| (this.getQueueSizeMode() != null && castOther.getQueueSizeMode() != null
								&& this.getQueueSizeMode().equals(castOther.getQueueSizeMode())))
				&& ((this.getMaxQueueSize() == castOther.getMaxQueueSize())
						|| (this.getMaxQueueSize() != null && castOther.getMaxQueueSize() != null
								&& this.getMaxQueueSize().equals(castOther.getMaxQueueSize())))
				&& ((this.getQueueConformanceMode() == castOther.getQueueConformanceMode())
						|| (this.getQueueConformanceMode() != null && castOther.getQueueConformanceMode() != null
								&& this.getQueueConformanceMode().equals(castOther.getQueueConformanceMode())))
				&& ((this.getOutputRateLimit() == castOther.getOutputRateLimit())
						|| (this.getOutputRateLimit() != null && castOther.getOutputRateLimit() != null
								&& this.getOutputRateLimit().equals(castOther.getOutputRateLimit())))
				&& ((this.getOutputRateLimitPer() == castOther.getOutputRateLimitPer())
						|| (this.getOutputRateLimitPer() != null && castOther.getOutputRateLimitPer() != null
								&& this.getOutputRateLimitPer().equals(castOther.getOutputRateLimitPer())))
				&& ((this.getOutputRateLimitUom() == castOther.getOutputRateLimitUom())
						|| (this.getOutputRateLimitUom() != null && castOther.getOutputRateLimitUom() != null
								&& this.getOutputRateLimitUom().equals(castOther.getOutputRateLimitUom())))
				&& ((this.getLowRwt() == castOther.getLowRwt()) || (this.getLowRwt() != null
						&& castOther.getLowRwt() != null && this.getLowRwt().equals(castOther.getLowRwt())))
				&& ((this.getLowRwtPer() == castOther.getLowRwtPer()) || (this.getLowRwtPer() != null
						&& castOther.getLowRwtPer() != null && this.getLowRwtPer().equals(castOther.getLowRwtPer())))
				&& ((this.getLowRwtUom() == castOther.getLowRwtUom()) || (this.getLowRwtUom() != null
						&& castOther.getLowRwtUom() != null && this.getLowRwtUom().equals(castOther.getLowRwtUom())))
				&& ((this.getHighRwtUom() == castOther.getHighRwtUom()) || (this.getHighRwtUom() != null
						&& castOther.getHighRwtUom() != null && this.getHighRwtUom().equals(castOther.getHighRwtUom())))
				&& ((this.getHighRwtPer() == castOther.getHighRwtPer()) || (this.getHighRwtPer() != null
						&& castOther.getHighRwtPer() != null && this.getHighRwtPer().equals(castOther.getHighRwtPer())))
				&& ((this.getHighRwt() == castOther.getHighRwt()) || (this.getHighRwt() != null
						&& castOther.getHighRwt() != null && this.getHighRwt().equals(castOther.getHighRwt())))
				&& ((this.getAcmFlag() == castOther.getAcmFlag()) || (this.getAcmFlag() != null
						&& castOther.getAcmFlag() != null && this.getAcmFlag().equals(castOther.getAcmFlag())))
				&& ((this.getIncOvertimeCostPer() == castOther.getIncOvertimeCostPer())
						|| (this.getIncOvertimeCostPer() != null && castOther.getIncOvertimeCostPer() != null
								&& this.getIncOvertimeCostPer().equals(castOther.getIncOvertimeCostPer())))
				&& ((this.getIncOvertimeCostPerT() == castOther.getIncOvertimeCostPerT())
						|| (this.getIncOvertimeCostPerT() != null && castOther.getIncOvertimeCostPerT() != null
								&& this.getIncOvertimeCostPerT().equals(castOther.getIncOvertimeCostPerT())))
				&& ((this.getLastMaintDate() == castOther.getLastMaintDate())
						|| (this.getLastMaintDate() != null && castOther.getLastMaintDate() != null
								&& this.getLastMaintDate().equals(castOther.getLastMaintDate())))
				&& ((this.getLastMaintDateFormat() == castOther.getLastMaintDateFormat())
						|| (this.getLastMaintDateFormat() != null && castOther.getLastMaintDateFormat() != null
								&& this.getLastMaintDateFormat().equals(castOther.getLastMaintDateFormat())))
				&& ((this.getLastMaintSeqNumber() == castOther.getLastMaintSeqNumber())
						|| (this.getLastMaintSeqNumber() != null && castOther.getLastMaintSeqNumber() != null
								&& this.getLastMaintSeqNumber().equals(castOther.getLastMaintSeqNumber())))
				&& ((this.getLastMaintTime() == castOther.getLastMaintTime())
						|| (this.getLastMaintTime() != null && castOther.getLastMaintTime() != null
								&& this.getLastMaintTime().equals(castOther.getLastMaintTime())))
				&& ((this.getLastMaintTimeUom() == castOther.getLastMaintTimeUom())
						|| (this.getLastMaintTimeUom() != null && castOther.getLastMaintTimeUom() != null
								&& this.getLastMaintTimeUom().equals(castOther.getLastMaintTimeUom())))
				&& ((this.getLoadSinceLastMaint() == castOther.getLoadSinceLastMaint())
						|| (this.getLoadSinceLastMaint() != null && castOther.getLoadSinceLastMaint() != null
								&& this.getLoadSinceLastMaint().equals(castOther.getLoadSinceLastMaint())))
				&& ((this.getLoadSinceUom() == castOther.getLoadSinceUom())
						|| (this.getLoadSinceUom() != null && castOther.getLoadSinceUom() != null
								&& this.getLoadSinceUom().equals(castOther.getLoadSinceUom())))
				&& ((this.getMaximumUtilLevel() == castOther.getMaximumUtilLevel())
						|| (this.getMaximumUtilLevel() != null && castOther.getMaximumUtilLevel() != null
								&& this.getMaximumUtilLevel().equals(castOther.getMaximumUtilLevel())))
				&& ((this.getMinOpTimeCalName() == castOther.getMinOpTimeCalName())
						|| (this.getMinOpTimeCalName() != null && castOther.getMinOpTimeCalName() != null
								&& this.getMinOpTimeCalName().equals(castOther.getMinOpTimeCalName())))
				&& ((this.getMinQueueConfLength() == castOther.getMinQueueConfLength())
						|| (this.getMinQueueConfLength() != null && castOther.getMinQueueConfLength() != null
								&& this.getMinQueueConfLength().equals(castOther.getMinQueueConfLength())))
				&& ((this.getMinQueueConfUom() == castOther.getMinQueueConfUom())
						|| (this.getMinQueueConfUom() != null && castOther.getMinQueueConfUom() != null
								&& this.getMinQueueConfUom().equals(castOther.getMinQueueConfUom())))
				&& ((this.getMinimumUtilLevel() == castOther.getMinimumUtilLevel())
						|| (this.getMinimumUtilLevel() != null && castOther.getMinimumUtilLevel() != null
								&& this.getMinimumUtilLevel().equals(castOther.getMinimumUtilLevel())))
				&& ((this.getOffloadableFrom() == castOther.getOffloadableFrom())
						|| (this.getOffloadableFrom() != null && castOther.getOffloadableFrom() != null
								&& this.getOffloadableFrom().equals(castOther.getOffloadableFrom())))
				&& ((this.getOffloadableTo() == castOther.getOffloadableTo())
						|| (this.getOffloadableTo() != null && castOther.getOffloadableTo() != null
								&& this.getOffloadableTo().equals(castOther.getOffloadableTo())))
				&& ((this.getOvertimeBasis() == castOther.getOvertimeBasis())
						|| (this.getOvertimeBasis() != null && castOther.getOvertimeBasis() != null
								&& this.getOvertimeBasis().equals(castOther.getOvertimeBasis())))
				&& ((this.getObertimeBasisUom() == castOther.getObertimeBasisUom())
						|| (this.getObertimeBasisUom() != null && castOther.getObertimeBasisUom() != null
								&& this.getObertimeBasisUom().equals(castOther.getObertimeBasisUom())))
				&& ((this.getOvertimeThreshold() == castOther.getOvertimeThreshold())
						|| (this.getOvertimeThreshold() != null && castOther.getOvertimeThreshold() != null
								&& this.getOvertimeThreshold().equals(castOther.getOvertimeThreshold())))
				&& ((this.getOvertimeThresholdUom() == castOther.getOvertimeThresholdUom())
						|| (this.getOvertimeThresholdUom() != null && castOther.getOvertimeThresholdUom() != null
								&& this.getOvertimeThresholdUom().equals(castOther.getOvertimeThresholdUom())))
				&& ((this.getProcessedMaterialTypes() == castOther.getProcessedMaterialTypes())
						|| (this.getProcessedMaterialTypes() != null && castOther.getProcessedMaterialTypes() != null
								&& this.getProcessedMaterialTypes().equals(castOther.getProcessedMaterialTypes())))
				&& ((this.getQueueSizeUom() == castOther.getQueueSizeUom())
						|| (this.getQueueSizeUom() != null && castOther.getQueueSizeUom() != null
								&& this.getQueueSizeUom().equals(castOther.getQueueSizeUom())))
				&& ((this.getSchedulingCriticality() == castOther.getSchedulingCriticality())
						|| (this.getSchedulingCriticality() != null && castOther.getSchedulingCriticality() != null
								&& this.getSchedulingCriticality().equals(castOther.getSchedulingCriticality())))
				&& ((this.getUnitSetupCostPer() == castOther.getUnitSetupCostPer())
						|| (this.getUnitSetupCostPer() != null && castOther.getUnitSetupCostPer() != null
								&& this.getUnitSetupCostPer().equals(castOther.getUnitSetupCostPer())))
				&& ((this.getUnitSetupCostPerTime() == castOther.getUnitSetupCostPerTime())
						|| (this.getUnitSetupCostPerTime() != null && castOther.getUnitSetupCostPerTime() != null
								&& this.getUnitSetupCostPerTime().equals(castOther.getUnitSetupCostPerTime())))
				&& ((this.getCaoPostProcDownstream() == castOther.getCaoPostProcDownstream())
						|| (this.getCaoPostProcDownstream() != null && castOther.getCaoPostProcDownstream() != null
								&& this.getCaoPostProcDownstream().equals(castOther.getCaoPostProcDownstream())))
				&& ((this.getKeepRelatedTasksTog() == castOther.getKeepRelatedTasksTog())
						|| (this.getKeepRelatedTasksTog() != null && castOther.getKeepRelatedTasksTog() != null
								&& this.getKeepRelatedTasksTog().equals(castOther.getKeepRelatedTasksTog())))
				&& ((this.getPreIcpOlRuntimeRatio() == castOther.getPreIcpOlRuntimeRatio())
						|| (this.getPreIcpOlRuntimeRatio() != null && castOther.getPreIcpOlRuntimeRatio() != null
								&& this.getPreIcpOlRuntimeRatio().equals(castOther.getPreIcpOlRuntimeRatio())))
				&& ((this.getSimulHierSetups() == castOther.getSimulHierSetups())
						|| (this.getSimulHierSetups() != null && castOther.getSimulHierSetups() != null
								&& this.getSimulHierSetups().equals(castOther.getSimulHierSetups())))
				&& ((this.getIgnoreForCapPlan() == castOther.getIgnoreForCapPlan())
						|| (this.getIgnoreForCapPlan() != null && castOther.getIgnoreForCapPlan() != null
								&& this.getIgnoreForCapPlan().equals(castOther.getIgnoreForCapPlan())))
				&& ((this.getNoneneeddispatch() == castOther.getNoneneeddispatch())
						|| (this.getNoneneeddispatch() != null && castOther.getNoneneeddispatch() != null
								&& this.getNoneneeddispatch().equals(castOther.getNoneneeddispatch())))
				&& ((this.getResourceref() == castOther.getResourceref())
						|| (this.getResourceref() != null && castOther.getResourceref() != null
								&& this.getResourceref().equals(castOther.getResourceref())))
				&& ((this.getCriticalLevel() == castOther.getCriticalLevel())
						|| (this.getCriticalLevel() != null && castOther.getCriticalLevel() != null
								&& this.getCriticalLevel().equals(castOther.getCriticalLevel())))
				&& ((this.getNeedNc() == castOther.getNeedNc()) || (this.getNeedNc() != null
						&& castOther.getNeedNc() != null && this.getNeedNc().equals(castOther.getNeedNc())))
				&& ((this.getRestype() == castOther.getRestype()) || (this.getRestype() != null
						&& castOther.getRestype() != null && this.getRestype().equals(castOther.getRestype())))
				&& ((this.getMonthplanwork() == castOther.getMonthplanwork())
						|| (this.getMonthplanwork() != null && castOther.getMonthplanwork() != null
								&& this.getMonthplanwork().equals(castOther.getMonthplanwork())))
				&& ((this.getOptype() == castOther.getOptype()) || (this.getOptype() != null
						&& castOther.getOptype() != null && this.getOptype().equals(castOther.getOptype())))
				&& ((this.getRResourceOutUid() == castOther.getRResourceOutUid())
						|| (this.getRResourceOutUid() != null && castOther.getRResourceOutUid() != null
								&& this.getRResourceOutUid().equals(castOther.getRResourceOutUid())))
				&& ((this.getResstate() == castOther.getResstate()) || (this.getResstate() != null
						&& castOther.getResstate() != null && this.getResstate().equals(castOther.getResstate())))
				&& ((this.getCustomerResuid() == castOther.getCustomerResuid())
						|| (this.getCustomerResuid() != null && castOther.getCustomerResuid() != null
								&& this.getCustomerResuid().equals(castOther.getCustomerResuid())))
				&& ((this.getToolShankSpec() == castOther.getToolShankSpec())
						|| (this.getToolShankSpec() != null && castOther.getToolShankSpec() != null
								&& this.getToolShankSpec().equals(castOther.getToolShankSpec())))
				&& ((this.getNcSysModel() == castOther.getNcSysModel()) || (this.getNcSysModel() != null
						&& castOther.getNcSysModel() != null && this.getNcSysModel().equals(castOther.getNcSysModel())))
				&& ((this.getDeviceTableCount() == castOther.getDeviceTableCount())
						|| (this.getDeviceTableCount() != null && castOther.getDeviceTableCount() != null
								&& this.getDeviceTableCount().equals(castOther.getDeviceTableCount())))
				&& ((this.getCurrentEmployeeid() == castOther.getCurrentEmployeeid())
						|| (this.getCurrentEmployeeid() != null && castOther.getCurrentEmployeeid() != null
								&& this.getCurrentEmployeeid().equals(castOther.getCurrentEmployeeid())))
				&& ((this.getBottleneckLevel() == castOther.getBottleneckLevel())
						|| (this.getBottleneckLevel() != null && castOther.getBottleneckLevel() != null
								&& this.getBottleneckLevel().equals(castOther.getBottleneckLevel())))
				&& ((this.getResourceunits() == castOther.getResourceunits())
						|| (this.getResourceunits() != null && castOther.getResourceunits() != null
								&& this.getResourceunits().equals(castOther.getResourceunits())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getResuid() == null ? 0 : this.getResuid().hashCode());
		result = 37 * result + (getResname() == null ? 0 : this.getResname().hashCode());
		result = 37 * result + (getCalUid() == null ? 0 : this.getCalUid().hashCode());
		result = 37 * result + (getDeptid() == null ? 0 : this.getDeptid().hashCode());
		result = 37 * result + (getResourcetype() == null ? 0 : this.getResourcetype().hashCode());
		result = 37 * result + (getLocation() == null ? 0 : this.getLocation().hashCode());
		result = 37 * result + (getNumOfPooledResources() == null ? 0 : this.getNumOfPooledResources().hashCode());
		result = 37 * result + (getEstimatedQueueTime() == null ? 0 : this.getEstimatedQueueTime().hashCode());
		result = 37 * result + (getEstimatedQueueTimeUom() == null ? 0 : this.getEstimatedQueueTimeUom().hashCode());
		result = 37 * result + (getDefaultSetupTime() == null ? 0 : this.getDefaultSetupTime().hashCode());
		result = 37 * result + (getDefaultTimeUom() == null ? 0 : this.getDefaultTimeUom().hashCode());
		result = 37 * result + (getIdealUtilizationLevel() == null ? 0 : this.getIdealUtilizationLevel().hashCode());
		result = 37 * result + (getIdealUtilCalName() == null ? 0 : this.getIdealUtilCalName().hashCode());
		result = 37 * result + (getWageRatePer() == null ? 0 : this.getWageRatePer().hashCode());
		result = 37 * result + (getWageRatePerTime() == null ? 0 : this.getWageRatePerTime().hashCode());
		result = 37 * result + (getSetupMatrixId() == null ? 0 : this.getSetupMatrixId().hashCode());
		result = 37 * result + (getSetupSequenceId() == null ? 0 : this.getSetupSequenceId().hashCode());
		result = 37 * result + (getSetupSequenceGoback() == null ? 0 : this.getSetupSequenceGoback().hashCode());
		result = 37 * result + (getMinimumQueueTime() == null ? 0 : this.getMinimumQueueTime().hashCode());
		result = 37 * result + (getMinimumQueueTimeUom() == null ? 0 : this.getMinimumQueueTimeUom().hashCode());
		result = 37 * result + (getModelName() == null ? 0 : this.getModelName().hashCode());
		result = 37 * result + (getScheduleFreezeHorizon() == null ? 0 : this.getScheduleFreezeHorizon().hashCode());
		result = 37 * result + (getSfhUom() == null ? 0 : this.getSfhUom().hashCode());
		result = 37 * result + (getBatchingHorizon() == null ? 0 : this.getBatchingHorizon().hashCode());
		result = 37 * result + (getBatchingHorizonUom() == null ? 0 : this.getBatchingHorizonUom().hashCode());
		result = 37 * result + (getBatchingLookahead() == null ? 0 : this.getBatchingLookahead().hashCode());
		result = 37 * result + (getBatchingLookaheadUom() == null ? 0 : this.getBatchingLookaheadUom().hashCode());
		result = 37 * result + (getLatenessTolerance() == null ? 0 : this.getLatenessTolerance().hashCode());
		result = 37 * result + (getLatenessToleranceUom() == null ? 0 : this.getLatenessToleranceUom().hashCode());
		result = 37 * result + (getEarlinessTolerance() == null ? 0 : this.getEarlinessTolerance().hashCode());
		result = 37 * result + (getEarlinessToleranceUom() == null ? 0 : this.getEarlinessToleranceUom().hashCode());
		result = 37 * result + (getQueueSizeMode() == null ? 0 : this.getQueueSizeMode().hashCode());
		result = 37 * result + (getMaxQueueSize() == null ? 0 : this.getMaxQueueSize().hashCode());
		result = 37 * result + (getQueueConformanceMode() == null ? 0 : this.getQueueConformanceMode().hashCode());
		result = 37 * result + (getOutputRateLimit() == null ? 0 : this.getOutputRateLimit().hashCode());
		result = 37 * result + (getOutputRateLimitPer() == null ? 0 : this.getOutputRateLimitPer().hashCode());
		result = 37 * result + (getOutputRateLimitUom() == null ? 0 : this.getOutputRateLimitUom().hashCode());
		result = 37 * result + (getLowRwt() == null ? 0 : this.getLowRwt().hashCode());
		result = 37 * result + (getLowRwtPer() == null ? 0 : this.getLowRwtPer().hashCode());
		result = 37 * result + (getLowRwtUom() == null ? 0 : this.getLowRwtUom().hashCode());
		result = 37 * result + (getHighRwtUom() == null ? 0 : this.getHighRwtUom().hashCode());
		result = 37 * result + (getHighRwtPer() == null ? 0 : this.getHighRwtPer().hashCode());
		result = 37 * result + (getHighRwt() == null ? 0 : this.getHighRwt().hashCode());
		result = 37 * result + (getAcmFlag() == null ? 0 : this.getAcmFlag().hashCode());
		result = 37 * result + (getIncOvertimeCostPer() == null ? 0 : this.getIncOvertimeCostPer().hashCode());
		result = 37 * result + (getIncOvertimeCostPerT() == null ? 0 : this.getIncOvertimeCostPerT().hashCode());
		result = 37 * result + (getLastMaintDate() == null ? 0 : this.getLastMaintDate().hashCode());
		result = 37 * result + (getLastMaintDateFormat() == null ? 0 : this.getLastMaintDateFormat().hashCode());
		result = 37 * result + (getLastMaintSeqNumber() == null ? 0 : this.getLastMaintSeqNumber().hashCode());
		result = 37 * result + (getLastMaintTime() == null ? 0 : this.getLastMaintTime().hashCode());
		result = 37 * result + (getLastMaintTimeUom() == null ? 0 : this.getLastMaintTimeUom().hashCode());
		result = 37 * result + (getLoadSinceLastMaint() == null ? 0 : this.getLoadSinceLastMaint().hashCode());
		result = 37 * result + (getLoadSinceUom() == null ? 0 : this.getLoadSinceUom().hashCode());
		result = 37 * result + (getMaximumUtilLevel() == null ? 0 : this.getMaximumUtilLevel().hashCode());
		result = 37 * result + (getMinOpTimeCalName() == null ? 0 : this.getMinOpTimeCalName().hashCode());
		result = 37 * result + (getMinQueueConfLength() == null ? 0 : this.getMinQueueConfLength().hashCode());
		result = 37 * result + (getMinQueueConfUom() == null ? 0 : this.getMinQueueConfUom().hashCode());
		result = 37 * result + (getMinimumUtilLevel() == null ? 0 : this.getMinimumUtilLevel().hashCode());
		result = 37 * result + (getOffloadableFrom() == null ? 0 : this.getOffloadableFrom().hashCode());
		result = 37 * result + (getOffloadableTo() == null ? 0 : this.getOffloadableTo().hashCode());
		result = 37 * result + (getOvertimeBasis() == null ? 0 : this.getOvertimeBasis().hashCode());
		result = 37 * result + (getObertimeBasisUom() == null ? 0 : this.getObertimeBasisUom().hashCode());
		result = 37 * result + (getOvertimeThreshold() == null ? 0 : this.getOvertimeThreshold().hashCode());
		result = 37 * result + (getOvertimeThresholdUom() == null ? 0 : this.getOvertimeThresholdUom().hashCode());
		result = 37 * result + (getProcessedMaterialTypes() == null ? 0 : this.getProcessedMaterialTypes().hashCode());
		result = 37 * result + (getQueueSizeUom() == null ? 0 : this.getQueueSizeUom().hashCode());
		result = 37 * result + (getSchedulingCriticality() == null ? 0 : this.getSchedulingCriticality().hashCode());
		result = 37 * result + (getUnitSetupCostPer() == null ? 0 : this.getUnitSetupCostPer().hashCode());
		result = 37 * result + (getUnitSetupCostPerTime() == null ? 0 : this.getUnitSetupCostPerTime().hashCode());
		result = 37 * result + (getCaoPostProcDownstream() == null ? 0 : this.getCaoPostProcDownstream().hashCode());
		result = 37 * result + (getKeepRelatedTasksTog() == null ? 0 : this.getKeepRelatedTasksTog().hashCode());
		result = 37 * result + (getPreIcpOlRuntimeRatio() == null ? 0 : this.getPreIcpOlRuntimeRatio().hashCode());
		result = 37 * result + (getSimulHierSetups() == null ? 0 : this.getSimulHierSetups().hashCode());
		result = 37 * result + (getIgnoreForCapPlan() == null ? 0 : this.getIgnoreForCapPlan().hashCode());
		result = 37 * result + (getNoneneeddispatch() == null ? 0 : this.getNoneneeddispatch().hashCode());
		result = 37 * result + (getResourceref() == null ? 0 : this.getResourceref().hashCode());
		result = 37 * result + (getCriticalLevel() == null ? 0 : this.getCriticalLevel().hashCode());
		result = 37 * result + (getNeedNc() == null ? 0 : this.getNeedNc().hashCode());
		result = 37 * result + (getRestype() == null ? 0 : this.getRestype().hashCode());
		result = 37 * result + (getMonthplanwork() == null ? 0 : this.getMonthplanwork().hashCode());
		result = 37 * result + (getOptype() == null ? 0 : this.getOptype().hashCode());
		result = 37 * result + (getRResourceOutUid() == null ? 0 : this.getRResourceOutUid().hashCode());
		result = 37 * result + (getResstate() == null ? 0 : this.getResstate().hashCode());
		result = 37 * result + (getCustomerResuid() == null ? 0 : this.getCustomerResuid().hashCode());
		result = 37 * result + (getToolShankSpec() == null ? 0 : this.getToolShankSpec().hashCode());
		result = 37 * result + (getNcSysModel() == null ? 0 : this.getNcSysModel().hashCode());
		result = 37 * result + (getDeviceTableCount() == null ? 0 : this.getDeviceTableCount().hashCode());
		result = 37 * result + (getCurrentEmployeeid() == null ? 0 : this.getCurrentEmployeeid().hashCode());
		result = 37 * result + (getBottleneckLevel() == null ? 0 : this.getBottleneckLevel().hashCode());
		result = 37 * result + (getResourceunits() == null ? 0 : this.getResourceunits().hashCode());
		return result;
	}

}
