package com.mes.old.meta;
// Generated 2017-5-22 1:25:24 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;

/**
 * TWipReportdetail generated by hbm2java
 */
public class TWipReportdetail implements java.io.Serializable {

	private TWipReportdetailId id;
	private TWipReportheader TWipReportheader;
	private String notes;
	private String partNumber;
	private String batchnum;
	private BigDecimal carryover;
	private BigDecimal recieve;
	private BigDecimal deliver;
	private BigDecimal final_;
	private BigDecimal waster;
	private BigDecimal opuid;

	public TWipReportdetail() {
	}

	public TWipReportdetail(TWipReportdetailId id, TWipReportheader TWipReportheader) {
		this.id = id;
		this.TWipReportheader = TWipReportheader;
	}

	public TWipReportdetail(TWipReportdetailId id, TWipReportheader TWipReportheader, String notes, String partNumber,
			String batchnum, BigDecimal carryover, BigDecimal recieve, BigDecimal deliver, BigDecimal final_,
			BigDecimal waster, BigDecimal opuid) {
		this.id = id;
		this.TWipReportheader = TWipReportheader;
		this.notes = notes;
		this.partNumber = partNumber;
		this.batchnum = batchnum;
		this.carryover = carryover;
		this.recieve = recieve;
		this.deliver = deliver;
		this.final_ = final_;
		this.waster = waster;
		this.opuid = opuid;
	}

	public TWipReportdetailId getId() {
		return this.id;
	}

	public void setId(TWipReportdetailId id) {
		this.id = id;
	}

	public TWipReportheader getTWipReportheader() {
		return this.TWipReportheader;
	}

	public void setTWipReportheader(TWipReportheader TWipReportheader) {
		this.TWipReportheader = TWipReportheader;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getPartNumber() {
		return this.partNumber;
	}

	public void setPartNumber(String partNumber) {
		this.partNumber = partNumber;
	}

	public String getBatchnum() {
		return this.batchnum;
	}

	public void setBatchnum(String batchnum) {
		this.batchnum = batchnum;
	}

	public BigDecimal getCarryover() {
		return this.carryover;
	}

	public void setCarryover(BigDecimal carryover) {
		this.carryover = carryover;
	}

	public BigDecimal getRecieve() {
		return this.recieve;
	}

	public void setRecieve(BigDecimal recieve) {
		this.recieve = recieve;
	}

	public BigDecimal getDeliver() {
		return this.deliver;
	}

	public void setDeliver(BigDecimal deliver) {
		this.deliver = deliver;
	}

	public BigDecimal getFinal_() {
		return this.final_;
	}

	public void setFinal_(BigDecimal final_) {
		this.final_ = final_;
	}

	public BigDecimal getWaster() {
		return this.waster;
	}

	public void setWaster(BigDecimal waster) {
		this.waster = waster;
	}

	public BigDecimal getOpuid() {
		return this.opuid;
	}

	public void setOpuid(BigDecimal opuid) {
		this.opuid = opuid;
	}

}
